import { expect, test } from "@jest/globals";
import { Skill, Tree } from "../../types";
import { PlotTreeReingoldTiltfordAlgorithm } from "./general";

test("HierarchicalTree - Rairtha 1", () => {
    const treeToTest: Tree<Skill> = {
        treeName: "Art",
        accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
        isRoot: true,
        parentId: null,
        treeId: "XrWEpaPKRS68T09rlekrkwvY",
        level: 0,
        nodeId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
        category: "SKILL_TREE",
        children: [
            {
                accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
                treeId: "XrWEpaPKRS68T09rlekrkwvY",
                treeName: "Art",
                category: "SKILL",
                children: [
                    {
                        accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
                        treeId: "XrWEpaPKRS68T09rlekrkwvY",
                        treeName: "Art",
                        category: "SKILL",
                        children: [
                            {
                                accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
                                treeId: "XrWEpaPKRS68T09rlekrkwvY",
                                treeName: "Art",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "S",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "yB7Y5ZFbcvzobGbvDQIBhLBC",
                                parentId: "UydKvtvXuznmmprn39hDN7Uq",
                                x: 0,
                                y: 0,
                            },
                        ],
                        data: {
                            name: "Dd",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "UydKvtvXuznmmprn39hDN7Uq",
                        parentId: "6nHFVkOqhxQt1t0wJyPH6XVJ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
                        treeId: "XrWEpaPKRS68T09rlekrkwvY",
                        treeName: "Art",
                        category: "SKILL",
                        children: [
                            {
                                accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
                                treeId: "XrWEpaPKRS68T09rlekrkwvY",
                                treeName: "Art",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "A",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "OeC54kCCSD4l9hhc1V7QkJUA",
                                parentId: "o5ZUPWxtFKnBB30tuAw8Xd9w",
                                x: 0,
                                y: 0,
                            },
                            {
                                accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
                                treeId: "XrWEpaPKRS68T09rlekrkwvY",
                                treeName: "Art",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "B",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "zKJi6y5UdSrQOx4ySeX5djPm",
                                parentId: "o5ZUPWxtFKnBB30tuAw8Xd9w",
                                x: 0,
                                y: 0,
                            },
                            {
                                accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
                                treeId: "XrWEpaPKRS68T09rlekrkwvY",
                                treeName: "Art",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "C",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "QOEus1TQ0uHqbW2QYsHoPDGt",
                                parentId: "o5ZUPWxtFKnBB30tuAw8Xd9w",
                                x: 0,
                                y: 0,
                            },
                        ],
                        data: {
                            name: "Cf",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "o5ZUPWxtFKnBB30tuAw8Xd9w",
                        parentId: "6nHFVkOqhxQt1t0wJyPH6XVJ",
                        x: 0,
                        y: 0,
                    },
                ],
                data: {
                    name: "A",
                    isCompleted: false,
                    icon: { isEmoji: false, text: "" },
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    usefulResources: [],
                },
                isRoot: false,
                level: 1,
                nodeId: "6nHFVkOqhxQt1t0wJyPH6XVJ",
                parentId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
                x: 0,
                y: 0,
            },
            {
                accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
                treeId: "XrWEpaPKRS68T09rlekrkwvY",
                treeName: "Art",
                category: "SKILL",
                children: [],
                data: {
                    name: "B",
                    isCompleted: false,
                    icon: { isEmoji: false, text: "" },
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    usefulResources: [],
                },
                isRoot: false,
                level: 1,
                nodeId: "cquIn5zeC4f8fvLQKK2PV2mM",
                parentId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
                x: 0,
                y: 0,
            },
            {
                accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
                treeId: "XrWEpaPKRS68T09rlekrkwvY",
                treeName: "Art",
                category: "SKILL",
                children: [],
                data: {
                    name: "C",
                    isCompleted: false,
                    icon: { isEmoji: false, text: "" },
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    usefulResources: [],
                },
                isRoot: false,
                level: 1,
                nodeId: "juEwrhtZAQ7ZMFm4Y44jG4Ru",
                parentId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
                x: 0,
                y: 0,
            },
        ],
        x: 0,
        y: 0,
        data: {
            name: "Art",
            isCompleted: false,
            icon: { isEmoji: false, text: "A" },
            logs: [],
            milestones: [],
            motivesToLearn: [],
            usefulResources: [],
        },
    };

    const result = [
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "S",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "yB7Y5ZFbcvzobGbvDQIBhLBC",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            treeName: "Art",
            x: -1.5,
            y: 3,
            level: 3,
            parentId: "UydKvtvXuznmmprn39hDN7Uq",
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "Dd",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "UydKvtvXuznmmprn39hDN7Uq",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            treeName: "Art",
            x: -1.5,
            y: 2,
            level: 2,
            parentId: "6nHFVkOqhxQt1t0wJyPH6XVJ",
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "A",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "OeC54kCCSD4l9hhc1V7QkJUA",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            treeName: "Art",
            x: -0.5,
            y: 3,
            level: 3,
            parentId: "o5ZUPWxtFKnBB30tuAw8Xd9w",
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "B",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "zKJi6y5UdSrQOx4ySeX5djPm",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            treeName: "Art",
            x: 0.5,
            y: 3,
            level: 3,
            parentId: "o5ZUPWxtFKnBB30tuAw8Xd9w",
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "C",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "QOEus1TQ0uHqbW2QYsHoPDGt",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            treeName: "Art",
            x: 1.5,
            y: 3,
            level: 3,
            parentId: "o5ZUPWxtFKnBB30tuAw8Xd9w",
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "Cf",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "o5ZUPWxtFKnBB30tuAw8Xd9w",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            treeName: "Art",
            x: 0.5,
            y: 2,
            level: 2,
            parentId: "6nHFVkOqhxQt1t0wJyPH6XVJ",
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "A",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "6nHFVkOqhxQt1t0wJyPH6XVJ",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            treeName: "Art",
            x: -0.5,
            y: 1,
            level: 1,
            parentId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "B",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "cquIn5zeC4f8fvLQKK2PV2mM",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            treeName: "Art",
            x: 0.5,
            y: 1,
            level: 1,
            parentId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "C",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "juEwrhtZAQ7ZMFm4Y44jG4Ru",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            treeName: "Art",
            x: 1.5,
            y: 1,
            level: 1,
            parentId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "Art",
                isCompleted: false,
                icon: { isEmoji: false, text: "A" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: true,
            category: "SKILL_TREE",
            nodeId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            treeName: "Art",
            x: 0.5,
            y: 0,
            level: 0,
            parentId: null,
        },
    ];

    expect(PlotTreeReingoldTiltfordAlgorithm(treeToTest)).toStrictEqual(result);
});

test("HierarchicalTree - Rairtha 2", () => {
    const treeToTest: Tree<Skill> = {
        treeName: "Degree",
        accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
        isRoot: true,
        parentId: null,
        treeId: "T60Qxm83DTSZYOLsULl78DZZ",
        level: 0,
        nodeId: "xo1pn5U1LbbyB1WpQqlGzjSC",
        category: "SKILL_TREE",
        children: [
            {
                accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
                treeId: "T60Qxm83DTSZYOLsULl78DZZ",
                treeName: "Degree",
                category: "SKILL",
                children: [
                    {
                        accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
                        treeId: "T60Qxm83DTSZYOLsULl78DZZ",
                        treeName: "Degree",
                        category: "SKILL",
                        children: [
                            {
                                accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
                                treeId: "T60Qxm83DTSZYOLsULl78DZZ",
                                treeName: "Degree",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "A",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "W4cebJSthJvkS687FcB6v4SE",
                                parentId: "PLqLY3zrO1rje2LdoypEuHtp",
                                x: 0,
                                y: 0,
                            },
                            {
                                accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
                                treeId: "T60Qxm83DTSZYOLsULl78DZZ",
                                treeName: "Degree",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "B",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "OAEoTmtL2CQfBKkGOLtoOpKu",
                                parentId: "PLqLY3zrO1rje2LdoypEuHtp",
                                x: 0,
                                y: 0,
                            },
                            {
                                accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
                                treeId: "T60Qxm83DTSZYOLsULl78DZZ",
                                treeName: "Degree",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "C",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "iaYRS8Ay7HBCXmVpuYqXwzaC",
                                parentId: "PLqLY3zrO1rje2LdoypEuHtp",
                                x: 0,
                                y: 0,
                            },
                        ],
                        data: {
                            name: "Dkkd",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "PLqLY3zrO1rje2LdoypEuHtp",
                        parentId: "c1nWxT1H0LdIJoIeqzpW9jTQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
                        treeId: "T60Qxm83DTSZYOLsULl78DZZ",
                        treeName: "Degree",
                        category: "SKILL",
                        children: [
                            {
                                accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
                                treeId: "T60Qxm83DTSZYOLsULl78DZZ",
                                treeName: "Degree",
                                category: "SKILL",
                                children: [
                                    {
                                        accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
                                        treeId: "T60Qxm83DTSZYOLsULl78DZZ",
                                        treeName: "Degree",
                                        category: "SKILL",
                                        children: [],
                                        data: {
                                            name: "S",
                                            isCompleted: false,
                                            icon: { isEmoji: false, text: "" },
                                            logs: [],
                                            milestones: [],
                                            motivesToLearn: [],
                                            usefulResources: [],
                                        },
                                        isRoot: false,
                                        level: 4,
                                        nodeId: "7ADT00vLlw0DrwbmeAunKEp6",
                                        parentId: "e7OpGNO7tuoSA4rfoTOzBxtW",
                                        x: 0,
                                        y: 0,
                                    },
                                    {
                                        accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
                                        treeId: "T60Qxm83DTSZYOLsULl78DZZ",
                                        treeName: "Degree",
                                        category: "SKILL",
                                        children: [],
                                        data: {
                                            name: "V",
                                            isCompleted: false,
                                            icon: { isEmoji: false, text: "" },
                                            logs: [],
                                            milestones: [],
                                            motivesToLearn: [],
                                            usefulResources: [],
                                        },
                                        isRoot: false,
                                        level: 4,
                                        nodeId: "35QXTiMkasFfiV9rAI0aZl4N",
                                        parentId: "e7OpGNO7tuoSA4rfoTOzBxtW",
                                        x: 0,
                                        y: 0,
                                    },
                                    {
                                        accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
                                        treeId: "T60Qxm83DTSZYOLsULl78DZZ",
                                        treeName: "Degree",
                                        category: "SKILL",
                                        children: [],
                                        data: {
                                            name: "X",
                                            isCompleted: false,
                                            icon: { isEmoji: false, text: "" },
                                            logs: [],
                                            milestones: [],
                                            motivesToLearn: [],
                                            usefulResources: [],
                                        },
                                        isRoot: false,
                                        level: 4,
                                        nodeId: "RWsXbYYVUkKhw53TnhY7yeHX",
                                        parentId: "e7OpGNO7tuoSA4rfoTOzBxtW",
                                        x: 0,
                                        y: 0,
                                    },
                                ],
                                data: {
                                    name: "F",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "e7OpGNO7tuoSA4rfoTOzBxtW",
                                parentId: "C4pjCLvMIUdw39PsreMyrgb8",
                                x: 0,
                                y: 0,
                            },
                            {
                                accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
                                treeId: "T60Qxm83DTSZYOLsULl78DZZ",
                                treeName: "Degree",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "F",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "jd1qoiMqoHS2cC9YWiid5jky",
                                parentId: "C4pjCLvMIUdw39PsreMyrgb8",
                                x: 0,
                                y: 0,
                            },
                            {
                                accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
                                treeId: "T60Qxm83DTSZYOLsULl78DZZ",
                                treeName: "Degree",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "F",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "NGimcP0Rzo17y2hK2cB3193i",
                                parentId: "C4pjCLvMIUdw39PsreMyrgb8",
                                x: 0,
                                y: 0,
                            },
                            {
                                accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
                                treeId: "T60Qxm83DTSZYOLsULl78DZZ",
                                treeName: "Degree",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "D",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "iWf29Z73Xp0IfMfJnLO5cNWC",
                                parentId: "C4pjCLvMIUdw39PsreMyrgb8",
                                x: 0,
                                y: 0,
                            },
                        ],
                        data: {
                            name: "Coo",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "C4pjCLvMIUdw39PsreMyrgb8",
                        parentId: "c1nWxT1H0LdIJoIeqzpW9jTQ",
                        x: 0,
                        y: 0,
                    },
                ],
                data: {
                    name: "Uno",
                    isCompleted: false,
                    icon: { isEmoji: false, text: "" },
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    usefulResources: [],
                },
                isRoot: false,
                level: 1,
                nodeId: "c1nWxT1H0LdIJoIeqzpW9jTQ",
                parentId: "xo1pn5U1LbbyB1WpQqlGzjSC",
                x: 0,
                y: 0,
            },
            {
                accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
                treeId: "T60Qxm83DTSZYOLsULl78DZZ",
                treeName: "Degree",
                category: "SKILL",
                children: [],
                data: {
                    name: "Dos",
                    isCompleted: false,
                    icon: { isEmoji: false, text: "" },
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    usefulResources: [],
                },
                isRoot: false,
                level: 1,
                nodeId: "OO2ZEOy17klSkQeUjlNIEDyC",
                parentId: "xo1pn5U1LbbyB1WpQqlGzjSC",
                x: 0,
                y: 0,
            },
        ],
        x: 0,
        y: 0,
        data: {
            name: "Degree",
            isCompleted: false,
            icon: { isEmoji: false, text: "D" },
            logs: [],
            milestones: [],
            motivesToLearn: [],
            usefulResources: [],
        },
    };

    const result = [
        {
            accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
            data: {
                name: "A",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "W4cebJSthJvkS687FcB6v4SE",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            treeName: "Degree",
            x: -2,
            y: 3,
            level: 3,
            parentId: "PLqLY3zrO1rje2LdoypEuHtp",
        },
        {
            accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
            data: {
                name: "B",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "OAEoTmtL2CQfBKkGOLtoOpKu",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            treeName: "Degree",
            x: -1,
            y: 3,
            level: 3,
            parentId: "PLqLY3zrO1rje2LdoypEuHtp",
        },
        {
            accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
            data: {
                name: "C",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "iaYRS8Ay7HBCXmVpuYqXwzaC",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            treeName: "Degree",
            x: 0,
            y: 3,
            level: 3,
            parentId: "PLqLY3zrO1rje2LdoypEuHtp",
        },
        {
            accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
            data: {
                name: "Dkkd",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "PLqLY3zrO1rje2LdoypEuHtp",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            treeName: "Degree",
            x: -1,
            y: 2,
            level: 2,
            parentId: "c1nWxT1H0LdIJoIeqzpW9jTQ",
        },
        {
            accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
            data: {
                name: "S",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "7ADT00vLlw0DrwbmeAunKEp6",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            treeName: "Degree",
            x: 0,
            y: 4,
            level: 4,
            parentId: "e7OpGNO7tuoSA4rfoTOzBxtW",
        },
        {
            accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
            data: {
                name: "V",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "35QXTiMkasFfiV9rAI0aZl4N",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            treeName: "Degree",
            x: 1,
            y: 4,
            level: 4,
            parentId: "e7OpGNO7tuoSA4rfoTOzBxtW",
        },
        {
            accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
            data: {
                name: "X",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "RWsXbYYVUkKhw53TnhY7yeHX",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            treeName: "Degree",
            x: 2,
            y: 4,
            level: 4,
            parentId: "e7OpGNO7tuoSA4rfoTOzBxtW",
        },
        {
            accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
            data: {
                name: "F",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "e7OpGNO7tuoSA4rfoTOzBxtW",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            treeName: "Degree",
            x: 1,
            y: 3,
            level: 3,
            parentId: "C4pjCLvMIUdw39PsreMyrgb8",
        },
        {
            accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
            data: {
                name: "F",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "jd1qoiMqoHS2cC9YWiid5jky",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            treeName: "Degree",
            x: 2,
            y: 3,
            level: 3,
            parentId: "C4pjCLvMIUdw39PsreMyrgb8",
        },
        {
            accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
            data: {
                name: "F",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "NGimcP0Rzo17y2hK2cB3193i",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            treeName: "Degree",
            x: 3,
            y: 3,
            level: 3,
            parentId: "C4pjCLvMIUdw39PsreMyrgb8",
        },
        {
            accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
            data: {
                name: "D",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "iWf29Z73Xp0IfMfJnLO5cNWC",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            treeName: "Degree",
            x: 4,
            y: 3,
            level: 3,
            parentId: "C4pjCLvMIUdw39PsreMyrgb8",
        },
        {
            accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
            data: {
                name: "Coo",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "C4pjCLvMIUdw39PsreMyrgb8",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            treeName: "Degree",
            x: 2.5,
            y: 2,
            level: 2,
            parentId: "c1nWxT1H0LdIJoIeqzpW9jTQ",
        },
        {
            accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
            data: {
                name: "Uno",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "c1nWxT1H0LdIJoIeqzpW9jTQ",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            treeName: "Degree",
            x: 0.75,
            y: 1,
            level: 1,
            parentId: "xo1pn5U1LbbyB1WpQqlGzjSC",
        },
        {
            accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
            data: {
                name: "Dos",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "OO2ZEOy17klSkQeUjlNIEDyC",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            treeName: "Degree",
            x: 1.75,
            y: 1,
            level: 1,
            parentId: "xo1pn5U1LbbyB1WpQqlGzjSC",
        },
        {
            accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
            data: {
                name: "Degree",
                isCompleted: false,
                icon: { isEmoji: false, text: "D" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: true,
            category: "SKILL_TREE",
            nodeId: "xo1pn5U1LbbyB1WpQqlGzjSC",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            treeName: "Degree",
            x: 1.25,
            y: 0,
            level: 0,
            parentId: null,
        },
    ];

    expect(PlotTreeReingoldTiltfordAlgorithm(treeToTest)).toStrictEqual(result);
});

test("HierarchicalTree - Rairtha 3", () => {
    const treeToTest: Tree<Skill> = {
        treeName: "Moneys",
        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
        isRoot: true,
        parentId: null,
        treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
        level: 0,
        nodeId: "ZaP524wLoByB2YUJZha99ELz",
        category: "SKILL_TREE",
        children: [
            {
                accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                treeName: "Moneys",
                category: "SKILL",
                children: [
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                        treeName: "Moneys",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "B",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "5q0IMY79rAneVeAHSwRgm8AM",
                        parentId: "EaTStq4s6zIxltcjd0MTaLKS",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                        treeName: "Moneys",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "S",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "NRfw8131hOoU3VPgCoQJSBai",
                        parentId: "EaTStq4s6zIxltcjd0MTaLKS",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                        treeName: "Moneys",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "J",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "qsVTkuD9OZ9I5Xl7j3Oib1Ox",
                        parentId: "EaTStq4s6zIxltcjd0MTaLKS",
                        x: 0,
                        y: 0,
                    },
                ],
                data: {
                    name: "B",
                    isCompleted: false,
                    icon: { isEmoji: false, text: "" },
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    usefulResources: [],
                },
                isRoot: false,
                level: 1,
                nodeId: "EaTStq4s6zIxltcjd0MTaLKS",
                parentId: "ZaP524wLoByB2YUJZha99ELz",
                x: 0,
                y: 0,
            },
            {
                accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                treeName: "Moneys",
                category: "SKILL",
                children: [
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                        treeName: "Moneys",
                        category: "SKILL",
                        children: [
                            {
                                accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                                treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                                treeName: "Moneys",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "L",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "eUVW3NvIA3K2JT4cS8Vt4idV",
                                parentId: "R2uls2cGeedOezadmH92BHu8",
                                x: 0,
                                y: 0,
                            },
                        ],
                        data: {
                            name: "H",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "R2uls2cGeedOezadmH92BHu8",
                        parentId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                        treeName: "Moneys",
                        category: "SKILL",
                        children: [
                            {
                                accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                                treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                                treeName: "Moneys",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "H",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "bz8QsifzNWuC68BcjQ9KSrq6",
                                parentId: "aIEQEcZwCzYjLK2hHkvso7vB",
                                x: 0,
                                y: 0,
                            },
                        ],
                        data: {
                            name: "M",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "aIEQEcZwCzYjLK2hHkvso7vB",
                        parentId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
                        x: 0,
                        y: 0,
                    },
                ],
                data: {
                    name: "A",
                    isCompleted: false,
                    icon: { isEmoji: false, text: "" },
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    usefulResources: [],
                },
                isRoot: false,
                level: 1,
                nodeId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
                parentId: "ZaP524wLoByB2YUJZha99ELz",
                x: 0,
                y: 0,
            },
            {
                accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                treeName: "Moneys",
                category: "SKILL",
                children: [
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                        treeName: "Moneys",
                        category: "SKILL",
                        children: [
                            {
                                accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                                treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                                treeName: "Moneys",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "Ghh",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "qiDTAMbKL2LqI7oPTlDISWUd",
                                parentId: "8Gp9OHcp6orUxdHjSfpaVUAH",
                                x: 0,
                                y: 0,
                            },
                        ],
                        data: {
                            name: "G",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "8Gp9OHcp6orUxdHjSfpaVUAH",
                        parentId: "nFC97sH2HjHgdirs9DcHO4wb",
                        x: 0,
                        y: 0,
                    },
                ],
                data: {
                    name: "C",
                    isCompleted: false,
                    icon: { isEmoji: false, text: "" },
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    usefulResources: [],
                },
                isRoot: false,
                level: 1,
                nodeId: "nFC97sH2HjHgdirs9DcHO4wb",
                parentId: "ZaP524wLoByB2YUJZha99ELz",
                x: 0,
                y: 0,
            },
        ],
        x: 0,
        y: 0,
        data: {
            name: "Moneys",
            isCompleted: false,
            icon: { isEmoji: false, text: "M" },
            logs: [],
            milestones: [],
            motivesToLearn: [],
            usefulResources: [],
        },
    };

    const result = [
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "B",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "5q0IMY79rAneVeAHSwRgm8AM",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: -2,
            y: 2,
            level: 2,
            parentId: "EaTStq4s6zIxltcjd0MTaLKS",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "S",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "NRfw8131hOoU3VPgCoQJSBai",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: -1,
            y: 2,
            level: 2,
            parentId: "EaTStq4s6zIxltcjd0MTaLKS",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "J",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "qsVTkuD9OZ9I5Xl7j3Oib1Ox",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 0,
            y: 2,
            level: 2,
            parentId: "EaTStq4s6zIxltcjd0MTaLKS",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "B",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "EaTStq4s6zIxltcjd0MTaLKS",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: -1,
            y: 1,
            level: 1,
            parentId: "ZaP524wLoByB2YUJZha99ELz",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "L",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "eUVW3NvIA3K2JT4cS8Vt4idV",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 1,
            y: 3,
            level: 3,
            parentId: "R2uls2cGeedOezadmH92BHu8",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "H",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "R2uls2cGeedOezadmH92BHu8",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 1,
            y: 2,
            level: 2,
            parentId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "H",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "bz8QsifzNWuC68BcjQ9KSrq6",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 2,
            y: 3,
            level: 3,
            parentId: "aIEQEcZwCzYjLK2hHkvso7vB",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "M",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "aIEQEcZwCzYjLK2hHkvso7vB",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 2,
            y: 2,
            level: 2,
            parentId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "A",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 1.5,
            y: 1,
            level: 1,
            parentId: "ZaP524wLoByB2YUJZha99ELz",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Ghh",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "qiDTAMbKL2LqI7oPTlDISWUd",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 3,
            y: 3,
            level: 3,
            parentId: "8Gp9OHcp6orUxdHjSfpaVUAH",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "G",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "8Gp9OHcp6orUxdHjSfpaVUAH",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 3,
            y: 2,
            level: 2,
            parentId: "nFC97sH2HjHgdirs9DcHO4wb",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "C",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "nFC97sH2HjHgdirs9DcHO4wb",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 3,
            y: 1,
            level: 1,
            parentId: "ZaP524wLoByB2YUJZha99ELz",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Moneys",
                isCompleted: false,
                icon: { isEmoji: false, text: "M" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: true,
            category: "SKILL_TREE",
            nodeId: "ZaP524wLoByB2YUJZha99ELz",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 1,
            y: 0,
            level: 0,
            parentId: null,
        },
    ];

    expect(PlotTreeReingoldTiltfordAlgorithm(treeToTest)).toStrictEqual(result);
});

test("HierarchicalTree - Rairtha 4", () => {
    const treeToTest: Tree<Skill> = {
        treeName: "Moneys",
        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
        isRoot: true,
        parentId: null,
        treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
        level: 0,
        nodeId: "ZaP524wLoByB2YUJZha99ELz",
        category: "SKILL_TREE",
        children: [
            {
                accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                treeName: "Moneys",
                category: "SKILL",
                children: [
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                        treeName: "Moneys",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "B",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "5q0IMY79rAneVeAHSwRgm8AM",
                        parentId: "EaTStq4s6zIxltcjd0MTaLKS",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                        treeName: "Moneys",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "S",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "NRfw8131hOoU3VPgCoQJSBai",
                        parentId: "EaTStq4s6zIxltcjd0MTaLKS",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                        treeName: "Moneys",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "J",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "qsVTkuD9OZ9I5Xl7j3Oib1Ox",
                        parentId: "EaTStq4s6zIxltcjd0MTaLKS",
                        x: 0,
                        y: 0,
                    },
                ],
                data: {
                    name: "B",
                    isCompleted: false,
                    icon: { isEmoji: false, text: "" },
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    usefulResources: [],
                },
                isRoot: false,
                level: 1,
                nodeId: "EaTStq4s6zIxltcjd0MTaLKS",
                parentId: "ZaP524wLoByB2YUJZha99ELz",
                x: 0,
                y: 0,
            },
            {
                accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                treeName: "Moneys",
                category: "SKILL",
                children: [
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                        treeName: "Moneys",
                        category: "SKILL",
                        children: [
                            {
                                accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                                treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                                treeName: "Moneys",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "L",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "eUVW3NvIA3K2JT4cS8Vt4idV",
                                parentId: "R2uls2cGeedOezadmH92BHu8",
                                x: 0,
                                y: 0,
                            },
                            {
                                accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                                treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                                treeName: "Moneys",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "Gcgc g",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "tleqTACAMzNV5IWS6PuhKAQa",
                                parentId: "R2uls2cGeedOezadmH92BHu8",
                                x: 0,
                                y: 0,
                            },
                        ],
                        data: {
                            name: "H",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "R2uls2cGeedOezadmH92BHu8",
                        parentId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                        treeName: "Moneys",
                        category: "SKILL",
                        children: [
                            {
                                accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                                treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                                treeName: "Moneys",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "H",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "bz8QsifzNWuC68BcjQ9KSrq6",
                                parentId: "aIEQEcZwCzYjLK2hHkvso7vB",
                                x: 0,
                                y: 0,
                            },
                        ],
                        data: {
                            name: "M",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "aIEQEcZwCzYjLK2hHkvso7vB",
                        parentId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
                        x: 0,
                        y: 0,
                    },
                ],
                data: {
                    name: "A",
                    isCompleted: false,
                    icon: { isEmoji: false, text: "" },
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    usefulResources: [],
                },
                isRoot: false,
                level: 1,
                nodeId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
                parentId: "ZaP524wLoByB2YUJZha99ELz",
                x: 0,
                y: 0,
            },
            {
                accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                treeName: "Moneys",
                category: "SKILL",
                children: [
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                        treeName: "Moneys",
                        category: "SKILL",
                        children: [
                            {
                                accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                                treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
                                treeName: "Moneys",
                                category: "SKILL",
                                children: [],
                                data: {
                                    name: "Ghh",
                                    isCompleted: false,
                                    icon: { isEmoji: false, text: "" },
                                    logs: [],
                                    milestones: [],
                                    motivesToLearn: [],
                                    usefulResources: [],
                                },
                                isRoot: false,
                                level: 3,
                                nodeId: "qiDTAMbKL2LqI7oPTlDISWUd",
                                parentId: "8Gp9OHcp6orUxdHjSfpaVUAH",
                                x: 0,
                                y: 0,
                            },
                        ],
                        data: {
                            name: "G",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "8Gp9OHcp6orUxdHjSfpaVUAH",
                        parentId: "nFC97sH2HjHgdirs9DcHO4wb",
                        x: 0,
                        y: 0,
                    },
                ],
                data: {
                    name: "C",
                    isCompleted: false,
                    icon: { isEmoji: false, text: "" },
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    usefulResources: [],
                },
                isRoot: false,
                level: 1,
                nodeId: "nFC97sH2HjHgdirs9DcHO4wb",
                parentId: "ZaP524wLoByB2YUJZha99ELz",
                x: 0,
                y: 0,
            },
        ],
        x: 0,
        y: 0,
        data: {
            name: "Moneys",
            isCompleted: false,
            icon: { isEmoji: false, text: "M" },
            logs: [],
            milestones: [],
            motivesToLearn: [],
            usefulResources: [],
        },
    };

    const result = [
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "B",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "5q0IMY79rAneVeAHSwRgm8AM",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: -2,
            y: 2,
            level: 2,
            parentId: "EaTStq4s6zIxltcjd0MTaLKS",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "S",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "NRfw8131hOoU3VPgCoQJSBai",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: -1,
            y: 2,
            level: 2,
            parentId: "EaTStq4s6zIxltcjd0MTaLKS",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "J",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "qsVTkuD9OZ9I5Xl7j3Oib1Ox",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 0,
            y: 2,
            level: 2,
            parentId: "EaTStq4s6zIxltcjd0MTaLKS",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "B",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "EaTStq4s6zIxltcjd0MTaLKS",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: -1,
            y: 1,
            level: 1,
            parentId: "ZaP524wLoByB2YUJZha99ELz",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "L",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "eUVW3NvIA3K2JT4cS8Vt4idV",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 0.5,
            y: 3,
            level: 3,
            parentId: "R2uls2cGeedOezadmH92BHu8",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Gcgc g",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "tleqTACAMzNV5IWS6PuhKAQa",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 1.5,
            y: 3,
            level: 3,
            parentId: "R2uls2cGeedOezadmH92BHu8",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "H",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "R2uls2cGeedOezadmH92BHu8",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 1,
            y: 2,
            level: 2,
            parentId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "H",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "bz8QsifzNWuC68BcjQ9KSrq6",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 2.5,
            y: 3,
            level: 3,
            parentId: "aIEQEcZwCzYjLK2hHkvso7vB",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "M",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "aIEQEcZwCzYjLK2hHkvso7vB",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 2.5,
            y: 2,
            level: 2,
            parentId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "A",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 1.75,
            y: 1,
            level: 1,
            parentId: "ZaP524wLoByB2YUJZha99ELz",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Ghh",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "qiDTAMbKL2LqI7oPTlDISWUd",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 3.5,
            y: 3,
            level: 3,
            parentId: "8Gp9OHcp6orUxdHjSfpaVUAH",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "G",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "8Gp9OHcp6orUxdHjSfpaVUAH",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 3.5,
            y: 2,
            level: 2,
            parentId: "nFC97sH2HjHgdirs9DcHO4wb",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "C",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "nFC97sH2HjHgdirs9DcHO4wb",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 3.5,
            y: 1,
            level: 1,
            parentId: "ZaP524wLoByB2YUJZha99ELz",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Moneys",
                isCompleted: false,
                icon: { isEmoji: false, text: "M" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: true,
            category: "SKILL_TREE",
            nodeId: "ZaP524wLoByB2YUJZha99ELz",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            treeName: "Moneys",
            x: 1.375,
            y: 0,
            level: 0,
            parentId: null,
        },
    ];

    expect(PlotTreeReingoldTiltfordAlgorithm(treeToTest)).toStrictEqual(result);
});
