import { Dictionary } from "@reduxjs/toolkit";
import { NormalizedNode, getDefaultSkillValue } from "../../types";
import {
    getAllNodesFromLevel0ToLCALevelIncluded,
    getNodesInBetweenConflictingTrees,
    getTreesToShift,
    hierarchicalShiftNodes,
    treesToCenterAfterShift,
} from "./general";
import { countNodesPerLevel } from "../extractInformationFromTree";
import {
    getDistanceToCenterPerLevel,
    getNodesToShiftByOverlapRadial,
    getNodesToShiftForInternalOverlapRadial,
} from "../treeToRadialCoordinates/overlap";
import { firstIteration } from "../treeToRadialCoordinates/firstInstance";
import { radiusPerLevelToAvoidLevelOvercrowd } from "../treeToRadialCoordinates/levelOvercrowd";

const MOCK_SKILL_VALUE = getDefaultSkillValue("foo", false, { isEmoji: false, text: "foo" });

const overlapCaseWithNodesInBetweenConflictingTreesAndNodesRightOfConflictingTrees: Dictionary<NormalizedNode> = {
    "1": {
        category: "SKILL_TREE",
        childrenIds: ["a", "b", "c", "d"],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 1,
        nodeId: "1",
        parentId: "rootId",
        treeId: "treeId",
        x: 1,
        y: 0,
    },
    rootId: {
        category: "SKILL_TREE",
        childrenIds: ["1"],
        data: MOCK_SKILL_VALUE,
        isRoot: true,
        level: 0,
        nodeId: "rootId",
        parentId: null,
        treeId: "treeId",
        x: 0,
        y: 0,
    },
    a: {
        category: "SKILL_TREE",
        childrenIds: ["a1"],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 2,
        nodeId: "a",
        parentId: "1",
        treeId: "treeId",
        x: 1.7670133296324289,
        y: -0.9368371752344786,
    },
    a1: {
        category: "SKILL_TREE",
        childrenIds: ["a11", "a12", "a13", "a14", "a15"],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 3,
        nodeId: "a1",
        parentId: "a",
        treeId: "treeId",
        x: 2.6505199944486435,
        y: -1.405255762851718,
    },
    a11: {
        category: "SKILL_TREE",
        childrenIds: [],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 4,
        nodeId: "a11",
        parentId: "a1",
        treeId: "treeId",
        x: 2.7507422488820192,
        y: -2.9040346210428503,
    },
    a12: {
        category: "SKILL_TREE",
        childrenIds: [],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 4,
        nodeId: "a12",
        parentId: "a1",
        treeId: "treeId",
        x: 3.184335194196223,
        y: -2.4207456229441586,
    },
    a13: {
        category: "SKILL_TREE",
        childrenIds: [],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 4,
        nodeId: "a13",
        parentId: "a1",
        treeId: "treeId",
        x: 3.5340266592648577,
        y: -1.8736743504689573,
    },
    a14: {
        category: "SKILL_TREE",
        childrenIds: [],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 4,
        nodeId: "a14",
        parentId: "a1",
        treeId: "treeId",
        x: 3.790602905659263,
        y: -1.2772351434280038,
    },
    a15: {
        category: "SKILL_TREE",
        childrenIds: [],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 4,
        nodeId: "a15",
        parentId: "a1",
        treeId: "treeId",
        x: 3.9473036127613144,
        y: -0.6471430975305805,
    },
    b: {
        category: "SKILL_TREE",
        childrenIds: ["b1"],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 2,
        nodeId: "b",
        parentId: "1",
        treeId: "treeId",
        x: 1.9736518063806572,
        y: -0.32357154876529026,
    },
    b1: {
        category: "SKILL_TREE",
        childrenIds: [],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 3,
        nodeId: "b1",
        parentId: "b",
        treeId: "treeId",
        x: 2.960477709570986,
        y: -0.4853573231479354,
    },
    c: {
        category: "SKILL_TREE",
        childrenIds: ["c1"],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 2,
        nodeId: "c",
        parentId: "1",
        treeId: "treeId",
        x: 1.9736518063806572,
        y: 0.32357154876529015,
    },
    c1: {
        category: "SKILL_TREE",
        childrenIds: ["c11", "c12", "c13", "c14", "c15"],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 3,
        nodeId: "c1",
        parentId: "c",
        treeId: "treeId",
        x: 2.960477709570986,
        y: 0.4853573231479352,
    },
    c11: {
        category: "SKILL_TREE",
        childrenIds: [],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 4,
        nodeId: "c11",
        parentId: "c1",
        treeId: "treeId",
        x: 3.9473036127613144,
        y: -0.6471430975305805,
    },
    c12: {
        category: "SKILL_TREE",
        childrenIds: [],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 4,
        nodeId: "c12",
        parentId: "c1",
        treeId: "treeId",
        x: 4,
        y: -2.220446049250313e-16,
    },
    c13: {
        category: "SKILL_TREE",
        childrenIds: [],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 4,
        nodeId: "c13",
        parentId: "c1",
        treeId: "treeId",
        x: 3.9473036127613144,
        y: 0.6471430975305803,
    },
    c14: {
        category: "SKILL_TREE",
        childrenIds: [],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 4,
        nodeId: "c14",
        parentId: "c1",
        treeId: "treeId",
        x: 3.790602905659263,
        y: 1.2772351434280038,
    },
    c15: {
        category: "SKILL_TREE",
        childrenIds: [],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 4,
        nodeId: "c15",
        parentId: "c1",
        treeId: "treeId",
        x: 3.5340266592648577,
        y: 1.8736743504689573,
    },
    d: {
        category: "SKILL_TREE",
        childrenIds: ["d1"],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 2,
        nodeId: "d",
        parentId: "1",
        treeId: "treeId",
        x: 1.7670133296324289,
        y: 0.9368371752344786,
    },
    d1: {
        category: "SKILL_TREE",
        childrenIds: [],
        data: MOCK_SKILL_VALUE,
        isRoot: false,
        level: 3,
        nodeId: "d1",
        parentId: "d",
        treeId: "treeId",
        x: 2.6505199944486435,
        y: 1.405255762851718,
    },
};

console.log(
    JSON.stringify(
        getNodesToShiftForInternalOverlapRadial(overlapCaseWithNodesInBetweenConflictingTreesAndNodesRightOfConflictingTrees, "rootId", [
            "c11",
            "a15",
        ])
    )
);

// console.log(
//     JSON.stringify(
//         getNodesToShiftByOverlapRadial(overlapCaseWithNodesInBetweenConflictingTreesAndNodesRightOfConflictingTrees, "rootId", 1, [
//             "rootId",
//             "1",
//             "a",
//             "a1",
//             "a15",
//         ])
//     )
// );

// const tablita = radiusPerLevelToAvoidLevelOvercrowd(overlapCaseWithNodesInBetweenConflictingTreesAndNodesRightOfConflictingTrees);

// const foo = firstIteration(overlapCaseWithNodesInBetweenConflictingTreesAndNodesRightOfConflictingTrees, "rootId", tablita);

// const keys = Object.keys(foo);

// console.log(keys.map((nodeId) => `${nodeId} - (${foo[nodeId]!.x},${foo[nodeId]!.y})`));
// console.log(JSON.stringify(firstIteration(overlapCaseWithNodesInBetweenConflictingTreesAndNodesRightOfConflictingTrees, "rootId", tablita)));
