import { Dictionary } from "@reduxjs/toolkit";
import { NormalizedNode, getDefaultSkillValue } from "../../types";
import {
    getAllNodesFromLevel0ToLCALevelIncluded,
    getNodesInBetweenConflictingTrees,
    getTreesToShift,
    hierarchicalShiftNodes,
    treesToCenterAfterShift,
} from "./general";

const MOCK_SKILL_VALUE = getDefaultSkillValue("foo", false, { isEmoji: false, text: "foo" });

const nodes: Dictionary<NormalizedNode> = {
    "21a": {
        category: "SKILL",
        childrenIds: [],
        data: {
            name: "foo",
            isCompleted: false,
            icon: { isEmoji: false, text: "foo" },
            logs: [],
            milestones: [],
            motivesToLearn: [],
            usefulResources: [],
        },
        isRoot: false,
        level: 2,
        nodeId: "21a",
        parentId: "1-1",
        treeId: "treeId",
        x: -1,
        y: 2,
    },
    "21b": {
        category: "SKILL",
        childrenIds: [],
        data: {
            name: "foo",
            isCompleted: false,
            icon: { isEmoji: false, text: "foo" },
            logs: [],
            milestones: [],
            motivesToLearn: [],
            usefulResources: [],
        },
        isRoot: false,
        level: 2,
        nodeId: "21b",
        parentId: "1-1",
        treeId: "treeId",
        x: 0,
        y: 2,
    },
    "1-1": {
        category: "SKILL",
        childrenIds: ["21a", "21b"],
        data: {
            name: "foo",
            isCompleted: false,
            icon: { isEmoji: false, text: "foo" },
            logs: [],
            milestones: [],
            motivesToLearn: [],
            usefulResources: [],
        },
        isRoot: false,
        level: 1,
        nodeId: "1-1",
        parentId: "rootId",
        treeId: "treeId",
        x: -0.5,
        y: 1,
    },
    "22a": {
        category: "SKILL",
        childrenIds: [],
        data: {
            name: "foo",
            isCompleted: false,
            icon: { isEmoji: false, text: "foo" },
            logs: [],
            milestones: [],
            motivesToLearn: [],
            usefulResources: [],
        },
        isRoot: false,
        level: 2,
        nodeId: "22a",
        parentId: "1-2",
        treeId: "treeId",
        x: 0,
        y: 2,
    },
    "22b": {
        category: "SKILL",
        childrenIds: [],
        data: {
            name: "foo",
            isCompleted: false,
            icon: { isEmoji: false, text: "foo" },
            logs: [],
            milestones: [],
            motivesToLearn: [],
            usefulResources: [],
        },
        isRoot: false,
        level: 2,
        nodeId: "22b",
        parentId: "1-2",
        treeId: "treeId",
        x: 1,
        y: 2,
    },
    "1-2": {
        category: "SKILL",
        childrenIds: ["22a", "22b"],
        data: {
            name: "foo",
            isCompleted: false,
            icon: { isEmoji: false, text: "foo" },
            logs: [],
            milestones: [],
            motivesToLearn: [],
            usefulResources: [],
        },
        isRoot: false,
        level: 1,
        nodeId: "1-2",
        parentId: "rootId",
        treeId: "treeId",
        x: 0.5,
        y: 1,
    },
    rootId: {
        category: "SKILL_TREE",
        childrenIds: ["1-1", "1-2"],
        data: {
            name: "foo",
            isCompleted: false,
            icon: { isEmoji: false, text: "foo" },
            logs: [],
            milestones: [],
            motivesToLearn: [],
            usefulResources: [],
        },
        isRoot: true,
        level: 0,
        nodeId: "rootId",
        parentId: null,
        treeId: "treeId",
        x: 0,
        y: 0,
    },
};

const treesToShift = getTreesToShift(nodes, "rootId", ["21b", "22a"]);

console.log(treesToShift);

console.log(JSON.stringify(hierarchicalShiftNodes(nodes, treesToShift, 1)));
