import { NodeCoordinate, NormalizedNode, getDefaultSkillValue } from "../types";
import { test, expect } from "@jest/globals";
import { Dictionary } from "@reduxjs/toolkit";
import {
    completedSkillTreeTable,
    countNodesPerLevel,
    findLowestCommonAncestorIdOfNodes,
    getDescendantsId,
    getRadialTreeContourByLevel,
    getSubTreesOuterContour,
    returnPathFromRootToNode,
} from "./extractInformationFromTree";

const MOCK_SKILL_VALUE = getDefaultSkillValue("foo", false, { isEmoji: false, text: "foo" });

test("getSubTreesOuterContour", () => {
    const nodes: Dictionary<NormalizedNode> = {
        homepageRoot: {
            category: "USER",
            data: MOCK_SKILL_VALUE,
            isRoot: true,
            level: 0,
            nodeId: "homepageRoot",
            parentId: null,
            treeId: "HomepageTree",
            x: 0,
            y: 0,
            childrenIds: [
                "aQbWCZDIHv4j0hsGnvwq6Y1n",
                "ZaP524wLoByB2YUJZha99ELz",
                "YiXnGOGRi0AM7Qr6NCLpS0Bc",
                "xo1pn5U1LbbyB1WpQqlGzjSC",
                "xq1Ty3XkyYWLlBX8Aoqt6dCP",
            ],
        },
        xq1Ty3XkyYWLlBX8Aoqt6dCP: {
            category: "SKILL_TREE",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "xq1Ty3XkyYWLlBX8Aoqt6dCP",
            parentId: "homepageRoot",
            treeId: "fEot9gYSv0XHOQS6rjTsepnv",
            x: 0.26749882862458735,
            y: 0.963558185417193,
            childrenIds: [],
        },
        xo1pn5U1LbbyB1WpQqlGzjSC: {
            category: "SKILL_TREE",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "xo1pn5U1LbbyB1WpQqlGzjSC",
            parentId: "homepageRoot",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 0.8497906437294646,
            y: 0.5271203485257066,
            childrenIds: ["dMSm122QIC2ZnzKo6YL95lY1", "OO2ZEOy17klSkQeUjlNIEDyC", "c1nWxT1H0LdIJoIeqzpW9jTQ"],
        },
        dMSm122QIC2ZnzKo6YL95lY1: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "dMSm122QIC2ZnzKo6YL95lY1",
            parentId: "xo1pn5U1LbbyB1WpQqlGzjSC",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 1.9641656834119547,
            y: 0.3768994137788611,
            childrenIds: ["yz0AyyeijZ1XZzn8FIOnTKpx"],
        },
        yz0AyyeijZ1XZzn8FIOnTKpx: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "yz0AyyeijZ1XZzn8FIOnTKpx",
            parentId: "dMSm122QIC2ZnzKo6YL95lY1",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 2.946248525117932,
            y: 0.5653491206682917,
            childrenIds: [],
        },
        OO2ZEOy17klSkQeUjlNIEDyC: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "OO2ZEOy17klSkQeUjlNIEDyC",
            parentId: "xo1pn5U1LbbyB1WpQqlGzjSC",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 1.7409957424804483,
            y: 0.9843443628451136,
            childrenIds: ["ETPU6bW0Il8YWK8kgLCztT2y"],
        },
        ETPU6bW0Il8YWK8kgLCztT2y: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "ETPU6bW0Il8YWK8kgLCztT2y",
            parentId: "OO2ZEOy17klSkQeUjlNIEDyC",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 2.6114936137206723,
            y: 1.4765165442676704,
            childrenIds: ["p3edDleaHkS4ULZkHpdYJM8J", "7dAcdJzTOJ2TwT6ltjpJjH4D"],
        },
        p3edDleaHkS4ULZkHpdYJM8J: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "p3edDleaHkS4ULZkHpdYJM8J",
            parentId: "ETPU6bW0Il8YWK8kgLCztT2y",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 3.6302845380053843,
            y: 1.679593454714275,
            childrenIds: [],
        },
        "7dAcdJzTOJ2TwT6ltjpJjH4D": {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "7dAcdJzTOJ2TwT6ltjpJjH4D",
            parentId: "ETPU6bW0Il8YWK8kgLCztT2y",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 3.310724490336077,
            y: 2.244794723151523,
            childrenIds: [],
        },
        c1nWxT1H0LdIJoIeqzpW9jTQ: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "c1nWxT1H0LdIJoIeqzpW9jTQ",
            parentId: "xo1pn5U1LbbyB1WpQqlGzjSC",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 1.2103138953392945,
            y: 1.5922123836814683,
            childrenIds: ["C4pjCLvMIUdw39PsreMyrgb8", "PLqLY3zrO1rje2LdoypEuHtp"],
        },
        C4pjCLvMIUdw39PsreMyrgb8: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "C4pjCLvMIUdw39PsreMyrgb8",
            parentId: "c1nWxT1H0LdIJoIeqzpW9jTQ",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 2.1779496245813217,
            y: 2.0631372791906215,
            childrenIds: ["pGOJR7WrQty7JcW7PY49C7qM"],
        },
        pGOJR7WrQty7JcW7PY49C7qM: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "pGOJR7WrQty7JcW7PY49C7qM",
            parentId: "C4pjCLvMIUdw39PsreMyrgb8",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 2.9039328327750953,
            y: 2.750849705587495,
            childrenIds: [],
        },
        PLqLY3zrO1rje2LdoypEuHtp: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "PLqLY3zrO1rje2LdoypEuHtp",
            parentId: "c1nWxT1H0LdIJoIeqzpW9jTQ",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 1.4051576841546907,
            y: 2.650571991601252,
            childrenIds: ["iaYRS8Ay7HBCXmVpuYqXwzaC", "OAEoTmtL2CQfBKkGOLtoOpKu", "W4cebJSthJvkS687FcB6v4SE"],
        },
        iaYRS8Ay7HBCXmVpuYqXwzaC: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "iaYRS8Ay7HBCXmVpuYqXwzaC",
            parentId: "PLqLY3zrO1rje2LdoypEuHtp",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 2.420627790678589,
            y: 3.1844247673629367,
            childrenIds: [],
        },
        OAEoTmtL2CQfBKkGOLtoOpKu: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "OAEoTmtL2CQfBKkGOLtoOpKu",
            parentId: "PLqLY3zrO1rje2LdoypEuHtp",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 1.873543578872921,
            y: 3.534095988801669,
            childrenIds: [],
        },
        W4cebJSthJvkS687FcB6v4SE: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "W4cebJSthJvkS687FcB6v4SE",
            parentId: "PLqLY3zrO1rje2LdoypEuHtp",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 1.2770948780968334,
            y: 3.7906501648581123,
            childrenIds: [],
        },
        YiXnGOGRi0AM7Qr6NCLpS0Bc: {
            category: "SKILL_TREE",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
            parentId: "homepageRoot",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 0.8238624002599529,
            y: -0.5667898600344833,
            childrenIds: ["juEwrhtZAQ7ZMFm4Y44jG4Ru", "cquIn5zeC4f8fvLQKK2PV2mM", "6nHFVkOqhxQt1t0wJyPH6XVJ"],
        },
        juEwrhtZAQ7ZMFm4Y44jG4Ru: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "juEwrhtZAQ7ZMFm4Y44jG4Ru",
            parentId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 1.1223361117676058,
            y: -1.6554037731690636,
            childrenIds: [],
        },
        cquIn5zeC4f8fvLQKK2PV2mM: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "cquIn5zeC4f8fvLQKK2PV2mM",
            parentId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 1.5921676005118635,
            y: -1.210372806981508,
            childrenIds: ["ZcAeHwZQceTlX4D6I3DU9k1U"],
        },
        ZcAeHwZQceTlX4D6I3DU9k1U: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "ZcAeHwZQceTlX4D6I3DU9k1U",
            parentId: "cquIn5zeC4f8fvLQKK2PV2mM",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 2.3882514007677953,
            y: -1.8155592104722622,
            childrenIds: [],
        },
        "6nHFVkOqhxQt1t0wJyPH6XVJ": {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "6nHFVkOqhxQt1t0wJyPH6XVJ",
            parentId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 1.9472377553615254,
            y: -0.45636073899340673,
            childrenIds: ["o5ZUPWxtFKnBB30tuAw8Xd9w", "UydKvtvXuznmmprn39hDN7Uq"],
        },
        o5ZUPWxtFKnBB30tuAw8Xd9w: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "o5ZUPWxtFKnBB30tuAw8Xd9w",
            parentId: "6nHFVkOqhxQt1t0wJyPH6XVJ",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 2.722713394459948,
            y: -1.2596951105836638,
            childrenIds: ["QOEus1TQ0uHqbW2QYsHoPDGt", "zKJi6y5UdSrQOx4ySeX5djPm", "OeC54kCCSD4l9hhc1V7QkJUA"],
        },
        QOEus1TQ0uHqbW2QYsHoPDGt: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "QOEus1TQ0uHqbW2QYsHoPDGt",
            parentId: "o5ZUPWxtFKnBB30tuAw8Xd9w",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 3.3107244966673264,
            y: -2.244794713813911,
            childrenIds: [],
        },
        zKJi6y5UdSrQOx4ySeX5djPm: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "zKJi6y5UdSrQOx4ySeX5djPm",
            parentId: "o5ZUPWxtFKnBB30tuAw8Xd9w",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 3.630284525946597,
            y: -1.6795934807782182,
            childrenIds: [],
        },
        OeC54kCCSD4l9hhc1V7QkJUA: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "OeC54kCCSD4l9hhc1V7QkJUA",
            parentId: "o5ZUPWxtFKnBB30tuAw8Xd9w",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 3.8541931380908716,
            y: -1.0701379604019472,
            childrenIds: [],
        },
        UydKvtvXuznmmprn39hDN7Uq: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "UydKvtvXuznmmprn39hDN7Uq",
            parentId: "6nHFVkOqhxQt1t0wJyPH6XVJ",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 2.9988998065232737,
            y: -0.08124007899227619,
            childrenIds: ["h1XB4MHwb6UjRndE4yy5H9Fb", "yB7Y5ZFbcvzobGbvDQIBhLBC"],
        },
        h1XB4MHwb6UjRndE4yy5H9Fb: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "h1XB4MHwb6UjRndE4yy5H9Fb",
            parentId: "UydKvtvXuznmmprn39hDN7Uq",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 3.9765507231863846,
            y: -0.43248623784560036,
            childrenIds: [],
        },
        yB7Y5ZFbcvzobGbvDQIBhLBC: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "yB7Y5ZFbcvzobGbvDQIBhLBC",
            parentId: "UydKvtvXuznmmprn39hDN7Uq",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 3.9941333783354294,
            y: 0.21656074451943172,
            childrenIds: [],
        },
        ZaP524wLoByB2YUJZha99ELz: {
            category: "SKILL_TREE",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "ZaP524wLoByB2YUJZha99ELz",
            parentId: "homepageRoot",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -0.1818323057845775,
            y: -0.9833295544084211,
            childrenIds: ["nFC97sH2HjHgdirs9DcHO4wb", "oE5PvpfzuzLjD2o2VZ4OJEUN", "EaTStq4s6zIxltcjd0MTaLKS"],
        },
        nFC97sH2HjHgdirs9DcHO4wb: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "nFC97sH2HjHgdirs9DcHO4wb",
            parentId: "ZaP524wLoByB2YUJZha99ELz",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -1.1668731186702903,
            y: -1.624317433546987,
            childrenIds: ["8Gp9OHcp6orUxdHjSfpaVUAH"],
        },
        "8Gp9OHcp6orUxdHjSfpaVUAH": {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "8Gp9OHcp6orUxdHjSfpaVUAH",
            parentId: "nFC97sH2HjHgdirs9DcHO4wb",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -1.7503096780054355,
            y: -2.4364761503204804,
            childrenIds: ["qiDTAMbKL2LqI7oPTlDISWUd"],
        },
        qiDTAMbKL2LqI7oPTlDISWUd: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "qiDTAMbKL2LqI7oPTlDISWUd",
            parentId: "8Gp9OHcp6orUxdHjSfpaVUAH",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -2.3337462373405806,
            y: -3.248634867093974,
            childrenIds: [],
        },
        oE5PvpfzuzLjD2o2VZ4OJEUN: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
            parentId: "ZaP524wLoByB2YUJZha99ELz",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -0.5611862632786044,
            y: -1.9196536088334784,
            childrenIds: ["aIEQEcZwCzYjLK2hHkvso7vB", "R2uls2cGeedOezadmH92BHu8"],
        },
        aIEQEcZwCzYjLK2hHkvso7vB: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "aIEQEcZwCzYjLK2hHkvso7vB",
            parentId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -1.185603984145554,
            y: -2.755783589612615,
            childrenIds: ["bz8QsifzNWuC68BcjQ9KSrq6"],
        },
        bz8QsifzNWuC68BcjQ9KSrq6: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "bz8QsifzNWuC68BcjQ9KSrq6",
            parentId: "aIEQEcZwCzYjLK2hHkvso7vB",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -1.5808053121940717,
            y: -3.6743781194834866,
            childrenIds: [],
        },
        R2uls2cGeedOezadmH92BHu8: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "R2uls2cGeedOezadmH92BHu8",
            parentId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -0.48546689123439435,
            y: -2.9604597442821636,
            childrenIds: ["tleqTACAMzNV5IWS6PuhKAQa", "eUVW3NvIA3K2JT4cS8Vt4idV"],
        },
        tleqTACAMzNV5IWS6PuhKAQa: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "tleqTACAMzNV5IWS6PuhKAQa",
            parentId: "R2uls2cGeedOezadmH92BHu8",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -0.9655175205387024,
            y: -3.8817233180035897,
            childrenIds: [],
        },
        eUVW3NvIA3K2JT4cS8Vt4idV: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "eUVW3NvIA3K2JT4cS8Vt4idV",
            parentId: "R2uls2cGeedOezadmH92BHu8",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -0.32479008630931194,
            y: -3.9867921189642166,
            childrenIds: [],
        },
        EaTStq4s6zIxltcjd0MTaLKS: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "EaTStq4s6zIxltcjd0MTaLKS",
            parentId: "ZaP524wLoByB2YUJZha99ELz",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: 0.5349976626844392,
            y: -1.9271163693254714,
            childrenIds: ["qsVTkuD9OZ9I5Xl7j3Oib1Ox", "NRfw8131hOoU3VPgCoQJSBai", "5q0IMY79rAneVeAHSwRgm8AM"],
        },
        qsVTkuD9OZ9I5Xl7j3Oib1Ox: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "qsVTkuD9OZ9I5Xl7j3Oib1Ox",
            parentId: "EaTStq4s6zIxltcjd0MTaLKS",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: 0.16230968996873413,
            y: -2.9956060429472786,
            childrenIds: [],
        },
        NRfw8131hOoU3VPgCoQJSBai: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "NRfw8131hOoU3VPgCoQJSBai",
            parentId: "EaTStq4s6zIxltcjd0MTaLKS",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: 0.8024964940266588,
            y: -2.890674553988207,
            childrenIds: [],
        },
        "5q0IMY79rAneVeAHSwRgm8AM": {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "5q0IMY79rAneVeAHSwRgm8AM",
            parentId: "EaTStq4s6zIxltcjd0MTaLKS",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: 1.4051576651246802,
            y: -2.6505720016897025,
            childrenIds: [],
        },
        aQbWCZDIHv4j0hsGnvwq6Y1n: {
            category: "SKILL_TREE",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "aQbWCZDIHv4j0hsGnvwq6Y1n",
            parentId: "homepageRoot",
            treeId: "CXCHHuWKSVVIhTn2wOKjr94x",
            x: -0.7398514313743738,
            y: -0.6727702873145411,
            childrenIds: [],
        },
    };
    expect(getSubTreesOuterContour(nodes, "homepageRoot")).toStrictEqual([
        {
            levelContours: {
                "0": {
                    leftNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                    rightNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                },
                "1": {
                    leftNode: { angleInRadians: 3.87953948, distanceToCenter: 1, id: "aQbWCZDIHv4j0hsGnvwq6Y1n" },
                    rightNode: { angleInRadians: 3.87953948, distanceToCenter: 1, id: "aQbWCZDIHv4j0hsGnvwq6Y1n" },
                },
            },
            maxLevel: 1,
        },
        {
            levelContours: {
                "0": {
                    leftNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                    rightNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                },
                "1": {
                    leftNode: { angleInRadians: 4.52953948, distanceToCenter: 1, id: "ZaP524wLoByB2YUJZha99ELz" },
                    rightNode: { angleInRadians: 4.52953948, distanceToCenter: 1, id: "ZaP524wLoByB2YUJZha99ELz" },
                },
                "2": {
                    leftNode: { angleInRadians: 4.98318531, distanceToCenter: 2, id: "EaTStq4s6zIxltcjd0MTaLKS" },
                    rightNode: { angleInRadians: 4.0894353, distanceToCenter: 2, id: "nFC97sH2HjHgdirs9DcHO4wb" },
                },
                "3": {
                    leftNode: { angleInRadians: 5.19985197, distanceToCenter: 3, id: "5q0IMY79rAneVeAHSwRgm8AM" },
                    rightNode: { angleInRadians: 4.0894353, distanceToCenter: 3, id: "8Gp9OHcp6orUxdHjSfpaVUAH" },
                },
                "4": {
                    leftNode: { angleInRadians: 4.63110197, distanceToCenter: 4, id: "eUVW3NvIA3K2JT4cS8Vt4idV" },
                    rightNode: { angleInRadians: 4.0894353, distanceToCenter: 4, id: "qiDTAMbKL2LqI7oPTlDISWUd" },
                },
            },
            maxLevel: 4,
        },
        {
            levelContours: {
                "0": {
                    leftNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                    rightNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                },
                "1": {
                    leftNode: { angleInRadians: 5.68058115, distanceToCenter: 1, id: "YiXnGOGRi0AM7Qr6NCLpS0Bc" },
                    rightNode: { angleInRadians: 5.68058115, distanceToCenter: 1, id: "YiXnGOGRi0AM7Qr6NCLpS0Bc" },
                },
                "2": {
                    leftNode: { angleInRadians: 6.05297697, distanceToCenter: 2, id: "6nHFVkOqhxQt1t0wJyPH6XVJ" },
                    rightNode: { angleInRadians: 5.30818531, distanceToCenter: 2, id: "juEwrhtZAQ7ZMFm4Y44jG4Ru" },
                },
                "3": {
                    leftNode: { angleInRadians: 6.25610197, distanceToCenter: 3, id: "UydKvtvXuznmmprn39hDN7Uq" },
                    rightNode: { angleInRadians: 5.63318531, distanceToCenter: 3, id: "ZcAeHwZQceTlX4D6I3DU9k1U" },
                },
                "4": {
                    leftNode: { angleInRadians: 0.05416667, distanceToCenter: 4, id: "yB7Y5ZFbcvzobGbvDQIBhLBC" },
                    rightNode: { angleInRadians: 5.68735198, distanceToCenter: 4, id: "QOEus1TQ0uHqbW2QYsHoPDGt" },
                },
            },
            maxLevel: 4,
        },
        {
            levelContours: {
                "0": {
                    leftNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                    rightNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                },
                "1": {
                    leftNode: { angleInRadians: 0.55520833, distanceToCenter: 1, id: "xo1pn5U1LbbyB1WpQqlGzjSC" },
                    rightNode: { angleInRadians: 0.55520833, distanceToCenter: 1, id: "xo1pn5U1LbbyB1WpQqlGzjSC" },
                },
                "2": {
                    leftNode: { angleInRadians: 0.92083333, distanceToCenter: 2, id: "c1nWxT1H0LdIJoIeqzpW9jTQ" },
                    rightNode: { angleInRadians: 0.18958333, distanceToCenter: 2, id: "dMSm122QIC2ZnzKo6YL95lY1" },
                },
                "3": {
                    leftNode: { angleInRadians: 1.08333333, distanceToCenter: 3, id: "PLqLY3zrO1rje2LdoypEuHtp" },
                    rightNode: { angleInRadians: 0.18958333, distanceToCenter: 3, id: "yz0AyyeijZ1XZzn8FIOnTKpx" },
                },
                "4": {
                    leftNode: { angleInRadians: 1.24583333, distanceToCenter: 4, id: "W4cebJSthJvkS687FcB6v4SE" },
                    rightNode: { angleInRadians: 0.43333333, distanceToCenter: 4, id: "p3edDleaHkS4ULZkHpdYJM8J" },
                },
            },
            maxLevel: 4,
        },
        {
            levelContours: {
                "0": {
                    leftNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                    rightNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                },
                "1": {
                    leftNode: { angleInRadians: 1.3, distanceToCenter: 1, id: "xq1Ty3XkyYWLlBX8Aoqt6dCP" },
                    rightNode: { angleInRadians: 1.3, distanceToCenter: 1, id: "xq1Ty3XkyYWLlBX8Aoqt6dCP" },
                },
            },
            maxLevel: 1,
        },
    ]);
});

test("returnPathFromRootToNode - Smallest overlap case", () => {
    const nodes: Dictionary<NormalizedNode> = {
        "21a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21a",
            parentId: "1-1",
            treeId: "treeId",
            x: -1,
            y: 2,
        },
        "21b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21b",
            parentId: "1-1",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "1-1": {
            category: "SKILL",
            childrenIds: ["21a", "21b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "treeId",
            x: -0.5,
            y: 1,
        },
        "22a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22a",
            parentId: "1-2",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "22b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22b",
            parentId: "1-2",
            treeId: "treeId",
            x: 1,
            y: 2,
        },
        "1-2": {
            category: "SKILL",
            childrenIds: ["22a", "22b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.5,
            y: 1,
        },
        rootId: {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2"],
            data: MOCK_SKILL_VALUE,
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "treeId",
            x: 0,
            y: 0,
        },
    };

    expect(returnPathFromRootToNode(nodes, "rootId", "21b")).toStrictEqual(["rootId", "1-1", "21b"]);
});

test("findLowestCommonAncestorIdOfNodes - Smallest overlap case", () => {
    const nodes: Dictionary<NormalizedNode> = {
        "21a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21a",
            parentId: "1-1",
            treeId: "treeId",
            x: -1,
            y: 2,
        },
        "21b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21b",
            parentId: "1-1",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "1-1": {
            category: "SKILL",
            childrenIds: ["21a", "21b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "treeId",
            x: -0.5,
            y: 1,
        },
        "22a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22a",
            parentId: "1-2",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "22b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22b",
            parentId: "1-2",
            treeId: "treeId",
            x: 1,
            y: 2,
        },
        "1-2": {
            category: "SKILL",
            childrenIds: ["22a", "22b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.5,
            y: 1,
        },
        rootId: {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2"],
            data: MOCK_SKILL_VALUE,
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "treeId",
            x: 0,
            y: 0,
        },
    };

    expect(findLowestCommonAncestorIdOfNodes(nodes, "rootId", "21a", "22b")).toStrictEqual("rootId");
});

test("getDescendantsId - Smallest overlap case", () => {
    const nodes: Dictionary<NormalizedNode> = {
        "21a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21a",
            parentId: "1-1",
            treeId: "treeId",
            x: -1,
            y: 2,
        },
        "21b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21b",
            parentId: "1-1",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "1-1": {
            category: "SKILL",
            childrenIds: ["21a", "21b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "treeId",
            x: -0.5,
            y: 1,
        },
        "22a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22a",
            parentId: "1-2",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "22b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22b",
            parentId: "1-2",
            treeId: "treeId",
            x: 1,
            y: 2,
        },
        "1-2": {
            category: "SKILL",
            childrenIds: ["22a", "22b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.5,
            y: 1,
        },
        rootId: {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2"],
            data: MOCK_SKILL_VALUE,
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "treeId",
            x: 0,
            y: 0,
        },
    };

    expect(getDescendantsId(nodes, "rootId")).toStrictEqual(["1-1", "21a", "21b", "1-2", "22a", "22b"]);
});

test("countNodesPerLevel", () => {
    const nodes: Dictionary<NormalizedNode> = {
        "21a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21a",
            parentId: "1-1",
            treeId: "treeId",
            x: -1,
            y: 2,
        },
        "21b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21b",
            parentId: "1-1",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "1-1": {
            category: "SKILL",
            childrenIds: ["21a", "21b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "treeId",
            x: -0.5,
            y: 1,
        },
        "22a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22a",
            parentId: "1-2",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "22b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22b",
            parentId: "1-2",
            treeId: "treeId",
            x: 1,
            y: 2,
        },
        "1-2": {
            category: "SKILL",
            childrenIds: ["22a", "22b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.5,
            y: 1,
        },
        rootId: {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2"],
            data: MOCK_SKILL_VALUE,
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "treeId",
            x: 0,
            y: 0,
        },
    };

    expect(countNodesPerLevel(nodes)).toStrictEqual({ "0": 1, "1": 2, "2": 4 });
});

test("getRadialTreeContourByLevel - Smallest overlap case", () => {
    const nodes: Dictionary<NormalizedNode> = {
        "21a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21a",
            parentId: "1-1",
            treeId: "treeId",
            x: -1,
            y: 2,
        },
        "21b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21b",
            parentId: "1-1",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "1-1": {
            category: "SKILL",
            childrenIds: ["21a", "21b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "treeId",
            x: -0.5,
            y: 1,
        },
        "22a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22a",
            parentId: "1-2",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "22b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22b",
            parentId: "1-2",
            treeId: "treeId",
            x: 1,
            y: 2,
        },
        "1-2": {
            category: "SKILL",
            childrenIds: ["22a", "22b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.5,
            y: 1,
        },
        rootId: {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2"],
            data: MOCK_SKILL_VALUE,
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "treeId",
            x: 0,
            y: 0,
        },
    };

    expect(getRadialTreeContourByLevel(nodes, "rootId")).toStrictEqual({
        contourByLevel: {
            "0": [
                {
                    leftNode: { angleInRadians: 0, distanceToCenter: 0, id: "rootId" },
                    rightNode: { angleInRadians: 0, distanceToCenter: 0, id: "rootId" },
                },
            ],
            "1": [
                {
                    leftNode: { angleInRadians: 1.10714872, distanceToCenter: 1.11803399, id: "1-2" },
                    rightNode: { angleInRadians: 2.03444394, distanceToCenter: 1.11803399, id: "1-1" },
                },
            ],
            "2": [
                {
                    leftNode: { angleInRadians: 1.10714872, distanceToCenter: 2.23606798, id: "22b" },
                    rightNode: { angleInRadians: 1.57079633, distanceToCenter: 2, id: "22a" },
                },
                {
                    leftNode: { angleInRadians: 1.57079633, distanceToCenter: 2, id: "21b" },
                    rightNode: { angleInRadians: 2.03444394, distanceToCenter: 2.23606798, id: "21a" },
                },
            ],
        },
        treeLevels: ["0", "1", "2"],
    });
});

test("completedSkillTreeTable", () => {
    const input: NodeCoordinate[] = [
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "USER",
            data: MOCK_SKILL_VALUE,
            isRoot: true,
            level: 0,
            nodeId: "homepageRoot",
            parentId: null,
            treeId: "HomepageTree",
            treeName: "Life Skills",
            x: 863.9274752338633,
            y: 794.5188174948537,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL_TREE",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "W13aNiwFA4QxLvB97rlfoiVh",
            parentId: "homepageRoot",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 908.3409249975296,
            y: 905.9972704805778,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "i2fZegyq8CRtKt94ExYsEx5N",
            parentId: "W13aNiwFA4QxLvB97rlfoiVh",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 1019.2964500402924,
            y: 977.4408819583821,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "Au0U4Y8urnDmRuepchXYk094",
            parentId: "i2fZegyq8CRtKt94ExYsEx5N",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 1096.980937443507,
            y: 1068.9019141901463,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "ZCENSQWBQ4IlyIm8LRBkhuNh",
            parentId: "W13aNiwFA4QxLvB97rlfoiVh",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 952.7543747611957,
            y: 1017.4757234663019,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "nKej63wQ9qAvUQ1BrdtHlLWr",
            parentId: "ZCENSQWBQ4IlyIm8LRBkhuNh",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 997.1678245248618,
            y: 1128.954176452026,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "rPvjkLO0YcEsfXFjuY2lfVuE",
            parentId: "nKej63wQ9qAvUQ1BrdtHlLWr",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 1184.4585336374093,
            y: 1151.8139904243274,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 5,
            nodeId: "G4jvapIbLJ1XryIcOIZHLZqm",
            parentId: "rPvjkLO0YcEsfXFjuY2lfVuE",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 1264.5912982382958,
            y: 1241.1377836566958,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "lSQ7xNHSDDbgWpK23at9bRqt",
            parentId: "nKej63wQ9qAvUQ1BrdtHlLWr",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 1122.4305502079187,
            y: 1198.9643147240329,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 5,
            nodeId: "rgxVIfKlLyOaNJkIMe2BVhKw",
            parentId: "lSQ7xNHSDDbgWpK23at9bRqt",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 1187.0563189514323,
            y: 1300.0756890313278,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 6,
            nodeId: "oyaQT0SBpSUbk7LwHFPVT4iL",
            parentId: "rgxVIfKlLyOaNJkIMe2BVhKw",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 1373.0349406684604,
            y: 1303.6451167947039,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 6,
            nodeId: "ggvyhGS8IWQrm9Kuyq7OtPHm",
            parentId: "rgxVIfKlLyOaNJkIMe2BVhKw",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 1315.0028591713558,
            y: 1355.7059502818088,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 6,
            nodeId: "lhkur9LTY0mVVeTmdkWlV7ZZ",
            parentId: "rgxVIfKlLyOaNJkIMe2BVhKw",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 1251.6820876949462,
            y: 1401.1870633386225,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 6,
            nodeId: "zo6kJdlnavamUPjftOQVN3CJ",
            parentId: "rgxVIfKlLyOaNJkIMe2BVhKw",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 1183.8150341988617,
            y: 1439.5552115218998,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 6,
            nodeId: "V4rQE2lYJw5OoUtiyCGyLoFS",
            parentId: "rgxVIfKlLyOaNJkIMe2BVhKw",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 1112.197408481296,
            y: 1470.3605447101206,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "v9A1jFspm3yP3AFhKPl8ijEA",
            parentId: "nKej63wQ9qAvUQ1BrdtHlLWr",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 1004.8045530887496,
            y: 1253.3800698741195,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 5,
            nodeId: "vqd6O7DFgDxKEurzozCCpXIG",
            parentId: "v9A1jFspm3yP3AFhKPl8ijEA",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 1040.023822552471,
            y: 1368.095382968936,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "qhfD2AscZy948FGL3QmPcOfd",
            parentId: "nKej63wQ9qAvUQ1BrdtHlLWr",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 876.9081293940512,
            y: 1274.3432672862057,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 5,
            nodeId: "zbzYhWqMjt2kHGJpBUfQzEyP",
            parentId: "qhfD2AscZy948FGL3QmPcOfd",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 880.1532929340982,
            y: 1394.2993797340437,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 6,
            nodeId: "duhNA0Tf6yZ1200ueoPLzuGg",
            parentId: "zbzYhWqMjt2kHGJpBUfQzEyP",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 1037.6689144049335,
            y: 1493.2418758769036,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 6,
            nodeId: "2VzB7kY3w7PPJZ9iydLdlhps",
            parentId: "zbzYhWqMjt2kHGJpBUfQzEyP",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 961.1033579136309,
            y: 1507.9309338942096,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 6,
            nodeId: "5gJHlxnfQWu7OQ7bEk5j0Dhr",
            parentId: "zbzYhWqMjt2kHGJpBUfQzEyP",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 883.3984564741452,
            y: 1514.2554921818817,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 6,
            nodeId: "ceqbtn7yLTTYOdWid6T6U70E",
            parentId: "zbzYhWqMjt2kHGJpBUfQzEyP",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 805.4652648504209,
            y: 1512.1413993281471,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 6,
            nodeId: "jF4COVBcLVYy9gS2fZPttOjJ",
            parentId: "zbzYhWqMjt2kHGJpBUfQzEyP",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 728.2175143421942,
            y: 1501.6134409468932,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "1ybjLeOiImEuSHzXEXgjsYe5",
            parentId: "W13aNiwFA4QxLvB97rlfoiVh",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 850.9249628273986,
            y: 1034.1663392244134,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "7UOehiZ7ODgv6JrWpSyueEIU",
            parentId: "1ybjLeOiImEuSHzXEXgjsYe5",
            treeId: "jzX4cM1gvWUfzdTVg7UACfLN",
            treeName: "Life Skills",
            x: 844.4237066241662,
            y: 1153.990100089193,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL_TREE",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "OuqUijIwgnIsfhHebtyq9aqH",
            parentId: "homepageRoot",
            treeId: "CaUf2JKOuTWj0SDktGn91Vii",
            treeName: "Life Skills",
            x: 966.7495473078349,
            y: 856.38659177529,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL_TREE",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "FD8FJKmpRY6RHDEZcZo6GaIY",
            parentId: "homepageRoot",
            treeId: "TLIq7eKs24qBnUiSQ9KsBi6r",
            treeName: "Life Skills",
            x: 983.2239969294549,
            y: 781.5442303594857,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "OWjYbBU4wkHkO9lWC71sJAUc",
            parentId: "FD8FJKmpRY6RHDEZcZo6GaIY",
            treeId: "TLIq7eKs24qBnUiSQ9KsBi6r",
            treeName: "Life Skills",
            x: 1102.5205186250464,
            y: 768.5696432241177,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL_TREE",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "ko0wTZHBoGVVvVfJUUJ0mwtU",
            parentId: "homepageRoot",
            treeId: "hgXfsFIBbDXjOMoT8Fs4qqJg",
            treeName: "Life Skills",
            x: 939.7382618358388,
            y: 701.4987947320649,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "NfRQpb0B2dRnIoOllYnSAviJ",
            parentId: "ko0wTZHBoGVVvVfJUUJ0mwtU",
            treeId: "hgXfsFIBbDXjOMoT8Fs4qqJg",
            treeName: "Life Skills",
            x: 921.8412842896289,
            y: 561.6111303725684,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "zKwWCEYqPDedLnCMwHrXvoV9",
            parentId: "NfRQpb0B2dRnIoOllYnSAviJ",
            treeId: "hgXfsFIBbDXjOMoT8Fs4qqJg",
            treeName: "Life Skills",
            x: 950.7981888175118,
            y: 445.1572868114258,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "HCeUiJunRYtk55Zy0dKlB3rL",
            parentId: "zKwWCEYqPDedLnCMwHrXvoV9",
            treeId: "hgXfsFIBbDXjOMoT8Fs4qqJg",
            treeName: "Life Skills",
            x: 979.7550933453946,
            y: 328.70344325028316,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "2TACt6HallMD1xEJZBAoEand",
            parentId: "ko0wTZHBoGVVvVfJUUJ0mwtU",
            treeId: "hgXfsFIBbDXjOMoT8Fs4qqJg",
            treeName: "Life Skills",
            x: 995.9055086246809,
            y: 594.0648359871465,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "Q1HQQ0hqk7d1Uuo81EGMbEly",
            parentId: "2TACt6HallMD1xEJZBAoEand",
            treeId: "hgXfsFIBbDXjOMoT8Fs4qqJg",
            treeName: "Life Skills",
            x: 1023.8712491756332,
            y: 472.0006177335627,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "ONtpTSzmbGfUQ34UcPG9AhN0",
            parentId: "Q1HQQ0hqk7d1Uuo81EGMbEly",
            treeId: "hgXfsFIBbDXjOMoT8Fs4qqJg",
            treeName: "Life Skills",
            x: 1077.1858404895565,
            y: 364.4945511464657,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "Hfzr9ntRDqjtLyfshwRMs3Ec",
            parentId: "2TACt6HallMD1xEJZBAoEand",
            treeId: "hgXfsFIBbDXjOMoT8Fs4qqJg",
            treeName: "Life Skills",
            x: 1096.9809327297187,
            y: 520.135716795799,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "ONiroGQ3VSo7TdiPOLDGTHxn",
            parentId: "Hfzr9ntRDqjtLyfshwRMs3Ec",
            treeId: "hgXfsFIBbDXjOMoT8Fs4qqJg",
            treeName: "Life Skills",
            x: 1143.9481630747084,
            y: 404.6619022283165,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "eLqGgDzBzHiTS3ox5VCg5R9n",
            parentId: "Hfzr9ntRDqjtLyfshwRMs3Ec",
            treeId: "hgXfsFIBbDXjOMoT8Fs4qqJg",
            treeName: "Life Skills",
            x: 1203.3324463592085,
            y: 455.10127879744994,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "VqrsN1O3m5Pb4SWVMs74CEGg",
            parentId: "ko0wTZHBoGVVvVfJUUJ0mwtU",
            treeId: "hgXfsFIBbDXjOMoT8Fs4qqJg",
            treeName: "Life Skills",
            x: 1081.7445467906591,
            y: 693.7432086481606,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "fbFatnhWdKgJe3AydMbHbhfv",
            parentId: "VqrsN1O3m5Pb4SWVMs74CEGg",
            treeId: "hgXfsFIBbDXjOMoT8Fs4qqJg",
            treeName: "Life Skills",
            x: 1150.5176411473276,
            y: 576.6517093722806,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "0i3SP1yMOtj9xKoCQFcmoOTi",
            parentId: "VqrsN1O3m5Pb4SWVMs74CEGg",
            treeId: "hgXfsFIBbDXjOMoT8Fs4qqJg",
            treeName: "Life Skills",
            x: 1190.653082569057,
            y: 643.355404224814,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "HOI7xk9mqBw2SXcnH1CVrtf5",
            parentId: "VqrsN1O3m5Pb4SWVMs74CEGg",
            treeId: "hgXfsFIBbDXjOMoT8Fs4qqJg",
            treeName: "Life Skills",
            x: 1215.5104794489255,
            y: 717.1276607189558,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL_TREE",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "3LkOwamlTSC6vOtNgDkeVtZv",
            parentId: "homepageRoot",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 769.9876761118046,
            y: 719.850791266037,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "6XwtKTfa6oP9h95goo7gdnYl",
            parentId: "3LkOwamlTSC6vOtNgDkeVtZv",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 635.0740526126884,
            y: 722.2269717958129,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "DzgtW4MkkjaIlo6t3YNBZn6o",
            parentId: "6XwtKTfa6oP9h95goo7gdnYl",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 532.4728573252726,
            y: 935.0102274353554,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "5DuTemiKCYv0ZBPva3c3ZvNc",
            parentId: "DzgtW4MkkjaIlo6t3YNBZn6o",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 458.1161537233079,
            y: 1050.8724235429383,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 5,
            nodeId: "bxp4HlZTT1iTXAIf1D96SgjL",
            parentId: "5DuTemiKCYv0ZBPva3c3ZvNc",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 356.66332334566897,
            y: 1114.9608250549595,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "Iw5TWV1RhiEQkr2sqvaIehGr",
            parentId: "DzgtW4MkkjaIlo6t3YNBZn6o",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 421.98798468907563,
            y: 981.8406974155226,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "i4VfsH1xgyizW0Cztnq1NMlW",
            parentId: "DzgtW4MkkjaIlo6t3YNBZn6o",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 397.50412291975124,
            y: 907.873378126818,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "RmLlaPuX6vjY9l96Y9RpoStL",
            parentId: "6XwtKTfa6oP9h95goo7gdnYl",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 508.9863894779611,
            y: 734.3787672585823,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "9Zh12pi0Nu0dHuVzpPg8JfSq",
            parentId: "RmLlaPuX6vjY9l96Y9RpoStL",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 385.309673945782,
            y: 830.9193709269467,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "2yI6CbMhyognYEBieQAHeu15",
            parentId: "RmLlaPuX6vjY9l96Y9RpoStL",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 385.72593946981516,
            y: 753.0062748973958,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "6eo2P6mf2xFih5Flee7aZXpf",
            parentId: "RmLlaPuX6vjY9l96Y9RpoStL",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 398.74195164722653,
            y: 676.1869593778335,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "lpbDvDoCoIxPB1itSvkw2ysa",
            parentId: "RmLlaPuX6vjY9l96Y9RpoStL",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 424.01476206901395,
            y: 602.4854745672751,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "jPMc23kmqTG38HwJd9s8rfBt",
            parentId: "6XwtKTfa6oP9h95goo7gdnYl",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 561.6407271831251,
            y: 599.0124954668703,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "lBKcIGyYIirv5kZrFUlBAD0O",
            parentId: "jPMc23kmqTG38HwJd9s8rfBt",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 460.8784778328791,
            y: 533.8437214575424,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 5,
            nodeId: "b2mEWsH9H8RmLojdy9AG87oT",
            parentId: "lBKcIGyYIirv5kZrFUlBAD0O",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 320.7385815990441,
            y: 539.6741082466901,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 6,
            nodeId: "g0wIzhtH4Nfk634vCXSPHT50",
            parentId: "b2mEWsH9H8RmLojdy9AG87oT",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 196.4999999999999,
            y: 524.4437070108431,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 6,
            nodeId: "mAvDUV8XSlCtgITy52Ib4h7d",
            parentId: "b2mEWsH9H8RmLojdy9AG87oT",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 229.61361598297196,
            y: 453.8636722786976,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 5,
            nodeId: "CYjqp96p8dgkmmfA5OArGBkd",
            parentId: "lBKcIGyYIirv5kZrFUlBAD0O",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 408.7184951374198,
            y: 403.641874660468,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 6,
            nodeId: "vDiV8mK2LRZhYmghiVr6Nb4R",
            parentId: "CYjqp96p8dgkmmfA5OArGBkd",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 270.16432891654154,
            y: 387.27770209102476,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 6,
            nodeId: "6V3rmv7hslIiURAhDvJVHqys",
            parentId: "CYjqp96p8dgkmmfA5OArGBkd",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 317.67669911813107,
            y: 325.46648609359085,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 6,
            nodeId: "qyh4ejHHHx23mABDJBejIgIe",
            parentId: "CYjqp96p8dgkmmfA5OArGBkd",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 371.5936613010415,
            y: 269.15473834748616,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "7cbHjf7OnQYjAClC4YyjAq4m",
            parentId: "6XwtKTfa6oP9h95goo7gdnYl",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 695.2850099118857,
            y: 476.46266067639874,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "IKS53b7vPGNwtVfhoI2oBIuf",
            parentId: "7cbHjf7OnQYjAClC4YyjAq4m",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 543.3699704448522,
            y: 437.2473714997348,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 5,
            nodeId: "SchpcwqjQ5rK4KYh0c5ZZOlz",
            parentId: "IKS53b7vPGNwtVfhoI2oBIuf",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 463.23059424759947,
            y: 347.92951000095513,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "dDOJnwqqbBXzywniCJL1ryBC",
            parentId: "7cbHjf7OnQYjAClC4YyjAq4m",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 605.394463601137,
            y: 390.0924559701473,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "jo2B3Kb9laPfavNFRbP9n238",
            parentId: "7cbHjf7OnQYjAClC4YyjAq4m",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 674.2308346049128,
            y: 353.59344451877877,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "82NW8QDWw5yRvs4EIc8LRa09",
            parentId: "7cbHjf7OnQYjAClC4YyjAq4m",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 748.0653694249188,
            y: 328.712020166265,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "Pdaefv6RnNvoq92kgcGPLIBy",
            parentId: "3LkOwamlTSC6vOtNgDkeVtZv",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 844.4400683378934,
            y: 555.3112904969122,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "kV0vlhkVCBfpZ9eXgSEz5jNa",
            parentId: "Pdaefv6RnNvoq92kgcGPLIBy",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 834.6963648899085,
            y: 435.7075269979415,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "eCNGcGjLEopgNGyxBfDk3EjC",
            parentId: "kV0vlhkVCBfpZ9eXgSEz5jNa",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 824.9526614419235,
            y: 316.10376349897075,
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 5,
            nodeId: "4fIm7RGnEjGCisFpEpOy0mae",
            parentId: "eCNGcGjLEopgNGyxBfDk3EjC",
            treeId: "qFRwpHaQ3QHaxKSNsw4Yd8ER",
            treeName: "Life Skills",
            x: 815.2089579939386,
            y: 196.5,
        },
    ];

    const output = {
        CaUf2JKOuTWj0SDktGn91Vii: { completedQty: 0, percentage: 0, qty: 0 },
        HomepageTree: { completedQty: 0, percentage: 0, qty: 0 },
        TLIq7eKs24qBnUiSQ9KsBi6r: { completedQty: 1, percentage: 100, qty: 1 },
        hgXfsFIBbDXjOMoT8Fs4qqJg: { completedQty: 0, percentage: 0, qty: 13 },
        jzX4cM1gvWUfzdTVg7UACfLN: { completedQty: 2, percentage: 8.333333333333332, qty: 24 },
        qFRwpHaQ3QHaxKSNsw4Yd8ER: { completedQty: 0, percentage: 0, qty: 30 },
    };

    expect(completedSkillTreeTable(input)).toStrictEqual(output);
});
