import { NormalizedNode } from "@/types";
import { test, expect } from "@jest/globals";
import { Dictionary } from "@reduxjs/toolkit";
import { countNodesPerLevel, findLowestCommonAncestorIdOfNodes, getDescendantsId, returnPathFromRootToNode } from "./extractInformationFromTree";

test("returnPathFromRootToNode - Smallest overlap case", () => {
    const nodes: Dictionary<NormalizedNode> = {
        "21a": {
            category: "SKILL",
            childrenIds: [],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 2,
            nodeId: "21a",
            parentId: "1-1",
            treeId: "treeId",
            x: -1,
            y: 2,
        },
        "21b": {
            category: "SKILL",
            childrenIds: [],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 2,
            nodeId: "21b",
            parentId: "1-1",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "1-1": {
            category: "SKILL",
            childrenIds: ["21a", "21b"],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "treeId",
            x: -0.5,
            y: 1,
        },
        "22a": {
            category: "SKILL",
            childrenIds: [],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 2,
            nodeId: "22a",
            parentId: "1-2",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "22b": {
            category: "SKILL",
            childrenIds: [],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 2,
            nodeId: "22b",
            parentId: "1-2",
            treeId: "treeId",
            x: 1,
            y: 2,
        },
        "1-2": {
            category: "SKILL",
            childrenIds: ["22a", "22b"],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.5,
            y: 1,
        },
        rootId: {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2"],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "treeId",
            x: 0,
            y: 0,
        },
    };

    expect(returnPathFromRootToNode(nodes, "rootId", "21b")).toStrictEqual(["rootId", "1-1", "21b"]);
});

test("findLowestCommonAncestorIdOfNodes - Smallest overlap case", () => {
    const nodes: Dictionary<NormalizedNode> = {
        "21a": {
            category: "SKILL",
            childrenIds: [],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 2,
            nodeId: "21a",
            parentId: "1-1",
            treeId: "treeId",
            x: -1,
            y: 2,
        },
        "21b": {
            category: "SKILL",
            childrenIds: [],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 2,
            nodeId: "21b",
            parentId: "1-1",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "1-1": {
            category: "SKILL",
            childrenIds: ["21a", "21b"],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "treeId",
            x: -0.5,
            y: 1,
        },
        "22a": {
            category: "SKILL",
            childrenIds: [],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 2,
            nodeId: "22a",
            parentId: "1-2",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "22b": {
            category: "SKILL",
            childrenIds: [],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 2,
            nodeId: "22b",
            parentId: "1-2",
            treeId: "treeId",
            x: 1,
            y: 2,
        },
        "1-2": {
            category: "SKILL",
            childrenIds: ["22a", "22b"],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.5,
            y: 1,
        },
        rootId: {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2"],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "treeId",
            x: 0,
            y: 0,
        },
    };

    expect(findLowestCommonAncestorIdOfNodes(nodes, "rootId", "21a", "22b")).toStrictEqual("rootId");
});

test("getDescendantsId - Smallest overlap case", () => {
    const nodes: Dictionary<NormalizedNode> = {
        "21a": {
            category: "SKILL",
            childrenIds: [],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 2,
            nodeId: "21a",
            parentId: "1-1",
            treeId: "treeId",
            x: -1,
            y: 2,
        },
        "21b": {
            category: "SKILL",
            childrenIds: [],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 2,
            nodeId: "21b",
            parentId: "1-1",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "1-1": {
            category: "SKILL",
            childrenIds: ["21a", "21b"],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "treeId",
            x: -0.5,
            y: 1,
        },
        "22a": {
            category: "SKILL",
            childrenIds: [],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 2,
            nodeId: "22a",
            parentId: "1-2",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "22b": {
            category: "SKILL",
            childrenIds: [],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 2,
            nodeId: "22b",
            parentId: "1-2",
            treeId: "treeId",
            x: 1,
            y: 2,
        },
        "1-2": {
            category: "SKILL",
            childrenIds: ["22a", "22b"],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.5,
            y: 1,
        },
        rootId: {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2"],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "treeId",
            x: 0,
            y: 0,
        },
    };

    expect(getDescendantsId(nodes, "rootId")).toStrictEqual(["1-1", "21a", "21b", "1-2", "22a", "22b"]);
});

test("countNodesPerLevel", () => {
    const nodes: Dictionary<NormalizedNode> = {
        "21a": {
            category: "SKILL",
            childrenIds: [],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 2,
            nodeId: "21a",
            parentId: "1-1",
            treeId: "treeId",
            x: -1,
            y: 2,
        },
        "21b": {
            category: "SKILL",
            childrenIds: [],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 2,
            nodeId: "21b",
            parentId: "1-1",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "1-1": {
            category: "SKILL",
            childrenIds: ["21a", "21b"],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "treeId",
            x: -0.5,
            y: 1,
        },
        "22a": {
            category: "SKILL",
            childrenIds: [],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 2,
            nodeId: "22a",
            parentId: "1-2",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "22b": {
            category: "SKILL",
            childrenIds: [],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 2,
            nodeId: "22b",
            parentId: "1-2",
            treeId: "treeId",
            x: 1,
            y: 2,
        },
        "1-2": {
            category: "SKILL",
            childrenIds: ["22a", "22b"],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.5,
            y: 1,
        },
        rootId: {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2"],
            data: {
                name: "foo",
                isCompleted: false,
                icon: { isEmoji: false, text: "foo" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "treeId",
            x: 0,
            y: 0,
        },
    };

    expect(countNodesPerLevel(nodes)).toStrictEqual({ "0": 1, "1": 2, "2": 4 });
});
