import { NormalizedNode, getDefaultSkillValue } from "../types";
import { test, expect } from "@jest/globals";
import { Dictionary } from "@reduxjs/toolkit";
import {
    countNodesPerLevel,
    findLowestCommonAncestorIdOfNodes,
    getDescendantsId,
    getRadialTreeContourByLevel,
    getSubTreesOuterContour,
    returnPathFromRootToNode,
} from "./extractInformationFromTree";

const MOCK_SKILL_VALUE = getDefaultSkillValue("foo", false, { isEmoji: false, text: "foo" });

test("getSubTreesOuterContour", () => {
    const nodes: Dictionary<NormalizedNode> = {
        homepageRoot: {
            category: "USER",
            data: MOCK_SKILL_VALUE,
            isRoot: true,
            level: 0,
            nodeId: "homepageRoot",
            parentId: null,
            treeId: "HomepageTree",
            x: 0,
            y: 0,
            childrenIds: [
                "aQbWCZDIHv4j0hsGnvwq6Y1n",
                "ZaP524wLoByB2YUJZha99ELz",
                "YiXnGOGRi0AM7Qr6NCLpS0Bc",
                "xo1pn5U1LbbyB1WpQqlGzjSC",
                "xq1Ty3XkyYWLlBX8Aoqt6dCP",
            ],
        },
        xq1Ty3XkyYWLlBX8Aoqt6dCP: {
            category: "SKILL_TREE",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "xq1Ty3XkyYWLlBX8Aoqt6dCP",
            parentId: "homepageRoot",
            treeId: "fEot9gYSv0XHOQS6rjTsepnv",
            x: 0.26749882862458735,
            y: 0.963558185417193,
            childrenIds: [],
        },
        xo1pn5U1LbbyB1WpQqlGzjSC: {
            category: "SKILL_TREE",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "xo1pn5U1LbbyB1WpQqlGzjSC",
            parentId: "homepageRoot",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 0.8497906437294646,
            y: 0.5271203485257066,
            childrenIds: ["dMSm122QIC2ZnzKo6YL95lY1", "OO2ZEOy17klSkQeUjlNIEDyC", "c1nWxT1H0LdIJoIeqzpW9jTQ"],
        },
        dMSm122QIC2ZnzKo6YL95lY1: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "dMSm122QIC2ZnzKo6YL95lY1",
            parentId: "xo1pn5U1LbbyB1WpQqlGzjSC",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 1.9641656834119547,
            y: 0.3768994137788611,
            childrenIds: ["yz0AyyeijZ1XZzn8FIOnTKpx"],
        },
        yz0AyyeijZ1XZzn8FIOnTKpx: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "yz0AyyeijZ1XZzn8FIOnTKpx",
            parentId: "dMSm122QIC2ZnzKo6YL95lY1",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 2.946248525117932,
            y: 0.5653491206682917,
            childrenIds: [],
        },
        OO2ZEOy17klSkQeUjlNIEDyC: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "OO2ZEOy17klSkQeUjlNIEDyC",
            parentId: "xo1pn5U1LbbyB1WpQqlGzjSC",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 1.7409957424804483,
            y: 0.9843443628451136,
            childrenIds: ["ETPU6bW0Il8YWK8kgLCztT2y"],
        },
        ETPU6bW0Il8YWK8kgLCztT2y: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "ETPU6bW0Il8YWK8kgLCztT2y",
            parentId: "OO2ZEOy17klSkQeUjlNIEDyC",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 2.6114936137206723,
            y: 1.4765165442676704,
            childrenIds: ["p3edDleaHkS4ULZkHpdYJM8J", "7dAcdJzTOJ2TwT6ltjpJjH4D"],
        },
        p3edDleaHkS4ULZkHpdYJM8J: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "p3edDleaHkS4ULZkHpdYJM8J",
            parentId: "ETPU6bW0Il8YWK8kgLCztT2y",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 3.6302845380053843,
            y: 1.679593454714275,
            childrenIds: [],
        },
        "7dAcdJzTOJ2TwT6ltjpJjH4D": {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "7dAcdJzTOJ2TwT6ltjpJjH4D",
            parentId: "ETPU6bW0Il8YWK8kgLCztT2y",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 3.310724490336077,
            y: 2.244794723151523,
            childrenIds: [],
        },
        c1nWxT1H0LdIJoIeqzpW9jTQ: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "c1nWxT1H0LdIJoIeqzpW9jTQ",
            parentId: "xo1pn5U1LbbyB1WpQqlGzjSC",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 1.2103138953392945,
            y: 1.5922123836814683,
            childrenIds: ["C4pjCLvMIUdw39PsreMyrgb8", "PLqLY3zrO1rje2LdoypEuHtp"],
        },
        C4pjCLvMIUdw39PsreMyrgb8: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "C4pjCLvMIUdw39PsreMyrgb8",
            parentId: "c1nWxT1H0LdIJoIeqzpW9jTQ",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 2.1779496245813217,
            y: 2.0631372791906215,
            childrenIds: ["pGOJR7WrQty7JcW7PY49C7qM"],
        },
        pGOJR7WrQty7JcW7PY49C7qM: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "pGOJR7WrQty7JcW7PY49C7qM",
            parentId: "C4pjCLvMIUdw39PsreMyrgb8",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 2.9039328327750953,
            y: 2.750849705587495,
            childrenIds: [],
        },
        PLqLY3zrO1rje2LdoypEuHtp: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "PLqLY3zrO1rje2LdoypEuHtp",
            parentId: "c1nWxT1H0LdIJoIeqzpW9jTQ",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 1.4051576841546907,
            y: 2.650571991601252,
            childrenIds: ["iaYRS8Ay7HBCXmVpuYqXwzaC", "OAEoTmtL2CQfBKkGOLtoOpKu", "W4cebJSthJvkS687FcB6v4SE"],
        },
        iaYRS8Ay7HBCXmVpuYqXwzaC: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "iaYRS8Ay7HBCXmVpuYqXwzaC",
            parentId: "PLqLY3zrO1rje2LdoypEuHtp",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 2.420627790678589,
            y: 3.1844247673629367,
            childrenIds: [],
        },
        OAEoTmtL2CQfBKkGOLtoOpKu: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "OAEoTmtL2CQfBKkGOLtoOpKu",
            parentId: "PLqLY3zrO1rje2LdoypEuHtp",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 1.873543578872921,
            y: 3.534095988801669,
            childrenIds: [],
        },
        W4cebJSthJvkS687FcB6v4SE: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "W4cebJSthJvkS687FcB6v4SE",
            parentId: "PLqLY3zrO1rje2LdoypEuHtp",
            treeId: "T60Qxm83DTSZYOLsULl78DZZ",
            x: 1.2770948780968334,
            y: 3.7906501648581123,
            childrenIds: [],
        },
        YiXnGOGRi0AM7Qr6NCLpS0Bc: {
            category: "SKILL_TREE",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
            parentId: "homepageRoot",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 0.8238624002599529,
            y: -0.5667898600344833,
            childrenIds: ["juEwrhtZAQ7ZMFm4Y44jG4Ru", "cquIn5zeC4f8fvLQKK2PV2mM", "6nHFVkOqhxQt1t0wJyPH6XVJ"],
        },
        juEwrhtZAQ7ZMFm4Y44jG4Ru: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "juEwrhtZAQ7ZMFm4Y44jG4Ru",
            parentId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 1.1223361117676058,
            y: -1.6554037731690636,
            childrenIds: [],
        },
        cquIn5zeC4f8fvLQKK2PV2mM: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "cquIn5zeC4f8fvLQKK2PV2mM",
            parentId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 1.5921676005118635,
            y: -1.210372806981508,
            childrenIds: ["ZcAeHwZQceTlX4D6I3DU9k1U"],
        },
        ZcAeHwZQceTlX4D6I3DU9k1U: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "ZcAeHwZQceTlX4D6I3DU9k1U",
            parentId: "cquIn5zeC4f8fvLQKK2PV2mM",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 2.3882514007677953,
            y: -1.8155592104722622,
            childrenIds: [],
        },
        "6nHFVkOqhxQt1t0wJyPH6XVJ": {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "6nHFVkOqhxQt1t0wJyPH6XVJ",
            parentId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 1.9472377553615254,
            y: -0.45636073899340673,
            childrenIds: ["o5ZUPWxtFKnBB30tuAw8Xd9w", "UydKvtvXuznmmprn39hDN7Uq"],
        },
        o5ZUPWxtFKnBB30tuAw8Xd9w: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "o5ZUPWxtFKnBB30tuAw8Xd9w",
            parentId: "6nHFVkOqhxQt1t0wJyPH6XVJ",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 2.722713394459948,
            y: -1.2596951105836638,
            childrenIds: ["QOEus1TQ0uHqbW2QYsHoPDGt", "zKJi6y5UdSrQOx4ySeX5djPm", "OeC54kCCSD4l9hhc1V7QkJUA"],
        },
        QOEus1TQ0uHqbW2QYsHoPDGt: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "QOEus1TQ0uHqbW2QYsHoPDGt",
            parentId: "o5ZUPWxtFKnBB30tuAw8Xd9w",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 3.3107244966673264,
            y: -2.244794713813911,
            childrenIds: [],
        },
        zKJi6y5UdSrQOx4ySeX5djPm: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "zKJi6y5UdSrQOx4ySeX5djPm",
            parentId: "o5ZUPWxtFKnBB30tuAw8Xd9w",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 3.630284525946597,
            y: -1.6795934807782182,
            childrenIds: [],
        },
        OeC54kCCSD4l9hhc1V7QkJUA: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "OeC54kCCSD4l9hhc1V7QkJUA",
            parentId: "o5ZUPWxtFKnBB30tuAw8Xd9w",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 3.8541931380908716,
            y: -1.0701379604019472,
            childrenIds: [],
        },
        UydKvtvXuznmmprn39hDN7Uq: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "UydKvtvXuznmmprn39hDN7Uq",
            parentId: "6nHFVkOqhxQt1t0wJyPH6XVJ",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 2.9988998065232737,
            y: -0.08124007899227619,
            childrenIds: ["h1XB4MHwb6UjRndE4yy5H9Fb", "yB7Y5ZFbcvzobGbvDQIBhLBC"],
        },
        h1XB4MHwb6UjRndE4yy5H9Fb: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "h1XB4MHwb6UjRndE4yy5H9Fb",
            parentId: "UydKvtvXuznmmprn39hDN7Uq",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 3.9765507231863846,
            y: -0.43248623784560036,
            childrenIds: [],
        },
        yB7Y5ZFbcvzobGbvDQIBhLBC: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "yB7Y5ZFbcvzobGbvDQIBhLBC",
            parentId: "UydKvtvXuznmmprn39hDN7Uq",
            treeId: "XrWEpaPKRS68T09rlekrkwvY",
            x: 3.9941333783354294,
            y: 0.21656074451943172,
            childrenIds: [],
        },
        ZaP524wLoByB2YUJZha99ELz: {
            category: "SKILL_TREE",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "ZaP524wLoByB2YUJZha99ELz",
            parentId: "homepageRoot",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -0.1818323057845775,
            y: -0.9833295544084211,
            childrenIds: ["nFC97sH2HjHgdirs9DcHO4wb", "oE5PvpfzuzLjD2o2VZ4OJEUN", "EaTStq4s6zIxltcjd0MTaLKS"],
        },
        nFC97sH2HjHgdirs9DcHO4wb: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "nFC97sH2HjHgdirs9DcHO4wb",
            parentId: "ZaP524wLoByB2YUJZha99ELz",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -1.1668731186702903,
            y: -1.624317433546987,
            childrenIds: ["8Gp9OHcp6orUxdHjSfpaVUAH"],
        },
        "8Gp9OHcp6orUxdHjSfpaVUAH": {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "8Gp9OHcp6orUxdHjSfpaVUAH",
            parentId: "nFC97sH2HjHgdirs9DcHO4wb",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -1.7503096780054355,
            y: -2.4364761503204804,
            childrenIds: ["qiDTAMbKL2LqI7oPTlDISWUd"],
        },
        qiDTAMbKL2LqI7oPTlDISWUd: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "qiDTAMbKL2LqI7oPTlDISWUd",
            parentId: "8Gp9OHcp6orUxdHjSfpaVUAH",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -2.3337462373405806,
            y: -3.248634867093974,
            childrenIds: [],
        },
        oE5PvpfzuzLjD2o2VZ4OJEUN: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
            parentId: "ZaP524wLoByB2YUJZha99ELz",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -0.5611862632786044,
            y: -1.9196536088334784,
            childrenIds: ["aIEQEcZwCzYjLK2hHkvso7vB", "R2uls2cGeedOezadmH92BHu8"],
        },
        aIEQEcZwCzYjLK2hHkvso7vB: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "aIEQEcZwCzYjLK2hHkvso7vB",
            parentId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -1.185603984145554,
            y: -2.755783589612615,
            childrenIds: ["bz8QsifzNWuC68BcjQ9KSrq6"],
        },
        bz8QsifzNWuC68BcjQ9KSrq6: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "bz8QsifzNWuC68BcjQ9KSrq6",
            parentId: "aIEQEcZwCzYjLK2hHkvso7vB",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -1.5808053121940717,
            y: -3.6743781194834866,
            childrenIds: [],
        },
        R2uls2cGeedOezadmH92BHu8: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "R2uls2cGeedOezadmH92BHu8",
            parentId: "oE5PvpfzuzLjD2o2VZ4OJEUN",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -0.48546689123439435,
            y: -2.9604597442821636,
            childrenIds: ["tleqTACAMzNV5IWS6PuhKAQa", "eUVW3NvIA3K2JT4cS8Vt4idV"],
        },
        tleqTACAMzNV5IWS6PuhKAQa: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "tleqTACAMzNV5IWS6PuhKAQa",
            parentId: "R2uls2cGeedOezadmH92BHu8",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -0.9655175205387024,
            y: -3.8817233180035897,
            childrenIds: [],
        },
        eUVW3NvIA3K2JT4cS8Vt4idV: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 4,
            nodeId: "eUVW3NvIA3K2JT4cS8Vt4idV",
            parentId: "R2uls2cGeedOezadmH92BHu8",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: -0.32479008630931194,
            y: -3.9867921189642166,
            childrenIds: [],
        },
        EaTStq4s6zIxltcjd0MTaLKS: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "EaTStq4s6zIxltcjd0MTaLKS",
            parentId: "ZaP524wLoByB2YUJZha99ELz",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: 0.5349976626844392,
            y: -1.9271163693254714,
            childrenIds: ["qsVTkuD9OZ9I5Xl7j3Oib1Ox", "NRfw8131hOoU3VPgCoQJSBai", "5q0IMY79rAneVeAHSwRgm8AM"],
        },
        qsVTkuD9OZ9I5Xl7j3Oib1Ox: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "qsVTkuD9OZ9I5Xl7j3Oib1Ox",
            parentId: "EaTStq4s6zIxltcjd0MTaLKS",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: 0.16230968996873413,
            y: -2.9956060429472786,
            childrenIds: [],
        },
        NRfw8131hOoU3VPgCoQJSBai: {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "NRfw8131hOoU3VPgCoQJSBai",
            parentId: "EaTStq4s6zIxltcjd0MTaLKS",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: 0.8024964940266588,
            y: -2.890674553988207,
            childrenIds: [],
        },
        "5q0IMY79rAneVeAHSwRgm8AM": {
            category: "SKILL",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 3,
            nodeId: "5q0IMY79rAneVeAHSwRgm8AM",
            parentId: "EaTStq4s6zIxltcjd0MTaLKS",
            treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
            x: 1.4051576651246802,
            y: -2.6505720016897025,
            childrenIds: [],
        },
        aQbWCZDIHv4j0hsGnvwq6Y1n: {
            category: "SKILL_TREE",
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "aQbWCZDIHv4j0hsGnvwq6Y1n",
            parentId: "homepageRoot",
            treeId: "CXCHHuWKSVVIhTn2wOKjr94x",
            x: -0.7398514313743738,
            y: -0.6727702873145411,
            childrenIds: [],
        },
    };
    expect(getSubTreesOuterContour(nodes, "homepageRoot")).toStrictEqual([
        {
            levelContours: {
                "0": {
                    leftNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                    rightNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                },
                "1": {
                    leftNode: { angleInRadians: 3.87953948, distanceToCenter: 1, id: "aQbWCZDIHv4j0hsGnvwq6Y1n" },
                    rightNode: { angleInRadians: 3.87953948, distanceToCenter: 1, id: "aQbWCZDIHv4j0hsGnvwq6Y1n" },
                },
            },
            maxLevel: 1,
        },
        {
            levelContours: {
                "0": {
                    leftNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                    rightNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                },
                "1": {
                    leftNode: { angleInRadians: 4.52953948, distanceToCenter: 1, id: "ZaP524wLoByB2YUJZha99ELz" },
                    rightNode: { angleInRadians: 4.52953948, distanceToCenter: 1, id: "ZaP524wLoByB2YUJZha99ELz" },
                },
                "2": {
                    leftNode: { angleInRadians: 4.98318531, distanceToCenter: 2, id: "EaTStq4s6zIxltcjd0MTaLKS" },
                    rightNode: { angleInRadians: 4.0894353, distanceToCenter: 2, id: "nFC97sH2HjHgdirs9DcHO4wb" },
                },
                "3": {
                    leftNode: { angleInRadians: 5.19985197, distanceToCenter: 3, id: "5q0IMY79rAneVeAHSwRgm8AM" },
                    rightNode: { angleInRadians: 4.0894353, distanceToCenter: 3, id: "8Gp9OHcp6orUxdHjSfpaVUAH" },
                },
                "4": {
                    leftNode: { angleInRadians: 4.63110197, distanceToCenter: 4, id: "eUVW3NvIA3K2JT4cS8Vt4idV" },
                    rightNode: { angleInRadians: 4.0894353, distanceToCenter: 4, id: "qiDTAMbKL2LqI7oPTlDISWUd" },
                },
            },
            maxLevel: 4,
        },
        {
            levelContours: {
                "0": {
                    leftNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                    rightNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                },
                "1": {
                    leftNode: { angleInRadians: 5.68058115, distanceToCenter: 1, id: "YiXnGOGRi0AM7Qr6NCLpS0Bc" },
                    rightNode: { angleInRadians: 5.68058115, distanceToCenter: 1, id: "YiXnGOGRi0AM7Qr6NCLpS0Bc" },
                },
                "2": {
                    leftNode: { angleInRadians: 6.05297697, distanceToCenter: 2, id: "6nHFVkOqhxQt1t0wJyPH6XVJ" },
                    rightNode: { angleInRadians: 5.30818531, distanceToCenter: 2, id: "juEwrhtZAQ7ZMFm4Y44jG4Ru" },
                },
                "3": {
                    leftNode: { angleInRadians: 6.25610197, distanceToCenter: 3, id: "UydKvtvXuznmmprn39hDN7Uq" },
                    rightNode: { angleInRadians: 5.63318531, distanceToCenter: 3, id: "ZcAeHwZQceTlX4D6I3DU9k1U" },
                },
                "4": {
                    leftNode: { angleInRadians: 0.05416667, distanceToCenter: 4, id: "yB7Y5ZFbcvzobGbvDQIBhLBC" },
                    rightNode: { angleInRadians: 5.68735198, distanceToCenter: 4, id: "QOEus1TQ0uHqbW2QYsHoPDGt" },
                },
            },
            maxLevel: 4,
        },
        {
            levelContours: {
                "0": {
                    leftNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                    rightNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                },
                "1": {
                    leftNode: { angleInRadians: 0.55520833, distanceToCenter: 1, id: "xo1pn5U1LbbyB1WpQqlGzjSC" },
                    rightNode: { angleInRadians: 0.55520833, distanceToCenter: 1, id: "xo1pn5U1LbbyB1WpQqlGzjSC" },
                },
                "2": {
                    leftNode: { angleInRadians: 0.92083333, distanceToCenter: 2, id: "c1nWxT1H0LdIJoIeqzpW9jTQ" },
                    rightNode: { angleInRadians: 0.18958333, distanceToCenter: 2, id: "dMSm122QIC2ZnzKo6YL95lY1" },
                },
                "3": {
                    leftNode: { angleInRadians: 1.08333333, distanceToCenter: 3, id: "PLqLY3zrO1rje2LdoypEuHtp" },
                    rightNode: { angleInRadians: 0.18958333, distanceToCenter: 3, id: "yz0AyyeijZ1XZzn8FIOnTKpx" },
                },
                "4": {
                    leftNode: { angleInRadians: 1.24583333, distanceToCenter: 4, id: "W4cebJSthJvkS687FcB6v4SE" },
                    rightNode: { angleInRadians: 0.43333333, distanceToCenter: 4, id: "p3edDleaHkS4ULZkHpdYJM8J" },
                },
            },
            maxLevel: 4,
        },
        {
            levelContours: {
                "0": {
                    leftNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                    rightNode: { angleInRadians: 0, distanceToCenter: 0, id: "homepageRoot" },
                },
                "1": {
                    leftNode: { angleInRadians: 1.3, distanceToCenter: 1, id: "xq1Ty3XkyYWLlBX8Aoqt6dCP" },
                    rightNode: { angleInRadians: 1.3, distanceToCenter: 1, id: "xq1Ty3XkyYWLlBX8Aoqt6dCP" },
                },
            },
            maxLevel: 1,
        },
    ]);
});

test("returnPathFromRootToNode - Smallest overlap case", () => {
    const nodes: Dictionary<NormalizedNode> = {
        "21a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21a",
            parentId: "1-1",
            treeId: "treeId",
            x: -1,
            y: 2,
        },
        "21b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21b",
            parentId: "1-1",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "1-1": {
            category: "SKILL",
            childrenIds: ["21a", "21b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "treeId",
            x: -0.5,
            y: 1,
        },
        "22a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22a",
            parentId: "1-2",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "22b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22b",
            parentId: "1-2",
            treeId: "treeId",
            x: 1,
            y: 2,
        },
        "1-2": {
            category: "SKILL",
            childrenIds: ["22a", "22b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.5,
            y: 1,
        },
        rootId: {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2"],
            data: MOCK_SKILL_VALUE,
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "treeId",
            x: 0,
            y: 0,
        },
    };

    expect(returnPathFromRootToNode(nodes, "rootId", "21b")).toStrictEqual(["rootId", "1-1", "21b"]);
});

test("findLowestCommonAncestorIdOfNodes - Smallest overlap case", () => {
    const nodes: Dictionary<NormalizedNode> = {
        "21a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21a",
            parentId: "1-1",
            treeId: "treeId",
            x: -1,
            y: 2,
        },
        "21b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21b",
            parentId: "1-1",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "1-1": {
            category: "SKILL",
            childrenIds: ["21a", "21b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "treeId",
            x: -0.5,
            y: 1,
        },
        "22a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22a",
            parentId: "1-2",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "22b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22b",
            parentId: "1-2",
            treeId: "treeId",
            x: 1,
            y: 2,
        },
        "1-2": {
            category: "SKILL",
            childrenIds: ["22a", "22b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.5,
            y: 1,
        },
        rootId: {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2"],
            data: MOCK_SKILL_VALUE,
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "treeId",
            x: 0,
            y: 0,
        },
    };

    expect(findLowestCommonAncestorIdOfNodes(nodes, "rootId", "21a", "22b")).toStrictEqual("rootId");
});

test("getDescendantsId - Smallest overlap case", () => {
    const nodes: Dictionary<NormalizedNode> = {
        "21a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21a",
            parentId: "1-1",
            treeId: "treeId",
            x: -1,
            y: 2,
        },
        "21b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21b",
            parentId: "1-1",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "1-1": {
            category: "SKILL",
            childrenIds: ["21a", "21b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "treeId",
            x: -0.5,
            y: 1,
        },
        "22a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22a",
            parentId: "1-2",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "22b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22b",
            parentId: "1-2",
            treeId: "treeId",
            x: 1,
            y: 2,
        },
        "1-2": {
            category: "SKILL",
            childrenIds: ["22a", "22b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.5,
            y: 1,
        },
        rootId: {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2"],
            data: MOCK_SKILL_VALUE,
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "treeId",
            x: 0,
            y: 0,
        },
    };

    expect(getDescendantsId(nodes, "rootId")).toStrictEqual(["1-1", "21a", "21b", "1-2", "22a", "22b"]);
});

test("countNodesPerLevel", () => {
    const nodes: Dictionary<NormalizedNode> = {
        "21a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21a",
            parentId: "1-1",
            treeId: "treeId",
            x: -1,
            y: 2,
        },
        "21b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21b",
            parentId: "1-1",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "1-1": {
            category: "SKILL",
            childrenIds: ["21a", "21b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "treeId",
            x: -0.5,
            y: 1,
        },
        "22a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22a",
            parentId: "1-2",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "22b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22b",
            parentId: "1-2",
            treeId: "treeId",
            x: 1,
            y: 2,
        },
        "1-2": {
            category: "SKILL",
            childrenIds: ["22a", "22b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.5,
            y: 1,
        },
        rootId: {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2"],
            data: MOCK_SKILL_VALUE,
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "treeId",
            x: 0,
            y: 0,
        },
    };

    expect(countNodesPerLevel(nodes)).toStrictEqual({ "0": 1, "1": 2, "2": 4 });
});

test("getRadialTreeContourByLevel - Smallest overlap case", () => {
    const nodes: Dictionary<NormalizedNode> = {
        "21a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21a",
            parentId: "1-1",
            treeId: "treeId",
            x: -1,
            y: 2,
        },
        "21b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21b",
            parentId: "1-1",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "1-1": {
            category: "SKILL",
            childrenIds: ["21a", "21b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "treeId",
            x: -0.5,
            y: 1,
        },
        "22a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22a",
            parentId: "1-2",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "22b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22b",
            parentId: "1-2",
            treeId: "treeId",
            x: 1,
            y: 2,
        },
        "1-2": {
            category: "SKILL",
            childrenIds: ["22a", "22b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.5,
            y: 1,
        },
        rootId: {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2"],
            data: MOCK_SKILL_VALUE,
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "treeId",
            x: 0,
            y: 0,
        },
    };

    expect(getRadialTreeContourByLevel(nodes, "rootId")).toStrictEqual({
        contourByLevel: {
            "0": [
                {
                    leftNode: { angleInRadians: 0, distanceToCenter: 0, id: "rootId" },
                    rightNode: { angleInRadians: 0, distanceToCenter: 0, id: "rootId" },
                },
            ],
            "1": [
                {
                    leftNode: { angleInRadians: 1.10714872, distanceToCenter: 1.11803399, id: "1-2" },
                    rightNode: { angleInRadians: 2.03444394, distanceToCenter: 1.11803399, id: "1-1" },
                },
            ],
            "2": [
                {
                    leftNode: { angleInRadians: 1.10714872, distanceToCenter: 2.23606798, id: "22b" },
                    rightNode: { angleInRadians: 1.57079633, distanceToCenter: 2, id: "22a" },
                },
                {
                    leftNode: { angleInRadians: 1.57079633, distanceToCenter: 2, id: "21b" },
                    rightNode: { angleInRadians: 2.03444394, distanceToCenter: 2.23606798, id: "21a" },
                },
            ],
        },
        treeLevels: ["0", "1", "2"],
    });
});
