import { expect, test } from "@jest/globals";
import { deleteNodeAndHoistChild, insertNodeAsChild, insertNodeAsParent, insertNodeAsSibling, nodesToUpdateFromTreeMutation } from "./misc";
import { NormalizedNode } from "@/types";

test("Delete and hoist", () => {
    const input: NormalizedNode[] = [
        {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2", "1-3"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: ["2-1", "2-2", "2-3"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-3",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 2,
            nodeId: "2-1",
            parentId: "1-1",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 3,
            nodeId: "3-1",
            parentId: "2-2",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: ["3-1"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 2,
            nodeId: "2-2",
            parentId: "1-1",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 2,
            nodeId: "2-3",
            parentId: "1-1",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
    ];

    const output: {
        nodeIdToDelete: string;
        updatedNodes: NormalizedNode[];
    } = {
        nodeIdToDelete: "1-1",
        updatedNodes: [
            {
                category: "SKILL_TREE",
                childrenIds: ["2-2", "1-2", "1-3"],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: true,
                level: 0,
                nodeId: "rootId",
                parentId: null,
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
            {
                category: "SKILL",
                childrenIds: ["3-1", "2-1", "2-3"],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 2,
                nodeId: "2-2",
                parentId: "rootId",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
            {
                category: "SKILL",
                childrenIds: [],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 2,
                nodeId: "2-1",
                parentId: "2-2",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
            {
                category: "SKILL",
                childrenIds: [],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 2,
                nodeId: "2-3",
                parentId: "2-2",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
        ],
    };

    expect(
        deleteNodeAndHoistChild(input, {
            category: "SKILL",
            childrenIds: ["3-1"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 2,
            nodeId: "2-2",
            parentId: "1-1",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        })
    ).toStrictEqual(output);
});

test("nodesToUpdateFromTreeMutation - Increase level of node and below", () => {
    const nodesOfTree: NormalizedNode[] = [
        {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2", "1-3"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: ["2-1"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-3",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 2,
            nodeId: "2-1",
            parentId: "1-2",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
    ];
    const output: NormalizedNode[] = [
        {
            category: "SKILL",
            childrenIds: ["2-1"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 2,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 3,
            nodeId: "2-1",
            parentId: "1-2",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
    ];

    expect(
        nodesToUpdateFromTreeMutation(
            nodesOfTree,
            {
                category: "SKILL",
                childrenIds: ["2-1"],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 1,
                nodeId: "1-2",
                parentId: "rootId",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
            (v: NormalizedNode) => {
                return { ...v, level: v.level + 1 };
            }
        )
    ).toStrictEqual(output);
});

test("insertNodeAsParent", () => {
    const nodesOfTree: NormalizedNode[] = [
        {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2", "1-3"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-3",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
    ];
    const output: {
        nodesToUpdate: NormalizedNode[];
        nodeToAdd: NormalizedNode;
    } = {
        nodesToUpdate: [
            {
                category: "SKILL_TREE",
                childrenIds: ["1-1", "newNode", "1-3"],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: true,
                level: 0,
                nodeId: "rootId",
                parentId: null,
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
            {
                category: "SKILL",
                childrenIds: [],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 2,
                nodeId: "1-2",
                parentId: "newNode",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
        ],
        nodeToAdd: {
            category: "SKILL",
            childrenIds: ["1-2"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "newNode",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
    };

    expect(
        insertNodeAsParent(
            nodesOfTree,
            {
                category: "SKILL",
                childrenIds: [],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 0,
                nodeId: "newNode",
                parentId: "",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
            { height: 0, ofNode: "1-2", type: "PARENT", width: 0, x: 0, y: 0 }
        )
    ).toStrictEqual(output);
});

test("insertNodeAsLeftSibling", () => {
    const nodesOfTree: NormalizedNode[] = [
        {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2", "1-3"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-3",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
    ];
    const output = {
        nodesToUpdate: [
            {
                category: "SKILL_TREE",
                childrenIds: ["1-1", "newNode", "1-2", "1-3"],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: true,
                level: 0,
                nodeId: "rootId",
                parentId: null,
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
        ],
        nodesToAdd: [
            {
                category: "SKILL",
                childrenIds: [],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 1,
                nodeId: "newNode",
                parentId: "rootId",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
        ],
    };

    expect(
        insertNodeAsSibling(
            nodesOfTree,
            [
                {
                    category: "SKILL",
                    childrenIds: [],
                    data: {
                        usefulResources: [],
                        icon: { isEmoji: false, text: "text" },
                        isCompleted: false,
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        name: "skillName",
                    },
                    isRoot: false,
                    level: 0,
                    nodeId: "newNode",
                    parentId: "",
                    treeId: "mockTreeId",
                    x: 0,
                    y: 0,
                },
            ],
            { height: 0, ofNode: "1-2", type: "LEFT_BROTHER", width: 0, x: 0, y: 0 }
        )
    ).toStrictEqual(output);
});

test("insertNodeAsRightSibling", () => {
    const nodesOfTree: NormalizedNode[] = [
        {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2", "1-3"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-3",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
    ];
    const output = {
        nodesToUpdate: [
            {
                category: "SKILL_TREE",
                childrenIds: ["1-1", "1-2", "newNode", "1-3"],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: true,
                level: 0,
                nodeId: "rootId",
                parentId: null,
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
        ],
        nodesToAdd: [
            {
                category: "SKILL",
                childrenIds: [],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 1,
                nodeId: "newNode",
                parentId: "rootId",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
        ],
    };

    expect(
        insertNodeAsSibling(
            nodesOfTree,
            [
                {
                    category: "SKILL",
                    childrenIds: [],
                    data: {
                        usefulResources: [],
                        icon: { isEmoji: false, text: "text" },
                        isCompleted: false,
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        name: "skillName",
                    },
                    isRoot: false,
                    level: 0,
                    nodeId: "newNode",
                    parentId: "",
                    treeId: "mockTreeId",
                    x: 0,
                    y: 0,
                },
            ],
            { height: 0, ofNode: "1-2", type: "RIGHT_BROTHER", width: 0, x: 0, y: 0 }
        )
    ).toStrictEqual(output);
});

test("insertNodeAsChild - In between nodes", () => {
    const nodesOfTree: NormalizedNode[] = [
        {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2", "1-3"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-3",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
    ];

    const output = {
        nodesToUpdate: [
            {
                category: "SKILL_TREE",
                childrenIds: ["newNode"],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: true,
                level: 0,
                nodeId: "rootId",
                parentId: null,
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
            {
                category: "SKILL",
                childrenIds: [],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 2,
                nodeId: "1-1",
                parentId: "newNode",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
            {
                category: "SKILL",
                childrenIds: [],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 2,
                nodeId: "1-2",
                parentId: "newNode",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
            {
                category: "SKILL",
                childrenIds: [],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 2,
                nodeId: "1-3",
                parentId: "newNode",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
        ],
        nodesToAdd: [
            {
                category: "SKILL",
                childrenIds: ["1-1", "1-2", "1-3"],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 1,
                nodeId: "newNode",
                parentId: "rootId",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
        ],
    };

    expect(
        insertNodeAsChild(
            nodesOfTree,
            [
                {
                    category: "SKILL",
                    childrenIds: [],
                    data: {
                        usefulResources: [],
                        icon: { isEmoji: false, text: "text" },
                        isCompleted: false,
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        name: "skillName",
                    },
                    isRoot: false,
                    level: 0,
                    nodeId: "newNode",
                    parentId: "",
                    treeId: "mockTreeId",
                    x: 0,
                    y: 0,
                },
            ],
            { height: 0, ofNode: "rootId", type: "CHILDREN", width: 0, x: 0, y: 0 }
        )
    ).toStrictEqual(output);
});

test("insertNodeAsChild - At leaf position", () => {
    const nodesOfTree: NormalizedNode[] = [
        {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2", "1-3"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-3",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
    ];

    const output = {
        nodesToUpdate: [],
        nodesToAdd: [
            {
                category: "SKILL",
                childrenIds: [],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 2,
                nodeId: "newNode",
                parentId: "1-1",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
            {
                category: "SKILL",
                childrenIds: [],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 2,
                nodeId: "newNode2",
                parentId: "1-1",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
        ],
    };

    expect(
        insertNodeAsChild(
            nodesOfTree,
            [
                {
                    category: "SKILL",
                    childrenIds: [],
                    data: {
                        usefulResources: [],
                        icon: { isEmoji: false, text: "text" },
                        isCompleted: false,
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        name: "skillName",
                    },
                    isRoot: false,
                    level: 2,
                    nodeId: "newNode",
                    parentId: "1-1",
                    treeId: "mockTreeId",
                    x: 0,
                    y: 0,
                },
                {
                    category: "SKILL",
                    childrenIds: [],
                    data: {
                        usefulResources: [],
                        icon: { isEmoji: false, text: "text" },
                        isCompleted: false,
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        name: "skillName",
                    },
                    isRoot: false,
                    level: 2,
                    nodeId: "newNode2",
                    parentId: "1-1",
                    treeId: "mockTreeId",
                    x: 0,
                    y: 0,
                },
            ],
            { height: 0, ofNode: "1-1", type: "CHILDREN", width: 0, x: 0, y: 0 }
        )
    ).toStrictEqual(output);
});
