import { expect, test } from "@jest/globals";
import { deleteNodeAndHoistChild } from "./misc";
import { NormalizedNode } from "@/types";

test("Delete and hoist", () => {
    const input: NormalizedNode[] = [
        {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2", "1-3"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: ["2-1", "2-2", "2-3"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 1,
            nodeId: "1-3",
            parentId: "rootId",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 2,
            nodeId: "2-1",
            parentId: "1-1",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 3,
            nodeId: "3-1",
            parentId: "2-2",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: ["3-1"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 2,
            nodeId: "2-2",
            parentId: "1-1",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
        {
            category: "SKILL",
            childrenIds: [],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 2,
            nodeId: "2-3",
            parentId: "1-1",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        },
    ];

    const output: {
        nodeIdToDelete: string;
        updatedNodes: NormalizedNode[];
    } = {
        nodeIdToDelete: "1-1",
        updatedNodes: [
            {
                category: "SKILL_TREE",
                childrenIds: ["2-2", "1-2", "1-3"],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: true,
                level: 0,
                nodeId: "rootId",
                parentId: null,
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
            {
                category: "SKILL",
                childrenIds: ["3-1", "2-1", "2-3"],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 2,
                nodeId: "2-2",
                parentId: "rootId",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
            {
                category: "SKILL",
                childrenIds: [],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 2,
                nodeId: "2-1",
                parentId: "2-2",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
            {
                category: "SKILL",
                childrenIds: [],
                data: {
                    usefulResources: [],
                    icon: { isEmoji: false, text: "text" },
                    isCompleted: false,
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    name: "skillName",
                },
                isRoot: false,
                level: 2,
                nodeId: "2-3",
                parentId: "2-2",
                treeId: "mockTreeId",
                x: 0,
                y: 0,
            },
        ],
    };

    expect(
        deleteNodeAndHoistChild(input, {
            category: "SKILL",
            childrenIds: ["3-1"],
            data: {
                usefulResources: [],
                icon: { isEmoji: false, text: "text" },
                isCompleted: false,
                logs: [],
                milestones: [],
                motivesToLearn: [],
                name: "skillName",
            },
            isRoot: false,
            level: 2,
            nodeId: "2-2",
            parentId: "1-1",
            treeId: "mockTreeId",
            x: 0,
            y: 0,
        })
    ).toStrictEqual(output);
});
