import { NormalizedNode, getDefaultSkillValue } from "../../types";
import { expect, test } from "@jest/globals";
import { Dictionary } from "@reduxjs/toolkit";
import { firstIteration } from "./firstInstance";
import { radiusPerLevelToAvoidLevelOvercrowd } from "./levelOvercrowd";

const MOCK_SKILL_VALUE = getDefaultSkillValue("foo", false, { isEmoji: false, text: "foo" });

test("firstInstance - Smallest Overlap Case", () => {
    const nodes: Dictionary<NormalizedNode> = {
        "21a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21a",
            parentId: "1-1",
            treeId: "treeId",
            x: -1,
            y: 2,
        },
        "21b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21b",
            parentId: "1-1",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "1-1": {
            category: "SKILL",
            childrenIds: ["21a", "21b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "treeId",
            x: -0.5,
            y: 1,
        },
        "22a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22a",
            parentId: "1-2",
            treeId: "treeId",
            x: 0,
            y: 2,
        },
        "22b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22b",
            parentId: "1-2",
            treeId: "treeId",
            x: 1,
            y: 2,
        },
        "1-2": {
            category: "SKILL",
            childrenIds: ["22a", "22b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.5,
            y: 1,
        },
        rootId: {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2"],
            data: MOCK_SKILL_VALUE,
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "treeId",
            x: 0,
            y: 0,
        },
    };

    const distanceToCenterPerLevel = radiusPerLevelToAvoidLevelOvercrowd(nodes);

    expect(firstIteration(nodes, "rootId", distanceToCenterPerLevel)).toStrictEqual({
        rootId: {
            category: "SKILL_TREE",
            childrenIds: ["1-1", "1-2"],
            data: MOCK_SKILL_VALUE,
            isRoot: true,
            level: 0,
            nodeId: "rootId",
            parentId: null,
            treeId: "treeId",
            x: 0,
            y: 0,
        },
        "1-1": {
            category: "SKILL",
            childrenIds: ["21a", "21b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-1",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.9476507264148157,
            y: -0.31930878585700095,
        },
        "21a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21a",
            parentId: "1-1",
            treeId: "treeId",
            x: 1.7670133296324289,
            y: -0.9368371752344786,
        },
        "21b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "21b",
            parentId: "1-1",
            treeId: "treeId",
            x: 1.9736518063806572,
            y: -0.3235715487652902,
        },
        "1-2": {
            category: "SKILL",
            childrenIds: ["22a", "22b"],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 1,
            nodeId: "1-2",
            parentId: "rootId",
            treeId: "treeId",
            x: 0.9476507264148157,
            y: 0.31930878585700095,
        },
        "22a": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22a",
            parentId: "1-2",
            treeId: "treeId",
            x: 1.9736518063806572,
            y: 0.3235715487652902,
        },
        "22b": {
            category: "SKILL",
            childrenIds: [],
            data: MOCK_SKILL_VALUE,
            isRoot: false,
            level: 2,
            nodeId: "22b",
            parentId: "1-2",
            treeId: "treeId",
            x: 1.7670133296324289,
            y: 0.9368371752344786,
        },
    });
});
