import { expect, test } from "@jest/globals";
import { PlotCircularTree } from "./general";
import { Skill, Tree } from "../../types";

test("Overflow - One tree at level 1", () => {
    const treeToTest: Tree<Skill> = {
        accentColor: { label: "White", color1: "#FFFFFF", color2: "#CAEFD7" },
        nodeId: "homepageRoot",
        isRoot: true,
        children: [
            {
                treeName: "Lvl1of",
                accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                isRoot: false,
                parentId: "homepageRoot",
                treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                level: 1,
                nodeId: "s57cqMSU0OJrr6rJs7baCCPQ",
                category: "SKILL_TREE",
                children: [
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "A",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "yk114U8gTYGRceAYUpj6O5YY",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "X",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "EakDTvb83eFpiQPF5DkF8Iji",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "S",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "OYn3N3QXUlfGVheklnACuiDd",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "X",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "cGeRehCeLUxvrRHHaC7ncupp",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "V",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "yG0qoX1nyGzRMlmLZQ2xQDD8",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "V",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "qjcxIRvqYd0i0CDGWZ0Ljdug",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "G",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "vrrV9ns3I4NSsdKb00SugmSf",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "F",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "ulS98IJV4u7Oj8ikfm3xupww",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "F",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "uLUNQGFmHLoDTkgrD210Sst0",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "B",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "19sUz5odSdgDjjoYYVUgUMsc",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "N",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "hl6yFEwwfjkyDLMaveGGeG7H",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "A",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "ACvINAgU6kRNx9iQHa9RFDh1",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "V",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "CHriCFd4lmNOTujsBxKBaNm5",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "N",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "ecy6Eb5aDJx7YCECbNsbHDyf",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "S",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "rJowPsYToiMddg7UAi3p7AQM",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "X",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "62x9ehpK07Jub1bu9H6iJinl",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "S",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "NMFhyuksSUhDlMO3mfUspgyd",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "V",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "13yAtFsH0D1GxUfm0h0VzlKz",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "X",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "CkTuuqusuL2ZWnJNcB6TCqxr",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "S",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "yLRKQTwffKpGloI39iio5Ldc",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                    {
                        accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                        treeId: "X2pBmLVF6reOqOoqIKxchvMA",
                        treeName: "Lvl1of",
                        category: "SKILL",
                        children: [],
                        data: {
                            name: "Dn",
                            isCompleted: false,
                            icon: { isEmoji: false, text: "" },
                            logs: [],
                            milestones: [],
                            motivesToLearn: [],
                            usefulResources: [],
                        },
                        isRoot: false,
                        level: 2,
                        nodeId: "6yShMNjWBEdk7qJJtu6tZzrm",
                        parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
                        x: 0,
                        y: 0,
                    },
                ],
                x: 0,
                y: 0,
                data: {
                    name: "Lvl1of",
                    isCompleted: false,
                    icon: { isEmoji: false, text: "L" },
                    logs: [],
                    milestones: [],
                    motivesToLearn: [],
                    usefulResources: [],
                },
            },
        ],
        data: {
            name: "Life Skills",
            isCompleted: false,
            icon: { isEmoji: false, text: "L" },
            logs: [],
            milestones: [],
            motivesToLearn: [],
            usefulResources: [],
        },
        level: 0,
        parentId: null,
        treeId: "HomepageTree",
        treeName: "Life Skills",
        x: 0,
        y: 0,
        category: "USER",
    };
    const result = [
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Dn",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "6yShMNjWBEdk7qJJtu6tZzrm",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: -2.14820033,
            y: -0.3237891,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "S",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "yLRKQTwffKpGloI39iio5Ldc",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: -1.95732331,
            y: -0.94259723,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "X",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "CkTuuqusuL2ZWnJNcB6TCqxr",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: -1.59252952,
            y: -1.47765145,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "V",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "13yAtFsH0D1GxUfm0h0VzlKz",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: -1.08623249,
            y: -1.88140986,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "S",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "NMFhyuksSUhDlMO3mfUspgyd",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: -0.48341893,
            y: -2.11799674,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "X",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "62x9ehpK07Jub1bu9H6iJinl",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: 0.16234851,
            y: -2.16639032,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "S",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "rJowPsYToiMddg7UAi3p7AQM",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: 0.79369058,
            y: -2.02229061,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "N",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "ecy6Eb5aDJx7YCECbNsbHDyf",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: 1.35450976,
            y: -1.69850151,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "V",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "CHriCFd4lmNOTujsBxKBaNm5",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: 1.7949748,
            y: -1.22379309,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "A",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "ACvINAgU6kRNx9iQHa9RFDh1",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: 2.07594845,
            y: -0.64034529,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "N",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "hl6yFEwwfjkyDLMaveGGeG7H",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: 2.17246497,
            y: 0,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "B",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "19sUz5odSdgDjjoYYVUgUMsc",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: 2.07594845,
            y: 0.64034529,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "F",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "uLUNQGFmHLoDTkgrD210Sst0",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: 1.7949748,
            y: 1.22379309,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "F",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "ulS98IJV4u7Oj8ikfm3xupww",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: 1.35450976,
            y: 1.69850151,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "G",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "vrrV9ns3I4NSsdKb00SugmSf",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: 0.79369058,
            y: 2.02229061,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "V",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "qjcxIRvqYd0i0CDGWZ0Ljdug",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: 0.16234851,
            y: 2.16639032,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "V",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "yG0qoX1nyGzRMlmLZQ2xQDD8",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: -0.48341893,
            y: 2.11799674,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "X",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "cGeRehCeLUxvrRHHaC7ncupp",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: -1.08623249,
            y: 1.88140986,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "S",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "OYn3N3QXUlfGVheklnACuiDd",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: -1.59252952,
            y: 1.47765145,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "X",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "EakDTvb83eFpiQPF5DkF8Iji",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: -1.95732331,
            y: 0.94259723,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "A",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "yk114U8gTYGRceAYUpj6O5YY",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: -2.14820033,
            y: 0.3237891,
            level: 2,
            parentId: "s57cqMSU0OJrr6rJs7baCCPQ",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Lvl1of",
                isCompleted: false,
                icon: { isEmoji: false, text: "L" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL_TREE",
            nodeId: "s57cqMSU0OJrr6rJs7baCCPQ",
            treeId: "X2pBmLVF6reOqOoqIKxchvMA",
            treeName: "Lvl1of",
            x: 1,
            y: 0,
            level: 1,
            parentId: "homepageRoot",
        },
        {
            accentColor: { label: "White", color1: "#FFFFFF", color2: "#CAEFD7" },
            data: {
                name: "Life Skills",
                isCompleted: false,
                icon: { isEmoji: false, text: "L" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: true,
            category: "USER",
            nodeId: "homepageRoot",
            treeId: "HomepageTree",
            treeName: "Life Skills",
            x: 0,
            y: 0,
            level: 0,
            parentId: null,
        },
    ];
    expect(PlotCircularTree(treeToTest)).toStrictEqual(result);
});
