import { expect, test } from "@jest/globals";
import { PlotCircularTree } from "./general";
import { Skill, Tree } from "../../types";

test("CircularTree1", () => {
    expect(
        PlotCircularTree({
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            nodeId: "homepageRoot",
            isRoot: true,
            children: [
                {
                    treeName: "TgHshshdhdj",
                    accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
                    isRoot: false,
                    parentId: "homepageRoot",
                    treeId: "8sDjNU7jCKLgXmuY6Fa7N9Zw",
                    level: 0,
                    nodeId: "YnOYZ6TzIXPO9n1ctCjYALBx",
                    category: "SKILL_TREE",
                    children: [
                        {
                            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
                            treeId: "8sDjNU7jCKLgXmuY6Fa7N9Zw",
                            treeName: "TgHshshdhdj",
                            category: "SKILL",
                            children: [
                                {
                                    accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
                                    treeId: "8sDjNU7jCKLgXmuY6Fa7N9Zw",
                                    treeName: "TgHshshdhdj",
                                    category: "SKILL",
                                    children: [],
                                    data: {
                                        name: "1",
                                        isCompleted: false,
                                        icon: { isEmoji: false, text: "" },
                                        logs: [],
                                        milestones: [],
                                        motivesToLearn: [],
                                        usefulResources: [],
                                    },
                                    isRoot: false,
                                    level: 2,
                                    nodeId: "uY8KrW6D5FKsuw8VZviwKYbK",
                                    parentId: "5Bd1Codzk0WsWtCAGX2tP1Ej",
                                    x: 0,
                                    y: 0,
                                },
                                {
                                    accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
                                    treeId: "8sDjNU7jCKLgXmuY6Fa7N9Zw",
                                    treeName: "TgHshshdhdj",
                                    category: "SKILL",
                                    children: [],
                                    data: {
                                        name: "2",
                                        isCompleted: false,
                                        icon: { isEmoji: false, text: "" },
                                        logs: [],
                                        milestones: [],
                                        motivesToLearn: [],
                                        usefulResources: [],
                                    },
                                    isRoot: false,
                                    level: 2,
                                    nodeId: "hCV7q7oJOlbeMeYlyMtIZYlK",
                                    parentId: "5Bd1Codzk0WsWtCAGX2tP1Ej",
                                    x: 0,
                                    y: 0,
                                },
                                {
                                    accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
                                    treeId: "8sDjNU7jCKLgXmuY6Fa7N9Zw",
                                    treeName: "TgHshshdhdj",
                                    category: "SKILL",
                                    children: [],
                                    data: {
                                        name: "3",
                                        isCompleted: false,
                                        icon: { isEmoji: false, text: "" },
                                        logs: [],
                                        milestones: [],
                                        motivesToLearn: [],
                                        usefulResources: [],
                                    },
                                    isRoot: false,
                                    level: 2,
                                    nodeId: "q3O24bcBKTYNzaK0qcs2P1tO",
                                    parentId: "5Bd1Codzk0WsWtCAGX2tP1Ej",
                                    x: 0,
                                    y: 0,
                                },
                            ],
                            data: {
                                name: "A",
                                isCompleted: false,
                                icon: { isEmoji: false, text: "" },
                                logs: [],
                                milestones: [],
                                motivesToLearn: [],
                                usefulResources: [],
                            },
                            isRoot: false,
                            level: 1,
                            nodeId: "5Bd1Codzk0WsWtCAGX2tP1Ej",
                            parentId: "YnOYZ6TzIXPO9n1ctCjYALBx",
                            x: 0,
                            y: 0,
                        },
                        {
                            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
                            treeId: "8sDjNU7jCKLgXmuY6Fa7N9Zw",
                            treeName: "TgHshshdhdj",
                            category: "SKILL",
                            children: [],
                            data: {
                                name: "Bdbdjd",
                                isCompleted: false,
                                icon: { isEmoji: false, text: "" },
                                logs: [],
                                milestones: [],
                                motivesToLearn: [],
                                usefulResources: [],
                            },
                            isRoot: false,
                            level: 1,
                            nodeId: "W9YGjEAjIW5jyZk4UqIsKVDX",
                            parentId: "YnOYZ6TzIXPO9n1ctCjYALBx",
                            x: 0,
                            y: 0,
                        },
                        {
                            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
                            treeId: "8sDjNU7jCKLgXmuY6Fa7N9Zw",
                            treeName: "TgHshshdhdj",
                            category: "SKILL",
                            children: [],
                            data: {
                                name: "C",
                                isCompleted: false,
                                icon: { isEmoji: false, text: "" },
                                logs: [],
                                milestones: [],
                                motivesToLearn: [],
                                usefulResources: [],
                            },
                            isRoot: false,
                            level: 1,
                            nodeId: "8HQgjPwxHMNJnJEfSCJihr2d",
                            parentId: "YnOYZ6TzIXPO9n1ctCjYALBx",
                            x: 0,
                            y: 0,
                        },
                    ],
                    x: 0,
                    y: 0,
                    data: {
                        name: "TgHshshdhdj",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "T" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                },
            ],
            data: {
                name: "Life Skills",
                isCompleted: false,
                icon: { isEmoji: false, text: "L" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            level: 0,
            parentId: null,
            treeId: "HomepageTree",
            treeName: "Life Skills",
            x: 0,
            y: 0,
            category: "USER",
        })
    ).toStrictEqual([
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "C",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "8HQgjPwxHMNJnJEfSCJihr2d",
            treeId: "8sDjNU7jCKLgXmuY6Fa7N9Zw",
            treeName: "TgHshshdhdj",
            x: 1.895,
            y: -0.639,
            level: 2,
            parentId: "YnOYZ6TzIXPO9n1ctCjYALBx",
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "Bdbdjd",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "W9YGjEAjIW5jyZk4UqIsKVDX",
            treeId: "8sDjNU7jCKLgXmuY6Fa7N9Zw",
            treeName: "TgHshshdhdj",
            x: 2,
            y: 0,
            level: 2,
            parentId: "YnOYZ6TzIXPO9n1ctCjYALBx",
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "3",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "q3O24bcBKTYNzaK0qcs2P1tO",
            treeId: "8sDjNU7jCKLgXmuY6Fa7N9Zw",
            treeName: "TgHshshdhdj",
            x: 2.982,
            y: 0.324,
            level: 3,
            parentId: "5Bd1Codzk0WsWtCAGX2tP1Ej",
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "2",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "hCV7q7oJOlbeMeYlyMtIZYlK",
            treeId: "8sDjNU7jCKLgXmuY6Fa7N9Zw",
            treeName: "TgHshshdhdj",
            x: 2.843,
            y: 0.958,
            level: 3,
            parentId: "5Bd1Codzk0WsWtCAGX2tP1Ej",
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "1",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "uY8KrW6D5FKsuw8VZviwKYbK",
            treeId: "8sDjNU7jCKLgXmuY6Fa7N9Zw",
            treeName: "TgHshshdhdj",
            x: 2.571,
            y: 1.547,
            level: 3,
            parentId: "5Bd1Codzk0WsWtCAGX2tP1Ej",
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "A",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "5Bd1Codzk0WsWtCAGX2tP1Ej",
            treeId: "8sDjNU7jCKLgXmuY6Fa7N9Zw",
            treeName: "TgHshshdhdj",
            x: 1.895,
            y: 0.639,
            level: 2,
            parentId: "YnOYZ6TzIXPO9n1ctCjYALBx",
        },
        {
            accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
            data: {
                name: "TgHshshdhdj",
                isCompleted: false,
                icon: { isEmoji: false, text: "T" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL_TREE",
            nodeId: "YnOYZ6TzIXPO9n1ctCjYALBx",
            treeId: "8sDjNU7jCKLgXmuY6Fa7N9Zw",
            treeName: "TgHshshdhdj",
            x: 1,
            y: 0,
            level: 1,
            parentId: "homepageRoot",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Life Skills",
                isCompleted: false,
                icon: { isEmoji: false, text: "L" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: true,
            category: "USER",
            nodeId: "homepageRoot",
            treeId: "HomepageTree",
            treeName: "Life Skills",
            x: 0,
            y: 0,
            level: 0,
            parentId: null,
        },
    ]);
});

test("CircularTree2", () => {
    expect(
        PlotCircularTree({
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            nodeId: "homepageRoot",
            isRoot: true,
            children: [
                {
                    treeName: "Tkrkek",
                    accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                    isRoot: false,
                    parentId: "homepageRoot",
                    treeId: "IbobD75HwID9VjkDvsafIh5t",
                    level: 0,
                    nodeId: "H1Oa1EewWrrAK5m6pHKj8rfB",
                    category: "SKILL_TREE",
                    children: [
                        {
                            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                            treeId: "IbobD75HwID9VjkDvsafIh5t",
                            treeName: "Tkrkek",
                            category: "SKILL",
                            children: [],
                            data: {
                                name: "Uxjdjd",
                                isCompleted: false,
                                icon: { isEmoji: false, text: "" },
                                logs: [],
                                milestones: [],
                                motivesToLearn: [],
                                usefulResources: [],
                            },
                            isRoot: false,
                            level: 1,
                            nodeId: "bxEZH4OV4jNbfpAWOAbyQmJ3",
                            parentId: "H1Oa1EewWrrAK5m6pHKj8rfB",
                            x: 0,
                            y: 0,
                        },
                        {
                            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                            treeId: "IbobD75HwID9VjkDvsafIh5t",
                            treeName: "Tkrkek",
                            category: "SKILL",
                            children: [],
                            data: {
                                name: "Bdjdjs",
                                isCompleted: false,
                                icon: { isEmoji: false, text: "" },
                                logs: [],
                                milestones: [],
                                motivesToLearn: [],
                                usefulResources: [],
                            },
                            isRoot: false,
                            level: 1,
                            nodeId: "Yburz8CPsJgyIoEVAdGwhVxy",
                            parentId: "H1Oa1EewWrrAK5m6pHKj8rfB",
                            x: 0,
                            y: 0,
                        },
                        {
                            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                            treeId: "IbobD75HwID9VjkDvsafIh5t",
                            treeName: "Tkrkek",
                            category: "SKILL",
                            children: [],
                            data: {
                                name: "Bsjsjs",
                                isCompleted: false,
                                icon: { isEmoji: false, text: "" },
                                logs: [],
                                milestones: [],
                                motivesToLearn: [],
                                usefulResources: [],
                            },
                            isRoot: false,
                            level: 1,
                            nodeId: "3UQYM1pNRBr55qDLBWoJ0zpC",
                            parentId: "H1Oa1EewWrrAK5m6pHKj8rfB",
                            x: 0,
                            y: 0,
                        },
                        {
                            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                            treeId: "IbobD75HwID9VjkDvsafIh5t",
                            treeName: "Tkrkek",
                            category: "SKILL",
                            children: [],
                            data: {
                                name: "Dnjsjs",
                                isCompleted: false,
                                icon: { isEmoji: false, text: "" },
                                logs: [],
                                milestones: [],
                                motivesToLearn: [],
                                usefulResources: [],
                            },
                            isRoot: false,
                            level: 1,
                            nodeId: "W9uTVoCFl4S8xgc7wfSTEa1M",
                            parentId: "H1Oa1EewWrrAK5m6pHKj8rfB",
                            x: 0,
                            y: 0,
                        },
                        {
                            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                            treeId: "IbobD75HwID9VjkDvsafIh5t",
                            treeName: "Tkrkek",
                            category: "SKILL",
                            children: [
                                {
                                    accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                                    treeId: "IbobD75HwID9VjkDvsafIh5t",
                                    treeName: "Tkrkek",
                                    category: "SKILL",
                                    children: [],
                                    data: {
                                        name: "Skksks",
                                        isCompleted: false,
                                        icon: { isEmoji: false, text: "" },
                                        logs: [],
                                        milestones: [],
                                        motivesToLearn: [],
                                        usefulResources: [],
                                    },
                                    isRoot: false,
                                    level: 2,
                                    nodeId: "vujNCByABSdf45h6BVZotcFv",
                                    parentId: "GvhYYLzYv9yoP2BIqUscZ0J4",
                                    x: 0,
                                    y: 0,
                                },
                                {
                                    accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                                    treeId: "IbobD75HwID9VjkDvsafIh5t",
                                    treeName: "Tkrkek",
                                    category: "SKILL",
                                    children: [],
                                    data: {
                                        name: "Bdnsjs",
                                        isCompleted: false,
                                        icon: { isEmoji: false, text: "" },
                                        logs: [],
                                        milestones: [],
                                        motivesToLearn: [],
                                        usefulResources: [],
                                    },
                                    isRoot: false,
                                    level: 2,
                                    nodeId: "vCxnByw3abSYBIf4H4tmPdwc",
                                    parentId: "GvhYYLzYv9yoP2BIqUscZ0J4",
                                    x: 0,
                                    y: 0,
                                },
                                {
                                    accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                                    treeId: "IbobD75HwID9VjkDvsafIh5t",
                                    treeName: "Tkrkek",
                                    category: "SKILL",
                                    children: [
                                        {
                                            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                                            treeId: "IbobD75HwID9VjkDvsafIh5t",
                                            treeName: "Tkrkek",
                                            category: "SKILL",
                                            children: [],
                                            data: {
                                                name: "Jdjdjs",
                                                isCompleted: false,
                                                icon: { isEmoji: false, text: "" },
                                                logs: [],
                                                milestones: [],
                                                motivesToLearn: [],
                                                usefulResources: [],
                                            },
                                            isRoot: false,
                                            level: 3,
                                            nodeId: "7oakyY7V6lJwvl2Z7Xy4p1mo",
                                            parentId: "z7nioPZIJHskOs5YAjpX7DKW",
                                            x: 0,
                                            y: 0,
                                        },
                                        {
                                            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                                            treeId: "IbobD75HwID9VjkDvsafIh5t",
                                            treeName: "Tkrkek",
                                            category: "SKILL",
                                            children: [],
                                            data: {
                                                name: "Sjajjs",
                                                isCompleted: false,
                                                icon: { isEmoji: false, text: "" },
                                                logs: [],
                                                milestones: [],
                                                motivesToLearn: [],
                                                usefulResources: [],
                                            },
                                            isRoot: false,
                                            level: 3,
                                            nodeId: "YfwYwj2D4HtlU2zjcfR5EpWM",
                                            parentId: "z7nioPZIJHskOs5YAjpX7DKW",
                                            x: 0,
                                            y: 0,
                                        },
                                    ],
                                    data: {
                                        name: "Sjjsjs",
                                        isCompleted: false,
                                        icon: { isEmoji: false, text: "" },
                                        logs: [],
                                        milestones: [],
                                        motivesToLearn: [],
                                        usefulResources: [],
                                    },
                                    isRoot: false,
                                    level: 2,
                                    nodeId: "z7nioPZIJHskOs5YAjpX7DKW",
                                    parentId: "GvhYYLzYv9yoP2BIqUscZ0J4",
                                    x: 0,
                                    y: 0,
                                },
                                {
                                    accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                                    treeId: "IbobD75HwID9VjkDvsafIh5t",
                                    treeName: "Tkrkek",
                                    category: "SKILL",
                                    children: [],
                                    data: {
                                        name: "Jsjsks",
                                        isCompleted: false,
                                        icon: { isEmoji: false, text: "" },
                                        logs: [],
                                        milestones: [],
                                        motivesToLearn: [],
                                        usefulResources: [],
                                    },
                                    isRoot: false,
                                    level: 2,
                                    nodeId: "hgVd10wt2mjtvWUkoUmAfEoR",
                                    parentId: "GvhYYLzYv9yoP2BIqUscZ0J4",
                                    x: 0,
                                    y: 0,
                                },
                            ],
                            data: {
                                name: "Dnjsjs",
                                isCompleted: true,
                                icon: { isEmoji: false, text: "" },
                                logs: [],
                                milestones: [],
                                motivesToLearn: [],
                                usefulResources: [],
                            },
                            isRoot: false,
                            level: 1,
                            nodeId: "GvhYYLzYv9yoP2BIqUscZ0J4",
                            parentId: "H1Oa1EewWrrAK5m6pHKj8rfB",
                            x: 0,
                            y: 0,
                        },
                    ],
                    x: 0,
                    y: 0,
                    data: {
                        name: "Tkrkek",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "T" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                },
            ],
            data: {
                name: "Life Skills",
                isCompleted: false,
                icon: { isEmoji: false, text: "L" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            level: 0,
            parentId: null,
            treeId: "HomepageTree",
            treeName: "Life Skills",
            x: 0,
            y: 0,
            category: "USER",
        })
    ).toStrictEqual([
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "Jsjsks",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "hgVd10wt2mjtvWUkoUmAfEoR",
            treeId: "IbobD75HwID9VjkDvsafIh5t",
            treeName: "Tkrkek",
            x: 1.684,
            y: -2.483,
            level: 3,
            parentId: "GvhYYLzYv9yoP2BIqUscZ0J4",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "Sjajjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "YfwYwj2D4HtlU2zjcfR5EpWM",
            treeId: "IbobD75HwID9VjkDvsafIh5t",
            treeName: "Tkrkek",
            x: 2.671,
            y: -2.977,
            level: 4,
            parentId: "z7nioPZIJHskOs5YAjpX7DKW",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "Jdjdjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "7oakyY7V6lJwvl2Z7Xy4p1mo",
            treeId: "IbobD75HwID9VjkDvsafIh5t",
            treeName: "Tkrkek",
            x: 3.118,
            y: -2.506,
            level: 4,
            parentId: "z7nioPZIJHskOs5YAjpX7DKW",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "Sjjsjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "z7nioPZIJHskOs5YAjpX7DKW",
            treeId: "IbobD75HwID9VjkDvsafIh5t",
            treeName: "Tkrkek",
            x: 2.178,
            y: -2.063,
            level: 3,
            parentId: "GvhYYLzYv9yoP2BIqUscZ0J4",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "Bdnsjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "vCxnByw3abSYBIf4H4tmPdwc",
            treeId: "IbobD75HwID9VjkDvsafIh5t",
            treeName: "Tkrkek",
            x: 2.571,
            y: -1.547,
            level: 3,
            parentId: "GvhYYLzYv9yoP2BIqUscZ0J4",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "Skksks",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "vujNCByABSdf45h6BVZotcFv",
            treeId: "IbobD75HwID9VjkDvsafIh5t",
            treeName: "Tkrkek",
            x: 2.843,
            y: -0.958,
            level: 3,
            parentId: "GvhYYLzYv9yoP2BIqUscZ0J4",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "Dnjsjs",
                isCompleted: true,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "GvhYYLzYv9yoP2BIqUscZ0J4",
            treeId: "IbobD75HwID9VjkDvsafIh5t",
            treeName: "Tkrkek",
            x: 1.592,
            y: -1.21,
            level: 2,
            parentId: "H1Oa1EewWrrAK5m6pHKj8rfB",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "Dnjsjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "W9uTVoCFl4S8xgc7wfSTEa1M",
            treeId: "IbobD75HwID9VjkDvsafIh5t",
            treeName: "Tkrkek",
            x: 1.895,
            y: -0.639,
            level: 2,
            parentId: "H1Oa1EewWrrAK5m6pHKj8rfB",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "Bsjsjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "3UQYM1pNRBr55qDLBWoJ0zpC",
            treeId: "IbobD75HwID9VjkDvsafIh5t",
            treeName: "Tkrkek",
            x: 2,
            y: 0,
            level: 2,
            parentId: "H1Oa1EewWrrAK5m6pHKj8rfB",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "Bdjdjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "Yburz8CPsJgyIoEVAdGwhVxy",
            treeId: "IbobD75HwID9VjkDvsafIh5t",
            treeName: "Tkrkek",
            x: 1.895,
            y: 0.639,
            level: 2,
            parentId: "H1Oa1EewWrrAK5m6pHKj8rfB",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "Uxjdjd",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "bxEZH4OV4jNbfpAWOAbyQmJ3",
            treeId: "IbobD75HwID9VjkDvsafIh5t",
            treeName: "Tkrkek",
            x: 1.592,
            y: 1.21,
            level: 2,
            parentId: "H1Oa1EewWrrAK5m6pHKj8rfB",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "Tkrkek",
                isCompleted: false,
                icon: { isEmoji: false, text: "T" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL_TREE",
            nodeId: "H1Oa1EewWrrAK5m6pHKj8rfB",
            treeId: "IbobD75HwID9VjkDvsafIh5t",
            treeName: "Tkrkek",
            x: 1,
            y: 0,
            level: 1,
            parentId: "homepageRoot",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Life Skills",
                isCompleted: false,
                icon: { isEmoji: false, text: "L" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: true,
            category: "USER",
            nodeId: "homepageRoot",
            treeId: "HomepageTree",
            treeName: "Life Skills",
            x: 0,
            y: 0,
            level: 0,
            parentId: null,
        },
    ]);
});

test("CircularTree3", () => {
    expect(
        PlotCircularTree({
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            nodeId: "homepageRoot",
            isRoot: true,
            children: [
                {
                    treeName: "B",
                    accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                    isRoot: false,
                    parentId: "homepageRoot",
                    treeId: "KdqtDCmLgAE9Od3o6mYNnhQN",
                    level: 0,
                    nodeId: "hmKCHlNPDIjtvMnmG1qQroa4",
                    category: "SKILL_TREE",
                    children: [
                        {
                            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                            treeId: "KdqtDCmLgAE9Od3o6mYNnhQN",
                            treeName: "B",
                            category: "SKILL",
                            children: [],
                            data: {
                                name: "A",
                                isCompleted: false,
                                icon: { isEmoji: false, text: "" },
                                logs: [],
                                milestones: [],
                                motivesToLearn: [],
                                usefulResources: [],
                            },
                            isRoot: false,
                            level: 1,
                            nodeId: "fpGigYlrkCNFhArd6xdd3hYs",
                            parentId: "hmKCHlNPDIjtvMnmG1qQroa4",
                            x: 0,
                            y: 0,
                        },
                        {
                            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                            treeId: "KdqtDCmLgAE9Od3o6mYNnhQN",
                            treeName: "B",
                            category: "SKILL",
                            children: [
                                {
                                    accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                                    treeId: "KdqtDCmLgAE9Od3o6mYNnhQN",
                                    treeName: "B",
                                    category: "SKILL",
                                    children: [],
                                    data: {
                                        name: "A",
                                        isCompleted: false,
                                        icon: { isEmoji: false, text: "" },
                                        logs: [],
                                        milestones: [],
                                        motivesToLearn: [],
                                        usefulResources: [],
                                    },
                                    isRoot: false,
                                    level: 2,
                                    nodeId: "MyETH2VmEBbqL1cLHV3rNAh4",
                                    parentId: "4X4ohF7P4bwIEMymjl8yuScy",
                                    x: 0,
                                    y: 0,
                                },
                            ],
                            data: {
                                name: "B",
                                isCompleted: false,
                                icon: { isEmoji: false, text: "" },
                                logs: [],
                                milestones: [],
                                motivesToLearn: [],
                                usefulResources: [],
                            },
                            isRoot: false,
                            level: 1,
                            nodeId: "4X4ohF7P4bwIEMymjl8yuScy",
                            parentId: "hmKCHlNPDIjtvMnmG1qQroa4",
                            x: 0,
                            y: 0,
                        },
                        {
                            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                            treeId: "KdqtDCmLgAE9Od3o6mYNnhQN",
                            treeName: "B",
                            category: "SKILL",
                            children: [],
                            data: {
                                name: "C",
                                isCompleted: false,
                                icon: { isEmoji: false, text: "" },
                                logs: [],
                                milestones: [],
                                motivesToLearn: [],
                                usefulResources: [],
                            },
                            isRoot: false,
                            level: 1,
                            nodeId: "QueW8HV7gLPbf1Eq7cBV8ZEC",
                            parentId: "hmKCHlNPDIjtvMnmG1qQroa4",
                            x: 0,
                            y: 0,
                        },
                        {
                            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                            treeId: "KdqtDCmLgAE9Od3o6mYNnhQN",
                            treeName: "B",
                            category: "SKILL",
                            children: [
                                {
                                    accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
                                    treeId: "KdqtDCmLgAE9Od3o6mYNnhQN",
                                    treeName: "B",
                                    category: "SKILL",
                                    children: [],
                                    data: {
                                        name: "S",
                                        isCompleted: false,
                                        icon: { isEmoji: false, text: "" },
                                        logs: [],
                                        milestones: [],
                                        motivesToLearn: [],
                                        usefulResources: [],
                                    },
                                    isRoot: false,
                                    level: 2,
                                    nodeId: "OgoaX6ksSgQx2BBrCZJtXYl7",
                                    parentId: "CDpIS1pMkSL4xubyo9R7QtEe",
                                    x: 0,
                                    y: 0,
                                },
                            ],
                            data: {
                                name: "E",
                                isCompleted: false,
                                icon: { isEmoji: false, text: "" },
                                logs: [],
                                milestones: [],
                                motivesToLearn: [],
                                usefulResources: [],
                            },
                            isRoot: false,
                            level: 1,
                            nodeId: "CDpIS1pMkSL4xubyo9R7QtEe",
                            parentId: "hmKCHlNPDIjtvMnmG1qQroa4",
                            x: 0,
                            y: 0,
                        },
                    ],
                    x: 0,
                    y: 0,
                    data: {
                        name: "B",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "B" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                },
            ],
            data: {
                name: "Life Skills",
                isCompleted: false,
                icon: { isEmoji: false, text: "L" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            level: 0,
            parentId: null,
            treeId: "HomepageTree",
            treeName: "Life Skills",
            x: 0,
            y: 0,
            category: "USER",
        })
    ).toStrictEqual([
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "S",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "OgoaX6ksSgQx2BBrCZJtXYl7",
            treeId: "KdqtDCmLgAE9Od3o6mYNnhQN",
            treeName: "B",
            x: 2.651,
            y: -1.405,
            level: 3,
            parentId: "CDpIS1pMkSL4xubyo9R7QtEe",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "E",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "CDpIS1pMkSL4xubyo9R7QtEe",
            treeId: "KdqtDCmLgAE9Od3o6mYNnhQN",
            treeName: "B",
            x: 1.767,
            y: -0.937,
            level: 2,
            parentId: "hmKCHlNPDIjtvMnmG1qQroa4",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "C",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "QueW8HV7gLPbf1Eq7cBV8ZEC",
            treeId: "KdqtDCmLgAE9Od3o6mYNnhQN",
            treeName: "B",
            x: 1.974,
            y: -0.324,
            level: 2,
            parentId: "hmKCHlNPDIjtvMnmG1qQroa4",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "A",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "MyETH2VmEBbqL1cLHV3rNAh4",
            treeId: "KdqtDCmLgAE9Od3o6mYNnhQN",
            treeName: "B",
            x: 2.96,
            y: 0.485,
            level: 3,
            parentId: "4X4ohF7P4bwIEMymjl8yuScy",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "B",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "4X4ohF7P4bwIEMymjl8yuScy",
            treeId: "KdqtDCmLgAE9Od3o6mYNnhQN",
            treeName: "B",
            x: 1.974,
            y: 0.324,
            level: 2,
            parentId: "hmKCHlNPDIjtvMnmG1qQroa4",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "A",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "fpGigYlrkCNFhArd6xdd3hYs",
            treeId: "KdqtDCmLgAE9Od3o6mYNnhQN",
            treeName: "B",
            x: 1.767,
            y: 0.937,
            level: 2,
            parentId: "hmKCHlNPDIjtvMnmG1qQroa4",
        },
        {
            accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
            data: {
                name: "B",
                isCompleted: false,
                icon: { isEmoji: false, text: "B" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL_TREE",
            nodeId: "hmKCHlNPDIjtvMnmG1qQroa4",
            treeId: "KdqtDCmLgAE9Od3o6mYNnhQN",
            treeName: "B",
            x: 1,
            y: 0,
            level: 1,
            parentId: "homepageRoot",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Life Skills",
                isCompleted: false,
                icon: { isEmoji: false, text: "L" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: true,
            category: "USER",
            nodeId: "homepageRoot",
            treeId: "HomepageTree",
            treeName: "Life Skills",
            x: 0,
            y: 0,
            level: 0,
            parentId: null,
        },
    ]);
});

// test("CircularTest4 - Rairtha 1", () => {
//     const treeToTest: Tree<Skill> = {
//         accentColor: { label: "White", color1: "#FFFFFF", color2: "#CAEFD7" },
//         nodeId: "homepageRoot",
//         isRoot: true,
//         children: [
//             {
//                 treeName: "Muscuki",
//                 accentColor: { label: "Red", color1: "#FE453A", color2: "#FF9F23" },
//                 isRoot: false,
//                 parentId: "homepageRoot",
//                 treeId: "fEot9gYSv0XHOQS6rjTsepnv",
//                 level: 0,
//                 nodeId: "xq1Ty3XkyYWLlBX8Aoqt6dCP",
//                 category: "SKILL_TREE",
//                 children: [],
//                 x: 0,
//                 y: 0,
//                 data: {
//                     name: "Muscuki",
//                     isCompleted: true,
//                     icon: { isEmoji: false, text: "M" },
//                     logs: [],
//                     milestones: [],
//                     motivesToLearn: [],
//                     usefulResources: [],
//                 },
//             },
//             {
//                 treeName: "Degree",
//                 accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
//                 isRoot: false,
//                 parentId: "homepageRoot",
//                 treeId: "T60Qxm83DTSZYOLsULl78DZZ",
//                 level: 0,
//                 nodeId: "xo1pn5U1LbbyB1WpQqlGzjSC",
//                 category: "SKILL_TREE",
//                 children: [
//                     {
//                         accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
//                         treeId: "T60Qxm83DTSZYOLsULl78DZZ",
//                         treeName: "Degree",
//                         category: "SKILL",
//                         children: [
//                             {
//                                 accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
//                                 treeId: "T60Qxm83DTSZYOLsULl78DZZ",
//                                 treeName: "Degree",
//                                 category: "SKILL",
//                                 children: [
//                                     {
//                                         accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
//                                         treeId: "T60Qxm83DTSZYOLsULl78DZZ",
//                                         treeName: "Degree",
//                                         category: "SKILL",
//                                         children: [],
//                                         data: {
//                                             name: "A",
//                                             isCompleted: false,
//                                             icon: { isEmoji: false, text: "" },
//                                             logs: [],
//                                             milestones: [],
//                                             motivesToLearn: [],
//                                             usefulResources: [],
//                                         },
//                                         isRoot: false,
//                                         level: 3,
//                                         nodeId: "W4cebJSthJvkS687FcB6v4SE",
//                                         parentId: "PLqLY3zrO1rje2LdoypEuHtp",
//                                         x: 0,
//                                         y: 0,
//                                     },
//                                     {
//                                         accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
//                                         treeId: "T60Qxm83DTSZYOLsULl78DZZ",
//                                         treeName: "Degree",
//                                         category: "SKILL",
//                                         children: [],
//                                         data: {
//                                             name: "B",
//                                             isCompleted: false,
//                                             icon: { isEmoji: false, text: "" },
//                                             logs: [],
//                                             milestones: [],
//                                             motivesToLearn: [],
//                                             usefulResources: [],
//                                         },
//                                         isRoot: false,
//                                         level: 3,
//                                         nodeId: "OAEoTmtL2CQfBKkGOLtoOpKu",
//                                         parentId: "PLqLY3zrO1rje2LdoypEuHtp",
//                                         x: 0,
//                                         y: 0,
//                                     },
//                                     {
//                                         accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
//                                         treeId: "T60Qxm83DTSZYOLsULl78DZZ",
//                                         treeName: "Degree",
//                                         category: "SKILL",
//                                         children: [],
//                                         data: {
//                                             name: "C",
//                                             isCompleted: false,
//                                             icon: { isEmoji: false, text: "" },
//                                             logs: [],
//                                             milestones: [],
//                                             motivesToLearn: [],
//                                             usefulResources: [],
//                                         },
//                                         isRoot: false,
//                                         level: 3,
//                                         nodeId: "iaYRS8Ay7HBCXmVpuYqXwzaC",
//                                         parentId: "PLqLY3zrO1rje2LdoypEuHtp",
//                                         x: 0,
//                                         y: 0,
//                                     },
//                                 ],
//                                 data: {
//                                     name: "Dkkd",
//                                     isCompleted: false,
//                                     icon: { isEmoji: false, text: "" },
//                                     logs: [],
//                                     milestones: [],
//                                     motivesToLearn: [],
//                                     usefulResources: [],
//                                 },
//                                 isRoot: false,
//                                 level: 2,
//                                 nodeId: "PLqLY3zrO1rje2LdoypEuHtp",
//                                 parentId: "c1nWxT1H0LdIJoIeqzpW9jTQ",
//                                 x: 0,
//                                 y: 0,
//                             },
//                             {
//                                 accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
//                                 treeId: "T60Qxm83DTSZYOLsULl78DZZ",
//                                 treeName: "Degree",
//                                 category: "SKILL",
//                                 children: [
//                                     {
//                                         accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
//                                         treeId: "T60Qxm83DTSZYOLsULl78DZZ",
//                                         treeName: "Degree",
//                                         category: "SKILL",
//                                         children: [
//                                             {
//                                                 accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
//                                                 treeId: "T60Qxm83DTSZYOLsULl78DZZ",
//                                                 treeName: "Degree",
//                                                 category: "SKILL",
//                                                 children: [],
//                                                 data: {
//                                                     name: "S",
//                                                     isCompleted: false,
//                                                     icon: { isEmoji: false, text: "" },
//                                                     logs: [],
//                                                     milestones: [],
//                                                     motivesToLearn: [],
//                                                     usefulResources: [],
//                                                 },
//                                                 isRoot: false,
//                                                 level: 4,
//                                                 nodeId: "7ADT00vLlw0DrwbmeAunKEp6",
//                                                 parentId: "e7OpGNO7tuoSA4rfoTOzBxtW",
//                                                 x: 0,
//                                                 y: 0,
//                                             },
//                                             {
//                                                 accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
//                                                 treeId: "T60Qxm83DTSZYOLsULl78DZZ",
//                                                 treeName: "Degree",
//                                                 category: "SKILL",
//                                                 children: [],
//                                                 data: {
//                                                     name: "V",
//                                                     isCompleted: false,
//                                                     icon: { isEmoji: false, text: "" },
//                                                     logs: [],
//                                                     milestones: [],
//                                                     motivesToLearn: [],
//                                                     usefulResources: [],
//                                                 },
//                                                 isRoot: false,
//                                                 level: 4,
//                                                 nodeId: "35QXTiMkasFfiV9rAI0aZl4N",
//                                                 parentId: "e7OpGNO7tuoSA4rfoTOzBxtW",
//                                                 x: 0,
//                                                 y: 0,
//                                             },
//                                             {
//                                                 accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
//                                                 treeId: "T60Qxm83DTSZYOLsULl78DZZ",
//                                                 treeName: "Degree",
//                                                 category: "SKILL",
//                                                 children: [],
//                                                 data: {
//                                                     name: "X",
//                                                     isCompleted: false,
//                                                     icon: { isEmoji: false, text: "" },
//                                                     logs: [],
//                                                     milestones: [],
//                                                     motivesToLearn: [],
//                                                     usefulResources: [],
//                                                 },
//                                                 isRoot: false,
//                                                 level: 4,
//                                                 nodeId: "RWsXbYYVUkKhw53TnhY7yeHX",
//                                                 parentId: "e7OpGNO7tuoSA4rfoTOzBxtW",
//                                                 x: 0,
//                                                 y: 0,
//                                             },
//                                         ],
//                                         data: {
//                                             name: "F",
//                                             isCompleted: false,
//                                             icon: { isEmoji: false, text: "" },
//                                             logs: [],
//                                             milestones: [],
//                                             motivesToLearn: [],
//                                             usefulResources: [],
//                                         },
//                                         isRoot: false,
//                                         level: 3,
//                                         nodeId: "e7OpGNO7tuoSA4rfoTOzBxtW",
//                                         parentId: "C4pjCLvMIUdw39PsreMyrgb8",
//                                         x: 0,
//                                         y: 0,
//                                     },
//                                     {
//                                         accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
//                                         treeId: "T60Qxm83DTSZYOLsULl78DZZ",
//                                         treeName: "Degree",
//                                         category: "SKILL",
//                                         children: [],
//                                         data: {
//                                             name: "F",
//                                             isCompleted: false,
//                                             icon: { isEmoji: false, text: "" },
//                                             logs: [],
//                                             milestones: [],
//                                             motivesToLearn: [],
//                                             usefulResources: [],
//                                         },
//                                         isRoot: false,
//                                         level: 3,
//                                         nodeId: "jd1qoiMqoHS2cC9YWiid5jky",
//                                         parentId: "C4pjCLvMIUdw39PsreMyrgb8",
//                                         x: 0,
//                                         y: 0,
//                                     },
//                                     {
//                                         accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
//                                         treeId: "T60Qxm83DTSZYOLsULl78DZZ",
//                                         treeName: "Degree",
//                                         category: "SKILL",
//                                         children: [],
//                                         data: {
//                                             name: "F",
//                                             isCompleted: false,
//                                             icon: { isEmoji: false, text: "" },
//                                             logs: [],
//                                             milestones: [],
//                                             motivesToLearn: [],
//                                             usefulResources: [],
//                                         },
//                                         isRoot: false,
//                                         level: 3,
//                                         nodeId: "NGimcP0Rzo17y2hK2cB3193i",
//                                         parentId: "C4pjCLvMIUdw39PsreMyrgb8",
//                                         x: 0,
//                                         y: 0,
//                                     },
//                                     {
//                                         accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
//                                         treeId: "T60Qxm83DTSZYOLsULl78DZZ",
//                                         treeName: "Degree",
//                                         category: "SKILL",
//                                         children: [],
//                                         data: {
//                                             name: "D",
//                                             isCompleted: false,
//                                             icon: { isEmoji: false, text: "" },
//                                             logs: [],
//                                             milestones: [],
//                                             motivesToLearn: [],
//                                             usefulResources: [],
//                                         },
//                                         isRoot: false,
//                                         level: 3,
//                                         nodeId: "iWf29Z73Xp0IfMfJnLO5cNWC",
//                                         parentId: "C4pjCLvMIUdw39PsreMyrgb8",
//                                         x: 0,
//                                         y: 0,
//                                     },
//                                 ],
//                                 data: {
//                                     name: "Coo",
//                                     isCompleted: false,
//                                     icon: { isEmoji: false, text: "" },
//                                     logs: [],
//                                     milestones: [],
//                                     motivesToLearn: [],
//                                     usefulResources: [],
//                                 },
//                                 isRoot: false,
//                                 level: 2,
//                                 nodeId: "C4pjCLvMIUdw39PsreMyrgb8",
//                                 parentId: "c1nWxT1H0LdIJoIeqzpW9jTQ",
//                                 x: 0,
//                                 y: 0,
//                             },
//                         ],
//                         data: {
//                             name: "Uno",
//                             isCompleted: false,
//                             icon: { isEmoji: false, text: "" },
//                             logs: [],
//                             milestones: [],
//                             motivesToLearn: [],
//                             usefulResources: [],
//                         },
//                         isRoot: false,
//                         level: 1,
//                         nodeId: "c1nWxT1H0LdIJoIeqzpW9jTQ",
//                         parentId: "xo1pn5U1LbbyB1WpQqlGzjSC",
//                         x: 0,
//                         y: 0,
//                     },
//                     {
//                         accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
//                         treeId: "T60Qxm83DTSZYOLsULl78DZZ",
//                         treeName: "Degree",
//                         category: "SKILL",
//                         children: [
//                             {
//                                 accentColor: { label: "Yellow", color1: "#FED739", color2: "#FF9F23" },
//                                 treeId: "T60Qxm83DTSZYOLsULl78DZZ",
//                                 treeName: "Degree",
//                                 category: "SKILL",
//                                 children: [],
//                                 data: {
//                                     name: "G",
//                                     isCompleted: false,
//                                     icon: { isEmoji: false, text: "" },
//                                     logs: [],
//                                     milestones: [],
//                                     motivesToLearn: [],
//                                     usefulResources: [],
//                                 },
//                                 isRoot: false,
//                                 level: 2,
//                                 nodeId: "nrNRYtZr79T9Pu9i5icseWl8",
//                                 parentId: "OO2ZEOy17klSkQeUjlNIEDyC",
//                                 x: 0,
//                                 y: 0,
//                             },
//                         ],
//                         data: {
//                             name: "Dos",
//                             isCompleted: false,
//                             icon: { isEmoji: false, text: "" },
//                             logs: [],
//                             milestones: [],
//                             motivesToLearn: [],
//                             usefulResources: [],
//                         },
//                         isRoot: false,
//                         level: 1,
//                         nodeId: "OO2ZEOy17klSkQeUjlNIEDyC",
//                         parentId: "xo1pn5U1LbbyB1WpQqlGzjSC",
//                         x: 0,
//                         y: 0,
//                     },
//                 ],
//                 x: 0,
//                 y: 0,
//                 data: {
//                     name: "Degree",
//                     isCompleted: false,
//                     icon: { isEmoji: false, text: "D" },
//                     logs: [],
//                     milestones: [],
//                     motivesToLearn: [],
//                     usefulResources: [],
//                 },
//             },
//             {
//                 treeName: "Art",
//                 accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
//                 isRoot: false,
//                 parentId: "homepageRoot",
//                 treeId: "XrWEpaPKRS68T09rlekrkwvY",
//                 level: 0,
//                 nodeId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
//                 category: "SKILL_TREE",
//                 children: [
//                     {
//                         accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
//                         treeId: "XrWEpaPKRS68T09rlekrkwvY",
//                         treeName: "Art",
//                         category: "SKILL",
//                         children: [],
//                         data: {
//                             name: "A",
//                             isCompleted: false,
//                             icon: { isEmoji: false, text: "" },
//                             logs: [],
//                             milestones: [],
//                             motivesToLearn: [],
//                             usefulResources: [],
//                         },
//                         isRoot: false,
//                         level: 1,
//                         nodeId: "6nHFVkOqhxQt1t0wJyPH6XVJ",
//                         parentId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
//                         x: 0,
//                         y: 0,
//                     },
//                     {
//                         accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
//                         treeId: "XrWEpaPKRS68T09rlekrkwvY",
//                         treeName: "Art",
//                         category: "SKILL",
//                         children: [],
//                         data: {
//                             name: "B",
//                             isCompleted: false,
//                             icon: { isEmoji: false, text: "" },
//                             logs: [],
//                             milestones: [],
//                             motivesToLearn: [],
//                             usefulResources: [],
//                         },
//                         isRoot: false,
//                         level: 1,
//                         nodeId: "cquIn5zeC4f8fvLQKK2PV2mM",
//                         parentId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
//                         x: 0,
//                         y: 0,
//                     },
//                     {
//                         accentColor: { label: "Orange", color1: "#FF9F23", color2: "#BF5AF2" },
//                         treeId: "XrWEpaPKRS68T09rlekrkwvY",
//                         treeName: "Art",
//                         category: "SKILL",
//                         children: [],
//                         data: {
//                             name: "C",
//                             isCompleted: false,
//                             icon: { isEmoji: false, text: "" },
//                             logs: [],
//                             milestones: [],
//                             motivesToLearn: [],
//                             usefulResources: [],
//                         },
//                         isRoot: false,
//                         level: 1,
//                         nodeId: "juEwrhtZAQ7ZMFm4Y44jG4Ru",
//                         parentId: "YiXnGOGRi0AM7Qr6NCLpS0Bc",
//                         x: 0,
//                         y: 0,
//                     },
//                 ],
//                 x: 0,
//                 y: 0,
//                 data: {
//                     name: "Art",
//                     isCompleted: false,
//                     icon: { isEmoji: false, text: "A" },
//                     logs: [],
//                     milestones: [],
//                     motivesToLearn: [],
//                     usefulResources: [],
//                 },
//             },
//             {
//                 treeName: "Moneys",
//                 accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
//                 isRoot: false,
//                 parentId: "homepageRoot",
//                 treeId: "VIu0RhIaYuFjtCDLmHCtRpXj",
//                 level: 0,
//                 nodeId: "ZaP524wLoByB2YUJZha99ELz",
//                 category: "SKILL_TREE",
//                 children: [],
//                 x: 0,
//                 y: 0,
//                 data: {
//                     name: "Moneys",
//                     isCompleted: true,
//                     icon: { isEmoji: false, text: "M" },
//                     logs: [],
//                     milestones: [],
//                     motivesToLearn: [],
//                     usefulResources: [],
//                 },
//             },
//             {
//                 treeName: "Brain",
//                 accentColor: { label: "Purple", color1: "#BF5AF2", color2: "#5A7BF2" },
//                 isRoot: false,
//                 parentId: "homepageRoot",
//                 treeId: "CXCHHuWKSVVIhTn2wOKjr94x",
//                 level: 0,
//                 nodeId: "aQbWCZDIHv4j0hsGnvwq6Y1n",
//                 category: "SKILL_TREE",
//                 children: [],
//                 x: 0,
//                 y: 0,
//                 data: {
//                     name: "Brain",
//                     isCompleted: true,
//                     icon: { isEmoji: false, text: "B" },
//                     logs: [],
//                     milestones: [],
//                     motivesToLearn: [],
//                     usefulResources: [],
//                 },
//             },
//         ],
//         data: {
//             name: "Life Skills",
//             isCompleted: false,
//             icon: { isEmoji: false, text: "L" },
//             logs: [],
//             milestones: [],
//             motivesToLearn: [],
//             usefulResources: [],
//         },
//         level: 0,
//         parentId: null,
//         treeId: "HomepageTree",
//         treeName: "Life Skills",
//         x: 0,
//         y: 0,
//         category: "USER",
//     };
// });
