import { test, expect } from "@jest/globals";
import { PlotCircularTree } from "./general";
import { Skill, Tree } from "../../types";

const mockTree1: Tree<Skill> = {
    treeName: "Djjsjs",
    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
    isRoot: false,
    parentId: "homepageRoot",
    treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
    level: 0,
    nodeId: "Sh3Wt3Gj09O01a68LMea2kld",
    category: "SKILL_TREE",
    children: [
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            category: "SKILL",
            children: [
                {
                    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                    treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
                    treeName: "Djjsjs",
                    category: "SKILL",
                    children: [],
                    data: {
                        name: "Jdjdks",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                    isRoot: false,
                    level: 2,
                    nodeId: "k8JI3e3U9LynaZl62tG2MOAf",
                    parentId: "Dps3abrdHSs3wRtjTawHMqDd",
                    x: 0,
                    y: 0,
                },
                {
                    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                    treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
                    treeName: "Djjsjs",
                    category: "SKILL",
                    children: [],
                    data: {
                        name: "Ndjdkd",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                    isRoot: false,
                    level: 2,
                    nodeId: "SIMLffgHhUsFkBwLYw83MQvh",
                    parentId: "Dps3abrdHSs3wRtjTawHMqDd",
                    x: 0,
                    y: 0,
                },
                {
                    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                    treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
                    treeName: "Djjsjs",
                    category: "SKILL",
                    children: [],
                    data: {
                        name: "Djjdjd",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                    isRoot: false,
                    level: 2,
                    nodeId: "LCcPNS0QKUCI2LMuq4OxOfpy",
                    parentId: "Dps3abrdHSs3wRtjTawHMqDd",
                    x: 0,
                    y: 0,
                },
                {
                    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                    treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
                    treeName: "Djjsjs",
                    category: "SKILL",
                    children: [],
                    data: {
                        name: "Ksksk",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                    isRoot: false,
                    level: 2,
                    nodeId: "op09WpBM4RlltL0VDAJQvRMa",
                    parentId: "Dps3abrdHSs3wRtjTawHMqDd",
                    x: 0,
                    y: 0,
                },
            ],
            data: {
                name: "Jsjsksk",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "Dps3abrdHSs3wRtjTawHMqDd",
            parentId: "Sh3Wt3Gj09O01a68LMea2kld",
            x: 0,
            y: 0,
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            category: "SKILL",
            children: [],
            data: {
                name: "Hdhdjd",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "wLj501tvNDcNbtwAtl1pmxwU",
            parentId: "Sh3Wt3Gj09O01a68LMea2kld",
            x: 0,
            y: 0,
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            category: "SKILL",
            children: [
                {
                    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                    treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
                    treeName: "Djjsjs",
                    category: "SKILL",
                    children: [],
                    data: {
                        name: "Fndnd",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                    isRoot: false,
                    level: 2,
                    nodeId: "mzYlDRahldUWg1Q6VuKXLzn1",
                    parentId: "cavZkH5wyAzfpr0ptIgxyjMv",
                    x: 0,
                    y: 0,
                },
                {
                    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                    treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
                    treeName: "Djjsjs",
                    category: "SKILL",
                    children: [],
                    data: {
                        name: "Nfndkd",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                    isRoot: false,
                    level: 2,
                    nodeId: "miINbhtWpqroyWLGz3jxZ8RR",
                    parentId: "cavZkH5wyAzfpr0ptIgxyjMv",
                    x: 0,
                    y: 0,
                },
                {
                    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                    treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
                    treeName: "Djjsjs",
                    category: "SKILL",
                    children: [],
                    data: {
                        name: "Sksnls",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                    isRoot: false,
                    level: 2,
                    nodeId: "DPAVNuBdXlo12cEtEJ76WO6Q",
                    parentId: "cavZkH5wyAzfpr0ptIgxyjMv",
                    x: 0,
                    y: 0,
                },
                {
                    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                    treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
                    treeName: "Djjsjs",
                    category: "SKILL",
                    children: [],
                    data: {
                        name: "Djjdjd",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                    isRoot: false,
                    level: 2,
                    nodeId: "JVPdSbEcmDvzhGK3jdJMYjF2",
                    parentId: "cavZkH5wyAzfpr0ptIgxyjMv",
                    x: 0,
                    y: 0,
                },
            ],
            data: {
                name: "Hdjsjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "cavZkH5wyAzfpr0ptIgxyjMv",
            parentId: "Sh3Wt3Gj09O01a68LMea2kld",
            x: 0,
            y: 0,
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            category: "SKILL",
            children: [],
            data: {
                name: "Hcjdks",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "O5dueFuuIcHC6sbYZ26mCdmB",
            parentId: "Sh3Wt3Gj09O01a68LMea2kld",
            x: 0,
            y: 0,
        },
    ],
    x: 0,
    y: 0,
    data: {
        name: "Djjsjs",
        isCompleted: false,
        icon: { isEmoji: false, text: "D" },
        logs: [],
        milestones: [],
        motivesToLearn: [],
        usefulResources: [],
    },
};
const mockTree2: Tree<Skill> = {
    treeName: "Dmsms",
    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
    isRoot: false,
    parentId: "homepageRoot",
    treeId: "e8kQLf8zohRdLptYmTQNGai5",
    level: 0,
    nodeId: "6g1r27ogWij8K9CYFtTS2hHp",
    category: "SKILL_TREE",
    children: [
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            treeId: "e8kQLf8zohRdLptYmTQNGai5",
            treeName: "Dmsms",
            category: "SKILL",
            children: [],
            data: {
                name: "Dnsnjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "J4Za3TQbTaFowriHZnfpduYT",
            parentId: "6g1r27ogWij8K9CYFtTS2hHp",
            x: 0,
            y: 0,
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            treeId: "e8kQLf8zohRdLptYmTQNGai5",
            treeName: "Dmsms",
            category: "SKILL",
            children: [
                {
                    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                    treeId: "e8kQLf8zohRdLptYmTQNGai5",
                    treeName: "Dmsms",
                    category: "SKILL",
                    children: [],
                    data: {
                        name: "Kzksks",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                    isRoot: false,
                    level: 2,
                    nodeId: "mW2NkvUcu9wD0OTmqUBLn7uA",
                    parentId: "HTERILctE4CIDD7HWGp9VWm9",
                    x: 0,
                    y: 0,
                },
            ],
            data: {
                name: "Hdjdjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "HTERILctE4CIDD7HWGp9VWm9",
            parentId: "6g1r27ogWij8K9CYFtTS2hHp",
            x: 0,
            y: 0,
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            treeId: "e8kQLf8zohRdLptYmTQNGai5",
            treeName: "Dmsms",
            category: "SKILL",
            children: [],
            data: {
                name: "Bdhdjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "DwCJ2JWysUac0SQ1H6sLnPtt",
            parentId: "6g1r27ogWij8K9CYFtTS2hHp",
            x: 0,
            y: 0,
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            treeId: "e8kQLf8zohRdLptYmTQNGai5",
            treeName: "Dmsms",
            category: "SKILL",
            children: [
                {
                    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                    treeId: "e8kQLf8zohRdLptYmTQNGai5",
                    treeName: "Dmsms",
                    category: "SKILL",
                    children: [],
                    data: {
                        name: "Hzjdjsj",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                    isRoot: false,
                    level: 2,
                    nodeId: "uPPJQ9FlPIW5159dVuzTkaVs",
                    parentId: "tMPa8AYFuTsaMwYBVv689n7t",
                    x: 0,
                    y: 0,
                },
            ],
            data: {
                name: "Dhsjjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "tMPa8AYFuTsaMwYBVv689n7t",
            parentId: "6g1r27ogWij8K9CYFtTS2hHp",
            x: 0,
            y: 0,
        },
    ],
    x: 0,
    y: 0,
    data: {
        name: "Dmsms",
        isCompleted: false,
        icon: { isEmoji: false, text: "D" },
        logs: [],
        milestones: [],
        motivesToLearn: [],
        usefulResources: [],
    },
};
const mockTree3: Tree<Skill> = {
    treeName: "Djdjks",
    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
    isRoot: false,
    parentId: "homepageRoot",
    treeId: "BNurenqfTcHV7xItZPUWmRc5",
    level: 0,
    nodeId: "QCfqZbm0QHNLsVXuzLY4uREW",
    category: "SKILL_TREE",
    children: [
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            category: "SKILL",
            children: [
                {
                    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                    treeId: "BNurenqfTcHV7xItZPUWmRc5",
                    treeName: "Djdjks",
                    category: "SKILL",
                    children: [],
                    data: {
                        name: "Bzbsbjs",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                    isRoot: false,
                    level: 2,
                    nodeId: "c3yNdq0NuOuJMWB4bvjVKks6",
                    parentId: "LCoIuPtcCtTxdrIxCvFRQ8zG",
                    x: 0,
                    y: 0,
                },
                {
                    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                    treeId: "BNurenqfTcHV7xItZPUWmRc5",
                    treeName: "Djdjks",
                    category: "SKILL",
                    children: [
                        {
                            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                            treeId: "BNurenqfTcHV7xItZPUWmRc5",
                            treeName: "Djdjks",
                            category: "SKILL",
                            children: [],
                            data: {
                                name: "Holal",
                                isCompleted: false,
                                icon: { isEmoji: false, text: "" },
                                logs: [],
                                milestones: [],
                                motivesToLearn: [],
                                usefulResources: [],
                            },
                            isRoot: false,
                            level: 3,
                            nodeId: "oxchna5q801ag0ecoY7NrRD1",
                            parentId: "l5fUHw7ZlVUuSweHYyVfHPca",
                            x: 0,
                            y: 0,
                        },
                        {
                            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                            treeId: "BNurenqfTcHV7xItZPUWmRc5",
                            treeName: "Djdjks",
                            category: "SKILL",
                            children: [],
                            data: {
                                name: "Nsjsks",
                                isCompleted: false,
                                icon: { isEmoji: false, text: "" },
                                logs: [],
                                milestones: [],
                                motivesToLearn: [],
                                usefulResources: [],
                            },
                            isRoot: false,
                            level: 3,
                            nodeId: "vkh4HCRcE7uE33KXlHssjej2",
                            parentId: "l5fUHw7ZlVUuSweHYyVfHPca",
                            x: 0,
                            y: 0,
                        },
                    ],
                    data: {
                        name: "Bxbdnsjs",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                    isRoot: false,
                    level: 2,
                    nodeId: "l5fUHw7ZlVUuSweHYyVfHPca",
                    parentId: "LCoIuPtcCtTxdrIxCvFRQ8zG",
                    x: 0,
                    y: 0,
                },
                {
                    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                    treeId: "BNurenqfTcHV7xItZPUWmRc5",
                    treeName: "Djdjks",
                    category: "SKILL",
                    children: [],
                    data: {
                        name: "Bdndndjs",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                    isRoot: false,
                    level: 2,
                    nodeId: "wE9jatTQPXg75C84KuGnZWFb",
                    parentId: "LCoIuPtcCtTxdrIxCvFRQ8zG",
                    x: 0,
                    y: 0,
                },
                {
                    accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
                    treeId: "BNurenqfTcHV7xItZPUWmRc5",
                    treeName: "Djdjks",
                    category: "SKILL",
                    children: [],
                    data: {
                        name: "Bdbsjsj",
                        isCompleted: false,
                        icon: { isEmoji: false, text: "" },
                        logs: [],
                        milestones: [],
                        motivesToLearn: [],
                        usefulResources: [],
                    },
                    isRoot: false,
                    level: 2,
                    nodeId: "3KTQpxGHBdFPRVTxUmRQfZKh",
                    parentId: "LCoIuPtcCtTxdrIxCvFRQ8zG",
                    x: 0,
                    y: 0,
                },
            ],
            data: {
                name: "Ndnsns",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "LCoIuPtcCtTxdrIxCvFRQ8zG",
            parentId: "QCfqZbm0QHNLsVXuzLY4uREW",
            x: 0,
            y: 0,
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            category: "SKILL",
            children: [],
            data: {
                name: "Nznsks",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "RI5yKr6z7aWBI55wTjibLysi",
            parentId: "QCfqZbm0QHNLsVXuzLY4uREW",
            x: 0,
            y: 0,
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            category: "SKILL",
            children: [],
            data: {
                name: "Nxnsksl",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "HJuyJcra51MNbpP3r2OtdYQu",
            parentId: "QCfqZbm0QHNLsVXuzLY4uREW",
            x: 0,
            y: 0,
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            category: "SKILL",
            children: [],
            data: {
                name: "Ndnsn",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "cL3gbS6xAelLEqdD3WyJzHe1",
            parentId: "QCfqZbm0QHNLsVXuzLY4uREW",
            x: 0,
            y: 0,
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            category: "SKILL",
            children: [],
            data: {
                name: "Sllaña",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            level: 1,
            nodeId: "YOQoORMUcCkBam4n3Yza5jC6",
            parentId: "QCfqZbm0QHNLsVXuzLY4uREW",
            x: 0,
            y: 0,
        },
    ],
    x: 0,
    y: 0,
    data: {
        name: "Djdjks",
        isCompleted: false,
        icon: { isEmoji: false, text: "D" },
        logs: [],
        milestones: [],
        motivesToLearn: [],
        usefulResources: [],
    },
};

test("CircularTree1", () => {
    expect(
        PlotCircularTree({
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            nodeId: "homepageRoot",
            isRoot: true,
            children: [mockTree1],
            data: {
                name: "Life Skills",
                isCompleted: false,
                icon: { isEmoji: false, text: "L" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            level: 0,
            parentId: null,
            treeId: "HomepageTree",
            treeName: "Life Skills",
            x: 0,
            y: 0,
            category: "USER",
        })
    ).toStrictEqual([
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Jdjdks",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "k8JI3e3U9LynaZl62tG2MOAf",
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            x: 1.547,
            y: -2.57,
            level: 3,
            parentId: "Dps3abrdHSs3wRtjTawHMqDd",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Ndjdkd",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "SIMLffgHhUsFkBwLYw83MQvh",
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            x: 2.062,
            y: -2.179,
            level: 3,
            parentId: "Dps3abrdHSs3wRtjTawHMqDd",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Djjdjd",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "LCcPNS0QKUCI2LMuq4OxOfpy",
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            x: 2.483,
            y: -1.684,
            level: 3,
            parentId: "Dps3abrdHSs3wRtjTawHMqDd",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Ksksk",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "op09WpBM4RlltL0VDAJQvRMa",
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            x: 2.787,
            y: -1.11,
            level: 3,
            parentId: "Dps3abrdHSs3wRtjTawHMqDd",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Jsjsksk",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "Dps3abrdHSs3wRtjTawHMqDd",
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            x: 1.525,
            y: -1.294,
            level: 2,
            parentId: "Sh3Wt3Gj09O01a68LMea2kld",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Hdhdjd",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "wLj501tvNDcNbtwAtl1pmxwU",
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            x: 1.927,
            y: -0.534,
            level: 2,
            parentId: "Sh3Wt3Gj09O01a68LMea2kld",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Fndnd",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "mzYlDRahldUWg1Q6VuKXLzn1",
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            x: 2.961,
            y: -0.484,
            level: 3,
            parentId: "cavZkH5wyAzfpr0ptIgxyjMv",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Nfndkd",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "miINbhtWpqroyWLGz3jxZ8RR",
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            x: 2.996,
            y: 0.162,
            level: 3,
            parentId: "cavZkH5wyAzfpr0ptIgxyjMv",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Sksnls",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "DPAVNuBdXlo12cEtEJ76WO6Q",
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            x: 2.891,
            y: 0.803,
            level: 3,
            parentId: "cavZkH5wyAzfpr0ptIgxyjMv",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Djjdjd",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "JVPdSbEcmDvzhGK3jdJMYjF2",
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            x: 2.651,
            y: 1.404,
            level: 3,
            parentId: "cavZkH5wyAzfpr0ptIgxyjMv",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Hdjsjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "cavZkH5wyAzfpr0ptIgxyjMv",
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            x: 1.973,
            y: 0.325,
            level: 2,
            parentId: "Sh3Wt3Gj09O01a68LMea2kld",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Hcjdks",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "O5dueFuuIcHC6sbYZ26mCdmB",
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            x: 1.767,
            y: 0.938,
            level: 2,
            parentId: "Sh3Wt3Gj09O01a68LMea2kld",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Djjsjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "D" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL_TREE",
            nodeId: "Sh3Wt3Gj09O01a68LMea2kld",
            treeId: "ngUlxSF3zGgzCbBx2PG8EHST",
            treeName: "Djjsjs",
            x: 0.994,
            y: -0.108,
            level: 1,
            parentId: "homepageRoot",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Life Skills",
                isCompleted: false,
                icon: { isEmoji: false, text: "L" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: true,
            category: "USER",
            nodeId: "homepageRoot",
            treeId: "HomepageTree",
            treeName: "Life Skills",
            x: 0,
            y: 0,
            level: 0,
            parentId: null,
        },
    ]);
});

test("CircularTree2", () => {
    expect(
        PlotCircularTree({
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            nodeId: "homepageRoot",
            isRoot: true,
            children: [mockTree2],
            data: {
                name: "Life Skills",
                isCompleted: false,
                icon: { isEmoji: false, text: "L" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            level: 0,
            parentId: null,
            treeId: "HomepageTree",
            treeName: "Life Skills",
            x: 0,
            y: 0,
            category: "USER",
        })
    ).toStrictEqual([
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Dnsnjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "J4Za3TQbTaFowriHZnfpduYT",
            treeId: "e8kQLf8zohRdLptYmTQNGai5",
            treeName: "Dmsms",
            x: 1.767,
            y: -0.937,
            level: 2,
            parentId: "6g1r27ogWij8K9CYFtTS2hHp",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Kzksks",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "mW2NkvUcu9wD0OTmqUBLn7uA",
            treeId: "e8kQLf8zohRdLptYmTQNGai5",
            treeName: "Dmsms",
            x: 2.96,
            y: -0.485,
            level: 3,
            parentId: "HTERILctE4CIDD7HWGp9VWm9",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Hdjdjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "HTERILctE4CIDD7HWGp9VWm9",
            treeId: "e8kQLf8zohRdLptYmTQNGai5",
            treeName: "Dmsms",
            x: 1.974,
            y: -0.324,
            level: 2,
            parentId: "6g1r27ogWij8K9CYFtTS2hHp",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Bdhdjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "DwCJ2JWysUac0SQ1H6sLnPtt",
            treeId: "e8kQLf8zohRdLptYmTQNGai5",
            treeName: "Dmsms",
            x: 1.974,
            y: 0.324,
            level: 2,
            parentId: "6g1r27ogWij8K9CYFtTS2hHp",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Hzjdjsj",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "uPPJQ9FlPIW5159dVuzTkaVs",
            treeId: "e8kQLf8zohRdLptYmTQNGai5",
            treeName: "Dmsms",
            x: 2.651,
            y: 1.405,
            level: 3,
            parentId: "tMPa8AYFuTsaMwYBVv689n7t",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Dhsjjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "tMPa8AYFuTsaMwYBVv689n7t",
            treeId: "e8kQLf8zohRdLptYmTQNGai5",
            treeName: "Dmsms",
            x: 1.767,
            y: 0.937,
            level: 2,
            parentId: "6g1r27ogWij8K9CYFtTS2hHp",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Dmsms",
                isCompleted: false,
                icon: { isEmoji: false, text: "D" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL_TREE",
            nodeId: "6g1r27ogWij8K9CYFtTS2hHp",
            treeId: "e8kQLf8zohRdLptYmTQNGai5",
            treeName: "Dmsms",
            x: 1,
            y: 0,
            level: 1,
            parentId: "homepageRoot",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Life Skills",
                isCompleted: false,
                icon: { isEmoji: false, text: "L" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: true,
            category: "USER",
            nodeId: "homepageRoot",
            treeId: "HomepageTree",
            treeName: "Life Skills",
            x: 0,
            y: 0,
            level: 0,
            parentId: null,
        },
    ]);
});

test("CircularTree3", () => {
    expect(
        PlotCircularTree({
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            nodeId: "homepageRoot",
            isRoot: true,
            children: [mockTree3],
            data: {
                name: "Life Skills",
                isCompleted: false,
                icon: { isEmoji: false, text: "L" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            level: 0,
            parentId: null,
            treeId: "HomepageTree",
            treeName: "Life Skills",
            x: 0,
            y: 0,
            category: "USER",
        })
    ).toStrictEqual([
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Bzbsbjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "c3yNdq0NuOuJMWB4bvjVKks6",
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            x: 1.684,
            y: -2.483,
            level: 3,
            parentId: "LCoIuPtcCtTxdrIxCvFRQ8zG",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Holal",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "oxchna5q801ag0ecoY7NrRD1",
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            x: 2.671,
            y: -2.977,
            level: 4,
            parentId: "l5fUHw7ZlVUuSweHYyVfHPca",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Nsjsks",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "vkh4HCRcE7uE33KXlHssjej2",
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            x: 3.118,
            y: -2.506,
            level: 4,
            parentId: "l5fUHw7ZlVUuSweHYyVfHPca",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Bxbdnsjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "l5fUHw7ZlVUuSweHYyVfHPca",
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            x: 2.178,
            y: -2.063,
            level: 3,
            parentId: "LCoIuPtcCtTxdrIxCvFRQ8zG",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Bdndndjs",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "wE9jatTQPXg75C84KuGnZWFb",
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            x: 2.571,
            y: -1.547,
            level: 3,
            parentId: "LCoIuPtcCtTxdrIxCvFRQ8zG",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Bdbsjsj",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "3KTQpxGHBdFPRVTxUmRQfZKh",
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            x: 2.843,
            y: -0.958,
            level: 3,
            parentId: "LCoIuPtcCtTxdrIxCvFRQ8zG",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Ndnsns",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "LCoIuPtcCtTxdrIxCvFRQ8zG",
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            x: 1.592,
            y: -1.21,
            level: 2,
            parentId: "QCfqZbm0QHNLsVXuzLY4uREW",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Nznsks",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "RI5yKr6z7aWBI55wTjibLysi",
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            x: 1.895,
            y: -0.639,
            level: 2,
            parentId: "QCfqZbm0QHNLsVXuzLY4uREW",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Nxnsksl",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "HJuyJcra51MNbpP3r2OtdYQu",
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            x: 2,
            y: 0,
            level: 2,
            parentId: "QCfqZbm0QHNLsVXuzLY4uREW",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Ndnsn",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "cL3gbS6xAelLEqdD3WyJzHe1",
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            x: 1.895,
            y: 0.639,
            level: 2,
            parentId: "QCfqZbm0QHNLsVXuzLY4uREW",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Sllaña",
                isCompleted: false,
                icon: { isEmoji: false, text: "" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL",
            nodeId: "YOQoORMUcCkBam4n3Yza5jC6",
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            x: 1.592,
            y: 1.21,
            level: 2,
            parentId: "QCfqZbm0QHNLsVXuzLY4uREW",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Djdjks",
                isCompleted: false,
                icon: { isEmoji: false, text: "D" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: false,
            category: "SKILL_TREE",
            nodeId: "QCfqZbm0QHNLsVXuzLY4uREW",
            treeId: "BNurenqfTcHV7xItZPUWmRc5",
            treeName: "Djdjks",
            x: 1,
            y: 0,
            level: 1,
            parentId: "homepageRoot",
        },
        {
            accentColor: { label: "Green", color1: "#50D158", color2: "#1982F9" },
            data: {
                name: "Life Skills",
                isCompleted: false,
                icon: { isEmoji: false, text: "L" },
                logs: [],
                milestones: [],
                motivesToLearn: [],
                usefulResources: [],
            },
            isRoot: true,
            category: "USER",
            nodeId: "homepageRoot",
            treeId: "HomepageTree",
            treeName: "Life Skills",
            x: 0,
            y: 0,
            level: 0,
            parentId: null,
        },
    ]);
});
